<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Eventos de Usuario
        <small>Sistema</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="index.html"><i class="fa fa-dashboard"></i> Inicio</a>
        </li>
        <li>
            <a>Eventos de Usuario</a>
        </li>
        <li class="active">
            <strong>Listado General</strong>
        </li>
    </ol>
</section>

<?= BarView::renderBar('messages'); ?>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="box">
        <!-- /.box-header -->
        <div class="box-body">

            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover dataTables">
                    <thead>
                    <tr>
                        <th width="5%">Nº</th>
                        <th width="10%">Fecha</th>
                        <th>Evento</th>
                        <th>Usuario</th>
                        <th>Mensaje</th>
                        <th>Detalles</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    /* @var SysEventUser $eventUser*/
                    $toEditLink = URI::toPage() . 'edit/';
                    $toDeleteLink = URI::toPage() . 'delete/';
                    $i = 0;
                    foreach ($eventUserPager as $eventUser):

                        $pk = $eventUser->getId();

                        ?>
                        <tr role="row">
                            <td><?= $eventUserPager->getFirstIndex() + $i; ?></td>
                            <td><?= $eventUser->getDate('d/m/Y H:i:s'); ?></td>
                            <td><?= $eventUser->getSysEvent()->getName(); ?></td>
                            <td><?= $eventUser->getSysUser()->getUsername(); ?></td>
                            <td><?= $eventUser->getMessage(); ?></td>
                            <td><?= $eventUser->getDetails(); ?></td>
                        </tr>
                        <?php
                        $i++;
                    endforeach;
                    ?>
                    </tbody>
                </table>
            </div>

        </div>
        <!-- /.box-body -->
        <div class="box-footer">
        </div>
        <!-- /.box-footer-->
    </div>
    <!-- /.box -->

</section>
<!-- /.content -->


<script>
    $(document).ready(function () {
        $('.dataTables').DataTable({
            language: {
                "emptyTable": "No se encontraron registros"
            },
            dom: '<"pull-right btn-group"B>lTfgitp',
            buttons: [
                {extend: 'copy', text: 'Copiar', className: 'btn-sm'},
                {extend: 'csv', text: 'CSV', className: 'btn-sm'},
                {extend: 'excel', text: 'Excel', className: 'btn-sm'},
                {extend: 'pdf', text: 'PDF', className: 'btn-sm'},
                {extend: 'print', text: 'Imprimir', className: 'btn-sm',
                    customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');
                        $(win.document.body).find('table')
                            .addClass('compact')
                            .css('font-size', 'inherit');
                    }
                }
            ]
        });
    });
</script>