
<div class="form-group">
    <label class="control-label col-sm-3" for="UserId">SysUser</label>
    <div class="col-sm-9">
        <select id="UserId" name="UserId"
                class="form-control">
            <option value="">-Select-</option>
        <?php
        foreach($sysUserList as $sysUser):
            $sel = $userParam && $userParam->getUserId() ==  <?=$sysUser->getId()? 'selected="yes"': '';
        ?>
        <option value="<?=$sysUser->getId();?>" <?=$sel;?>><?=$sysUser->getId();?></option>
        <?php
        endforeach;
        ?>
        </select>
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="ParamId">SysParam</label>
    <div class="col-sm-9">
        <select id="ParamId" name="ParamId"
                class="form-control">
            <option value="">-Select-</option>
        <?php
        foreach($sysParamList as $sysParam):
            $sel = $userParam && $userParam->getParamId() ==  <?=$sysParam->getId()? 'selected="yes"': '';
        ?>
        <option value="<?=$sysParam->getId();?>" <?=$sel;?>><?=$sysParam->getId();?></option>
        <?php
        endforeach;
        ?>
        </select>
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Value">Value</label>
    <div class="col-sm-9">
        
        <input type="text" id="Value" name="Value" value="<?=$userParam? $userParam->getValue(): '';?>" placeholder="Value..."
               class="form-control" maxlength="200" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Description">Description</label>
    <div class="col-sm-9">
        
        <input type="text" id="Description" name="Description" value="<?=$userParam? $userParam->getDescription(): '';?>" placeholder="Description..."
               class="form-control" maxlength="300" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="LastUserId">Last User Id</label>
    <div class="col-sm-9">
        
        <input type="text" id="LastUserId" name="LastUserId" value="<?=$userParam? $userParam->getLastUserId(): '';?>" placeholder="LastUserId..."
               class="form-control" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="CreationDate">Creation Date</label>
    <div class="col-sm-9">
        
        <input type="text" id="CreationDate" name="CreationDate" value="<?=$userParam? $userParam->getCreationDate(): '';?>" placeholder="CreationDate..."
               class="form-control" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="ModificationDate">Modification Date</label>
    <div class="col-sm-9">
        
        <input type="text" id="ModificationDate" name="ModificationDate" value="<?=$userParam? $userParam->getModificationDate(): '';?>" placeholder="ModificationDate..."
               class="form-control" />
        
    </div>
</div>
    
<script type="text/javascript">
    $().ready(function(){
        $('.ajaxPost').formAjaxPost();
    });
</script>