<?php
/**
 * Generated by Chocala Framework.
 * 
 */
class UserParamService extends GenericService
{

    /**
    * @var UserParamService
    */
    protected static $instance = null;

    public function createQuery()
    {
        return SysUserParamQuery::create();
    }

    /**
     * @param $pk
     * @return array|mixed|SysUserParam
     * @throws NotFoundException
     */
    public function findPk($pk)
    {
        $userParam = $this->createQuery()->findPk($pk);
        if (!is_object($userParam)) {
            throw new NotFoundException(ChocalaErrors::INVALID_RESOURCE);
        }
        return $userParam;
    }

    public function dataList($filters=[])
    {
        $query = $this->createQuery();
        /**
         * put here your filters code
         *
        if(isset($filters['field'])){
            $query->filterByField(filters['field']);
        }
         */
        $_page = $filters['_page']?: 1;
        $_max = $filters['_max']?: $query->count();
        return $query->paginate($_page, $_max);
    }

    public function insertOrUpdate($data, &$userParam = null)
    {
        if(!is_object($userParam)){
            $userParam = new SysUserParam();
        }
        $userParam->fromArray($data);
        $results['success'] = $userParam->validate();
        if ($results['success']) {
            $userParam->save();
        }
        $results['object'] = $userParam;
        $results['errors'] = $userParam->getErrorsMap();
        return $results;
    }

}