<?php
/**
 * Generated by Chocala Framework.
 * 
 */
class UserParamController extends AdminWebController
{

    /**
    * @service UserParamService Injected service
    * @var UserParamService
    */
    protected $userParamService;

    public function index()
    {
        $this->redirectTo(['action' => 'dataList']);
    }

    public function dataList()
    {
        $filters = Req::all();
        $filters['_page'] = $filters['_page']?: 1;
        $filters['_max'] = $filters['_max']?: 10;
        $userParamPager = $this->userParamService->dataList($filters);
        $this->set('userParamPager', $userParamPager);
    }

    public function show()
    {
        $userParam = $this->objectIfExist();
        $this->set('userParam', $userParam);
    }

    public function create()
    {
        $userParam = new SysUserParam();
        $sysUserList = SysUserQuery::create()
                ->orderById()->find();
        $this->set('sysUserList', $sysUserList);
        $sysParamList = SysParamQuery::create()
                ->orderById()->find();
        $this->set('sysParamList', $sysParamList);
        $this->set('userParam', $userParam);
        $this->view->changeLayout('ajax');
    }

    public function save()
    {
        $results = $this->userParamService->insertOrUpdate(Req::all());
        $this->set('userParam', $results['object']);
        $this->set('success', $results['success']);
        $this->set('errors', $results['errors']);
        $this->renderAsJSON();
    }

    public function edit()
    {
        $userParam = $this->objectIfExist();
    $sysUserList = SysUserQuery::create()
                ->orderById()->find();
        $this->set('sysUserList', $sysUserList);
    $sysParamList = SysParamQuery::create()
                ->orderById()->find();
        $this->set('sysParamList', $sysParamList);
        $this->set('userParam', $userParam);
        $this->view->changeLayout('ajax');
    }

    public function update()
    {
        $userParam = $this->objectIfExist();
        $results = $this->userParamService->insertOrUpdate(Req::all(), $userParam);
        $this->set('userParam', $userParam);
        $this->set('success', $results['success']);
        $this->set('errors', $results['errors']);
        $this->renderAsJSON();
    }

    public function delete()
    {
        $userParam = $this->objectIfExist();
        try {
            $userParam->delete();
            $this->redirectTo(['action' => 'dataList']);
        } catch (Exception $e) {
            $this->redirectTo(['action' => 'show',
                'id' => $userParam->getPrimaryKey()]);
        }
    }

    public function objectIfExist()
    {
        try {
            return $this->userParamService->findPk($this->id);
        } catch (ChocalaException $che) {
            HttpManager::responseAs404();
        }
    }

}