<?= BarView::renderBar('messages'); ?>
<div class="dialog" style="padding: 0 250px">
    
    <div class="fRight">
        <a href="<?= URI::toPage(); ?>" class="linkGoBack">Cancel edition</a>
    </div>
    
    <h1>Update JobStudent</h1>    
    <hr class="clear" />
    
    <form method="POST" action="<?= URI::toPage(); ?>update/<?= $jobStudentInstance->getPrimaryKey(); ?>">
        
        <div class="input">
            <label class="name">NAME</label>
            <div class="value">
                
                <input type="text" name="nAME" value="<?= $jobStudentInstance->getNAME(); ?>" maxlength="20" />
                
            </div>
        </div>
            
        <div class="input">
            <label class="name">LASTNAME</label>
            <div class="value">
                
                <input type="text" name="lASTNAME" value="<?= $jobStudentInstance->getLASTNAME(); ?>" maxlength="20" />
                
            </div>
        </div>
            
        <div class="input">
            <label class="name">CREATIONDATE</label>
            <div class="value">
                
                <input type="text" name="cREATIONDATE" value="<?= $jobStudentInstance->getCREATIONDATE(); ?>" />
                
            </div>
        </div>
            
        <div class="input">
            <label class="name">MODIFICATIONDATE</label>
            <div class="value">
                
                <input type="text" name="mODIFICATIONDATE" value="<?= $jobStudentInstance->getMODIFICATIONDATE(); ?>" />
                
            </div>
        </div>
            
        <div class="input">
            <label class="name">STATUS</label>
            <div class="value">
                
                <input type="text" name="sTATUS" value="<?= $jobStudentInstance->getSTATUS(); ?>" maxlength="20" />
                
            </div>
        </div>
            
        <div class="input">
            <div class="value">
                <input type="submit" name="update" value="Update" />
            </div>
        </div>

    </form>
</div>