<?php
/**
 * Generated by Chocala Framework.
 * 
 */
class JobStudentController extends WebController
{

    public function index()
    {
        $this->redirectTo(array('action' => 'dataList'));
    }

    public function dataList()
    {
        $_page = $_GET['page']?: 1;
        $_max = $_GET['max']?: 10;
        $jobStudentPager = JobStudentQuery::create()->paginate($_page, $_max);
        $this->set('jobStudentPager', $jobStudentPager);
    }

    public function show()
    {
        $jobStudentInstance = $this->getObjectIfExist();
        $this->set('jobStudentInstance', $jobStudentInstance);
    }

    public function create()
    {
    }

    public function save()
    {
        $jobStudentInstance = new JobStudent();
        $jobStudentInstance->fromArray($_POST, BasePeer::TYPE_STUDLYPHPNAME);
        if ($jobStudentInstance->validate()) {
            $jobStudentInstance->save();
            $this->redirectTo(array('action' => 'show',
                'id' => $jobStudentInstance->getPrimaryKey()));
        } else {
            $this->set('jobStudentInstance', $jobStudentInstance);
            $this->set('errors', $jobStudentInstance->getErrorsMap());
            $this->renderView('create');
        }
    }

    public function edit()
    {
        $jobStudentInstance = $this->getObjectIfExist();
        $this->set('jobStudentInstance', $jobStudentInstance);
    }

    public function update()
    {
        $jobStudentInstance = $this->getObjectIfExist();
        $jobStudentInstance->fromArray($_POST, BasePeer::TYPE_STUDLYPHPNAME);
        if ($jobStudentInstance->validate()) {
            $jobStudentInstance->save();
            $this->redirectTo(array('action' => 'show',
                'id' => $jobStudentInstance->getPrimaryKey()));
        } else {
            $this->set('jobStudentInstance', $jobStudentInstance);
            $this->set('errors', $jobStudentInstance->getErrorsMap());
            $this->renderView('edit');
        }
    }

    public function delete()
    {
        $jobStudentInstance = $this->getObjectIfExist();
        try {
            $jobStudentInstance->delete();
            $this->redirectTo(array('action' => 'dataList'));
        } catch (Exception $e) {
            $this->redirectTo(array('action' => 'show',
                'id' => $jobStudentInstance->getPrimaryKey()));
        }
    }

    public function getObjectIfExist()
    {
        $object = JobStudentPeer::retrieveByPk($this->id);
        if (!is_object($object)) {
            $this->redirectTo(array('action' => 'dataList'));
        }
        return $object;
    }

}