<div class="loginColumns animated fadeInDown">
    <div class="row">

        <div class="col-md-6">
            <h2 class="font-bold">¡Bienvenido a <?=Configs::value('app.name');?>!</h2>

            <p>
                <strong>Centro de Acceso al Sistema</strong>
            </p>

            <p class="text-center">
                <img src="<?=WEB_ROOT.'img/Logo-Buscar-Empleos-Click.png';?>" alt="Empleos.Click" title="Empleos.Click el portal de empleos de Bolivia" />
            </p>

            <p>
                <small>El uso de tus datos es completamente confidencial, solamente podrá utilizarlo el usuario registrado a nombre de su empresa y en ningun caso compartiremos sus datos.</small>
<!--                <small>El uso de tus datos es completamente confidencial, solamente podrá ser utilizado en casos de reclutamiento y selección de empresas interesadas en tus servicios.</small>-->
            </p>

        </div>
        <div class="col-md-6">
            <div class="ibox-content">
                <form class="m-t" role="form" method="post" action="<?= URI::toPage().'login'; ?>">

                    <?= BarView::renderBar('messages'); ?>

                    <div class="form-group">
                        <input type="text" name="username" class="form-control" placeholder="Usuario" required="">
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" class="form-control" placeholder="Contraseña" required="">
                    </div>
                    <button type="submit" class="btn btn-primary block full-width m-b">Ingresar <i class="fa fa-sign-in"></i></button>

                    <a href="#">
                        <small>¿Olvidaste tu contraseña?</small>
                    </a>

                    <hr />

                    <p class="text-muted text-center">
                        <small>¿No tienes una cuenta?</small>
                    </p>
                    <a class="btn btn-sm btn-white btn-block" href="<?=Uri::createURLTo(['uri' => 'bolsa/trabajo/empresa']);?>">Crear una cuenta <i class="fa fa-external-link"></i></a>
                </form>
            </div>
        </div>
    </div>
    <br/><br/>
    <hr/>
</div>

<!-- page script -->
<script type="text/javascript">
$().ready(function(){

});
</script>