<div class="box">
    <div class="box-header">
        <h1>Bienvenid@ <?=$user->person()->getFirstName();?>!</h1>
    </div>
    <div class="box-body">
        <p class="text-left">Administración del Sistema</p>
    </div>
    <div class="text-center">
        <div class="infont col-md-3 col-sm-4">
            <a href="<?=URI::createURLTo(['uri'=>'customers/aviso']);?>"><i class="fa fa-archive fa-5x"></i> <br />Gestión de  Avisos</a>
        </div>
<!--        <img alt="" class="img-circle hide1" src="--><?//=IMG_WEB;?><!--logofi.png.jpg"/>-->
    </div>
</div>
<!-- page script -->
<script type="text/javascript">
</script>