<div class="box">
    <div class="box-header">
        <h1>Bienvenid@ <?=$user->person()->getFirstName();?>!</h1>
    </div>
    <div class="box-body">
        <p class="text-left">Administración del Sistema</p>
    </div>
    <div class="text-center">
        <img alt="" class="img-circle hide1" src="<?=IMG_WEB;?>logofi.png.jpg"/>
    </div>
</div>
<!-- page script -->
<script type="text/javascript">
</script>