<div id="bodyWork" class="bg-black">
        <div class="form-box" id="login-box">
            <form action="<?=URI::toPage().'login'?>" method="post">
                <div class="body bg-gray">
                   Esta intentando entrar a una sección restringida del sistema.
                    <p><a href="<?=URI::toPage().'access';?>">Acceso al Sistema>></a></p>
                </div>
            </form>
        </div>

</div>
<!-- page script -->
<script type="text/javascript">
</script>