<h1>Recuperación de su Contraseña</h1>

<div class="wrapper wrapper-content animated fadeIn">
    <div class="row">

        <div class="col-lg-6">
            <div class="ibox float-e-margins">

                <?php
                if($passwordRequest->getActive()) {
                ?>
                <div class="ibox-title">
                    <h5>Registro de Contraseña</h5>
                </div>

                <form action="<?=URI::toPage().'resetPassword2/'.$passwordRequest->getHashString();?>" method="post" role="form" class="ajaxPost form-horizontal">

                    <div class="ibox-content">

                        <div id="errorMessages" class="alert alert-danger">
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-4" for="Password"> Nueva Contraseña</label>
                            <div class="col-sm-8">
                                <input type="password" id="Password" name="Password" value=""
                                       size="30" maxlength="30" class="form-control" placeholder="Nuevo password...." autocomplete="off" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-4" for="RPassword">Repetir Contraseña</label>
                            <div class="col-sm-8">
                                <input type="password" id="RPassword" name="RPassword" value=""
                                       size="30" maxlength="30" class="form-control" placeholder="Repetir password...." autocomplete="off" />
                            </div>
                        </div>

                        <small class="text-blue">Es recomedable usar caracteres mayúsculas, minúsculas, numerales y otros.</small>

                    </div>
                    <div class="ibox-footer">
                        <div class="text-right">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Aceptar</button>
                        </div>
                    </div>
                </form>
                <?php
                } else {
                ?>
                    <div class="alert alert-info">
                        La solicitud de recuperación de contraseña ya no esta vigente, intente nuevamente por favor. <a href="<?=URI::toPage();?>">Volver a Principal</a>
                    </div>
                <?php
                }
                ?>

            </div>
        </div>

    </div>
</div>

<script type="text/javascript">
$().ready(function() {
    $("#errorMessages").hide();
    $(".ajaxPost").formAjaxPost({
        'onErrors': function ($form, message) {
            $("#errorMessages").show().html(message);
        },
        'onSuccess': function (data) {
            $("#errorMessages").hide();
            window.location.replace("<?=URI::toPage().'main';?>");
        }
    });
});
</script>