<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Areas</h2>
        <ol class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>
                <a>Areas</a>
            </li>
            <li class="active">
                <strong>Listado General</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

    <?= BarView::renderBar('messages'); ?>

    <div class="row">

        <div class="ibox float-e-margins">

            <div class="ibox-title">
                <h5>Lista de Areas</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#">Opción 1</a>
                        </li>
                    </ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>

            <div class="ibox-content">

                <div class="btn-group">
                    <?php if(PageControl::canCreate()){ ?>


                    <a href="<?= URI::toPage().'create'; ?>" class="btn btn-sm btn-primary btn-rounded" data-toggle="modal" data-target="#ajax-modal-lg">
                            <span class="fa fa-plus-square"></span> Agregar Area</a>
                    <?php } ?>
                </div>

                <div class="table-responsive">

                    <table class="table table-striped table-bordered table-hover dataTables" >
                        <thead>
                            <tr>
                                <th>Código</th>
                                <th width="10%">Nombre</th>
                                <th>Descripcion</th>
                                <th>Estado</th>
                                <th width="15%">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $toDetailsLink = URI::toPage().'show/';
                            $toEditLink = URI::toPage().'edit/';
                            $toDeleteLink = URI::toPage().'delete/';
                            $i = 0;
                            foreach($areaPager as $area):
                                $pk = $area->getId();
                            ?>
                            <tr role="row">
                                <td class="text-left"><?= $area->getCodigo(); ?></td>

                                <td class="text-left"><?= $area->getNombre(); ?></td>
                                <td class="text-left"><?= $area->getDescripcion(); ?></td>
                                <td class="text-left"><?= $area->getStatus(); ?></td>
                                <td class="text-center">
                                    <a href="<?= $toDetailsLink.$pk; ?>" class="btn btn-sm btn-success btn-circle"><i class="fa fa-eye"></i></a>
                                    <?php
                                    if(PageControl::canUpdate()){
                                        ?>
                                        <a href="<?= $toEditLink.$pk; ?>" class="btn btn-sm btn-warning btn-circle" data-toggle="modal" data-target="#ajax-modal-lg"><i class="fa fa-edit"></i></a>
                                        <?php
                                    }
                                    if(PageControl::canDelete()){
                                        ?>
                                        <a href="<?= $toDeleteLink.$pk; ?>"class="btn btn-sm btn-danger btn-circle" onclick="return confirm('¿Esta seguro de eliminar este registro? ');"><i class="fa fa-times"></i></a>
                                        <?php
                                    }
                                    ?>
                                </td>
                            </tr>
                            <?php
                            $i++;
                            endforeach;
                            ?>
                        </tbody>
                    </table>

                </div>

            </div>

        </div>

    </div>
</div>

<script>
$(document).ready(function(){
    $('.dataTables').DataTable({
        "language": {
            "emptyTable": "No se encontraron registros"
        },
        dom: '<"html5buttons"B>lTfgitp',
        buttons: [
            {extend: 'copy', title: 'Copiar'},
            {extend: 'csv', title: 'Reporte CSV'},
            {extend: 'excel', title: 'Reporte Excel'},
            {extend: 'pdf', title: 'Reporte PDF'},
            {extend: 'print',
                customize: function (win){
                    $(win.document.body).addClass('white-bg');
                    $(win.document.body).css('font-size', '10px');
                    $(win.document.body).find('table')
                        .addClass('compact')
                        .css('font-size', 'inherit');
                }
            }
        ]
    });
});
</script>