<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Directorio de Empresas <small>(Base de Datos)</small></h2>
        <ol class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>
                <a href="<?= URI::toPage() ?>">Recursos</a>
            </li>
            <li class="active">
                <strong>Directorio de Empresas (Base de Datos)</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

    <?= BarView::renderBar('messages'); ?>

    <div class="row">

        <div class="ibox float-e-margins">

            <div class="ibox-title">
                <h5>Resumen del Directorio de Empresas</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#">Opción 1</a>
                        </li>
                    </ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>

            <div class="ibox-content">

                <div class="btn-group">
                </div>

                <div class="row">

                    <div class="table-responsive col-md-6">

                        <h4>Por Departamento</h4>
                        <table class="table table-striped table-bordered table-hover dataTables" >
                            <thead>
                            <tr>
                                <th width="5%">Nº</th>
                                <th width="40%">Departamento</th>
                                <th>Total</th>
                                <th width="15%">Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            $toDetailsLink = URI::toPage() . 'detailsDpto/';
                            $i = 0;
                            foreach ($resultsDpto as $result):
                                $i++;
                                ?>
                                <tr role="row">
                                    <td class="text-center"><?= $i; ?></td>
                                    <td class="text-left"><?= $result->DPTO; ?></td>
                                    <td class="text-right"><?= $result->TOTAL; ?></td>
                                    <td class="text-center">
                                        <a href="<?= $toDetailsLink . $pk; ?>"
                                           class="btn btn-sm btn-success btn-circle"><i class="fa fa-eye"></i></a>
                                    </td>
                                </tr>
                                <?php
                            endforeach;
                            ?>
                            </tbody>
                        </table>
                    </div>

                    <div class="table-responsive col-md-6">

                        <h4>Por Tipo de Constitución</h4>
                        <table class="table table-striped table-bordered table-hover dataTables" >
                            <thead>
                            <tr>
                                <th width="5%">Nº</th>
                                <th width="40%">Departamento</th>
                                <th>Total</th>
                                <th width="15%">Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            $toDetailsLink = URI::toPage() . 'detailsTps/';
                            $i = 0;
                            foreach ($resultsTps as $result):
                                $i++;
                                ?>
                                <tr role="row">
                                    <td class="text-center"><?= $i; ?></td>
                                    <td class="text-left"><?= $result->TPS; ?></td>
                                    <td class="text-right"><?= $result->TOTAL; ?></td>
                                    <td class="text-center">
                                        <a href="<?= $toDetailsLink . $pk; ?>"
                                           class="btn btn-sm btn-success btn-circle"><i class="fa fa-eye"></i></a>
                                    </td>
                                </tr>
                                <?php
                            endforeach;
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
