<?php
/**
 * Generated by Chocala Framework.
 *
 */
class PostulacionService extends AppSecureService
{
    /**
     * @var PostulacionService
     */
    protected static $instance = null;

    public function createQuery()
    {
        return JobPostulanteAvisoQuery::create();
    }

    /**
     * @return PostulacionService
     */
    public static function instance()
    {
        return parent::instance(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $pk
     * @return array|JobPostulanteAviso|mixed
     * @throws NotFoundException
     */
    public function findPk($pk)
    {
        $auth = $this->createQuery()->findPk($pk);
        if (!is_object($auth)) {
            throw new NotFoundException(ChocalaErrors::INVALID_RESOURCE);
        }
        return $auth;
    }

    public function insertOrUpdate($data, &$postulanteAviso = null)
    {
        if(!is_object($postulanteAviso)){
            $postulanteAviso = new JobPostulanteAviso();
        }
        $postulanteAviso->fromArray($data);
        $postulanteAviso->save();
        $results['object'] = $postulanteAviso;
        $results['errors'] = [];//$postulanteAviso->getErrorsMap();
        return $results;
    }

    public function findPostulacion($idPostulante, $idAviso)
    {
        return JobPostulanteAvisoQuery::create()
            ->filterByIdPostulante($idPostulante)
            ->filterByIdAviso($idAviso)
            ->findOne();
    }

    /**
     * @param $user SysUser
     */
    public function getPostulantePorUsuario($user, $data = [])
    {
        $postulante = JobPostulanteQuery::create()->findOneByUserId($user->getId());
        if(!is_object($postulante)){
            $person = SysPersonQuery::create()->findOneByUserId($user->getId());
            if(isset($data["celular"])){
                $person->setCellphone1($data["celular"])->save();
            }
            $aResult = PostulanteService::instance()->insertOrUpdate([
                "UserId" => $user->getId(),
                "Nombres" => $person->getFirstName(),
                "Apellido1" => $person->getLastName(),
                "Email" => $user->getEmail(),
                "Estado" => JobPostulante::ESTADO_NUEVO,
                "Celular1" => $person->getCellphone1(),
            ]);
            if(is_object($aResult["object"])){
                return $aResult["object"];
            }
        }
        return $postulante;
    }

    public function findPostulacionPorIdUsuario($idUsuario, $idAviso)
    {
        return JobPostulanteAvisoQuery::create()
            ->useJobPostulanteQuery()
                ->filterByUserId($idUsuario)
            ->endUse()
            ->filterByIdAviso($idAviso)
            ->findOne();
    }

    public function verificarPostulacionPorIdUsuario($idUsuario, $idAviso)
    {
        return is_object($this->findPostulacionPorIdUsuario($idUsuario, $idAviso));
    }

    public function savePostulacionPorUsuario($user, $idAviso, $data)
    {
        if(!$this->verificarPostulacionPorIdUsuario($user->getId(), $idAviso)){
            $postulante = $this->getPostulantePorUsuario($user, $data);
            if(is_object($postulante)){
                return $this->insertOrUpdate([
                    "IdPostulante" => $postulante->getId(),
                    "IdAviso" => $idAviso,
                    "CvMime" => $data['cvMime'],
                    "CvFilename" => $data['cvFilename'],
                    "FechaPostulacion" => date("Y-m-d H:i:s"),
                    "Estado" => JobPostulanteAviso::ESTADO_NUEVO,
                ]);
            }
        }else{
            throw new Exception("Tu postulación ya fue anteriormente registrada.");
        }
    }

    public function getCvDir()
    {
        $dir = PUBLIC_DIR . "files" . DIRECTORY_SEPARATOR . "cvs" . DIRECTORY_SEPARATOR;
        return $dir;
    }
}