<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Language" content="es-bo"/>
    <meta name="description" content="El nuevo portal de empleos en Bolivia. La mejor conexión entre trabajo y talento.">

    <title>Empleos en Bolivia en un click</title>

    <link rel="apple-touch-icon" sizes="180x180" href="<?= IMG_WEB ?>favicons/empleos.click-180x180.png">
    <link rel="icon" type="image/png" sizes="180x180" href="<?= IMG_WEB ?>favicons/empleos.click-180x180.png">

    <link href="<?=CSS_WEB;?>bootstrap.min.css" rel="stylesheet" />
    <link href="<?=FONTS_WEB;?>font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="<?=CSS_WEB;?>animate.css" rel="stylesheet">
    <link href="<?=CSS_WEB;?>style.css" rel="stylesheet" />
    <link href="<?=CSS_WEB;?>site.css" rel="stylesheet" />

    <!-- Main scripts -->
    <script src="<?=JS_WEB;?>jquery-2.1.1.js"></script>
    <script src="<?=JS_WEB;?>bootstrap.min.js"></script>
    <script src="<?=JS_WEB;?>plugins/metisMenu/jquery.metisMenu.js"></script> <!-- Main menu (applied on vertical mode) -->
    <script src="<?=JS_WEB;?>plugins/slimscroll/jquery.slimscroll.min.js"></script> <!-- Transforms any div into a scrollable area -->

    <!-- JQuery-ui -->
    <link href="<?=JS_WEB;?>plugins/jquery-ui/jquery-ui.min.css" rel="stylesheet" />
    <script src="<?=JS_WEB;?>plugins/jquery-ui/jquery-ui.min.js"></script>

    <!-- Date picker -->
    <link href="<?=CSS_WEB;?>plugins/datapicker/datepicker3.css" rel="stylesheet" />
    <script src="<?=JS_WEB;?>plugins/datapicker/bootstrap-datepicker.js"></script>
    <script src="<?=JS_WEB;?>plugins/datapicker/locales/bootstrap-datepicker.es.js" type="text/javascript" charset="UTF-8"></script>

    <!-- Custom and plugin javascript -->
    <script src="<?=JS_WEB;?>inspinia.js"></script>
    <script src="<?=JS_WEB;?>plugins/pace/pace.min.js"></script> <!-- Automatic page load progress bar -->
    <script src="<?=JS_WEB;?>plugins/wow/wow.min.js"></script>

    <!-- Gritter -  notification plugin -->
    <!--    <link href="<?=JS_WEB;?>plugins/gritter/jquery.gritter.css" rel="stylesheet">-->
    <!--    <script src="<?=JS_WEB;?>plugins/gritter/jquery.gritter.min.js"></script>-->

    <!-- Our plugins javascript -->
    <link href="<?=JQUERY_WEB;?>jquery.loadmask.css" rel="stylesheet" type="text/css" />
    <script src="<?=JQUERY_WEB;?>jquery.loadmask.js" type="text/javascript"></script>
    <script src="<?=JQUERY_WEB;?>jquery.formAjaxPost.js" type="text/javascript"></script>


    <script type="application/javascript">
    $().ready(function () {

    });
    </script>

    <?php
    if(strtoupper(Configs::value('app.run.environment')) != 'DEVELOPMENT'){
    ?>
    <script type="text/javascript">
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-106081408-1', 'auto');
        ga('send', 'pageview');
    </script>
    <?php
    }
    ?>
</head>

<body id="page-top" class="landing-page">

    <div class="navbar-wrapper">

        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header page-scroll">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
<!--                    <a class="navbar-brand" href="http://blog.empleos.click">IR AL BLOG</a>-->
<!--                    <div class="btn-group">-->
                    <div class="top-left">
                        <a class="btn btn-primary dim" target="_blank" href="http://blog.empleos.click">
                             Ir al blog
                        </a>
                        <a class="btn btn-success btn-facebook dim" target="_blank" href="https://www.facebook.com/empleos.clic">
                            <i class="fa fa-facebook"> </i> Siguenos <span class="to-hide">en Facebook</span>
                        </a>
                    </div>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a class="page-scroll" href="#page-top">Inicio</a></li>
                        <li><a class="page-scroll" href="#ventajas">Ventajas</a></li>
                    </ul>
                </div>
            </div>
        </nav>

    </div>

    <?= $__Content; ?>

</body>

</html>