<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><?=Configs::value('app.name');?></title>

    <link href="<?=CSS_WEB;?>bootstrap.min.css" rel="stylesheet" />

    <link href="<?=FONTS_WEB;?>font-awesome/css/font-awesome.min.css" rel="stylesheet" />

    <link href="<?=CSS_WEB;?>animate.css" rel="stylesheet" />
    <link href="<?=CSS_WEB;?>style.css" rel="stylesheet" />

    <link href="<?=CSS_WEB;?>site.css" rel="stylesheet" />

    <!-- Main scripts -->
    <script src="<?=JS_WEB;?>jquery-2.1.1.js"></script>
    <script src="<?=JS_WEB;?>bootstrap.min.js"></script>
    <script src="<?=JS_WEB;?>plugins/metisMenu/jquery.metisMenu.js"></script> <!-- Main menu (applied on vertical mode) -->
    <script src="<?=JS_WEB;?>plugins/slimscroll/jquery.slimscroll.min.js"></script> <!-- Transforms any div into a scrollable area -->

    <!-- JQuery-ui -->
    <link href="<?=JS_WEB;?>plugins/jquery-ui/jquery-ui.min.css" rel="stylesheet" />
    <script src="<?=JS_WEB;?>plugins/jquery-ui/jquery-ui.min.js"></script>

    <!-- Date picker -->
    <link href="<?=CSS_WEB;?>plugins/datapicker/datepicker3.css" rel="stylesheet" />
    <script src="<?=JS_WEB;?>plugins/datapicker/bootstrap-datepicker.js"></script>
    <script src="<?=JS_WEB;?>plugins/datapicker/locales/bootstrap-datepicker.es.js" type="text/javascript" charset="UTF-8"></script>

    <!-- DataTables jquery plugin -->
    <link href="<?=CSS_WEB;?>plugins/dataTables/datatables.min.css" rel="stylesheet" />
    <script src="<?=JS_WEB;?>plugins/dataTables/datatables.min.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="<?=JS_WEB;?>inspinia.js"></script>
    <script src="<?=JS_WEB;?>plugins/pace/pace.min.js"></script> <!-- Automatic page load progress bar -->

    <!-- Gritter -  notification plugin -->
<!--    <link href="<?=JS_WEB;?>plugins/gritter/jquery.gritter.css" rel="stylesheet">-->
<!--    <script src="<?=JS_WEB;?>plugins/gritter/jquery.gritter.min.js"></script>-->

    <!-- Our plugins javascript -->
    <link href="<?=JQUERY_WEB;?>jquery.loadmask.css" rel="stylesheet" type="text/css" />
    <script src="<?=JQUERY_WEB;?>jquery.loadmask.js" type="text/javascript"></script>
    <script src="<?=JQUERY_WEB;?>jquery.formAjaxPost.js" type="text/javascript"></script>

</head>

<body class="top-navigation">

    <div id="wrapper">

<!--        <nav class="navbar-default navbar-static-side" role="navigation">-->
<!--            --><?//= BarView::renderBar('sidebar'); ?>
<!--        </nav>-->

        <div id="page-wrapper" class="gray-bg">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                            <i class="fa fa-reorder"></i>
                        </button>
                        <a href="#" class="navbar-brand">Empleos.Click</a>
<!--                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>-->
<!--                        <form role="search" class="navbar-form-custom" method="post" action="#">-->
<!--                            <div class="form-group">-->
<!--                                <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">-->
<!--                            </div>-->
<!--                        </form>-->
                    </div>

                    <div class="navbar-collapse collapse" id="navbar">
                        <ul class="nav navbar-nav">
                            <li class="active">
                                <a aria-expanded="false" role="button" href="layouts.html"> Back to main Layout page</a>
                            </li>
                            <li class="dropdown">
                                <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
                                <ul role="menu" class="dropdown-menu">
                                    <li><a href="">Menu item</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
                                <ul role="menu" class="dropdown-menu">
                                    <li><a href="">Menu item</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
                                <ul role="menu" class="dropdown-menu">
                                    <li><a href="">Menu item</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Menu item <span class="caret"></span></a>
                                <ul role="menu" class="dropdown-menu">
                                    <li><a href="">Menu item</a></li>
                                    <li><a href="">Menu item</a></li>
                                </ul>
                            </li>

                        </ul>
                        <?php
                        if(UserControl::isLoggedIn()) {
                            ?>
                            <ul class="nav navbar-top-links navbar-right">
                                <li>
                                    <a href="<?=Uri::createURLTo(['uri' => 'main/system/logout']);?>">
                                        <i class="fa fa-sign-out"></i> Cerrar Sesión
                                    </a>
                                </li>
                            </ul>
                            <?php
                        }
                        ?>
                    </div>


                </nav>
            </div>

            <?= $__Content; ?>

            <div class="footer">
                <div class="pull-right">
                    10GB of <strong>250GB</strong> Free.
                </div>
                <div>
                    <strong>Derechos Reservados</strong> <?=Configs::value('app.company');?> &copy; <?=date('Y');?>
                </div>
            </div>

        </div>
    </div>

    <?= BarView::renderBar('modals'); ?>

</body>

</html>