
<div class="form-group">
    <label class="control-label col-sm-3" for="MainId">Main Id</label>
    <div class="col-sm-9">
        
        <input type="text" id="MainId" name="MainId" value=""
               class="form-control" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Code">Code</label>
    <div class="col-sm-9">
        
        <input type="text" id="Code" name="Code" value=""
               class="form-control" maxlength="30" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Status">Status</label>
    <div class="col-sm-9">
        
        <input type="text" id="Status" name="Status" value=""
               class="form-control" maxlength="30" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Name">Name</label>
    <div class="col-sm-9">
        
        <input type="text" id="Name" name="Name" value=""
               class="form-control" maxlength="200" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Type">Type</label>
    <div class="col-sm-9">
        
        <input type="text" id="Type" name="Type" value=""
               class="form-control" maxlength="30" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Level">Level</label>
    <div class="col-sm-9">
        
        <input type="text" id="Level" name="Level" value=""
               class="form-control" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Left">Left</label>
    <div class="col-sm-9">
        
        <input type="text" id="Left" name="Left" value=""
               class="form-control" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Right">Right</label>
    <div class="col-sm-9">
        
        <input type="text" id="Right" name="Right" value=""
               class="form-control" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="LastUserId">Last User Id</label>
    <div class="col-sm-9">
        
        <input type="text" id="LastUserId" name="LastUserId" value=""
               class="form-control" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="CreationDate">Creation Date</label>
    <div class="col-sm-9">
        
        <input type="text" id="CreationDate" name="CreationDate" value=""
               class="form-control" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="ModificationDate">Modification Date</label>
    <div class="col-sm-9">
        
        <input type="text" id="ModificationDate" name="ModificationDate" value=""
               class="form-control" />
        
    </div>
</div>
    