<?php
/**
 * Generated by Chocala Framework.
 *
 */
class LocationService extends GenericService
{

    /**
    * @var LocationService
    */
    protected static $instance = null;

    /**
     * @return SysLocationQuery
     */
    public function validsQuery($noDeletes=true)
    {
        return SysLocationQuery::createValids($noDeletes);
    }

    /**
     * @param $pk
     * @return array|mixed|SysLocation
     * @throws NotFoundException
     */
    public function findPk($pk)
    {
        $location = $this->validsQuery()->findPk($pk);
        if (!is_object($location)) {
            throw new NotFoundException(ChocalaErrors::INVALID_RESOURCE);
        }
        return $location;
    }

    /**
     * @param array $filters
     * @return \Propel\Runtime\Util\PropelModelPager|SysLocation[]
     */
    public function dataList($filters=[])
    {
        $query = $this->validsQuery();
        /**
         * put here your filters code
         *
        if(isset($filters['field'])){
            $query->filterByField(filters['field']);
        }
         */
        $_page = $filters['_page']?: 1;
        $_max = $filters['_max']?: $query->count();
        return $query->paginate($_page, $_max);
    }

    /**
     * @param $data
     * @param null $location
     * @return array|mixed
     * @throws \Propel\Runtime\Exception\PropelException
     */
    public function insertOrUpdate($data, &$location = null)
    {
        if(!is_object($location)){
            $location = new SysLocation();
        }
        $location->fromArray($data);
        $results['success'] = $location->validate();
        if ($results['success']) {
            $location->save();
        }
        $results['object'] = $location;
        $results['errors'] = $location->getErrorsMap();
        return $results;
    }

}