<?php
/**
 * Generated by Chocala Framework.
 * 
 */
class LocationController extends AdminWebController
{

    /**
    * @service LocationService Injected service
    * @var LocationService
    */
    protected $locationService;

    public function index()
    {
        $this->redirectTo(['action' => 'dataList']);
    }

    public function dataList()
    {
        $filters = Req::all();
        $filters['_page'] = $filters['_page']?: 1;
        $filters['_max'] = $filters['_max']?: 10;
        $locationPager = $this->locationService->dataList($filters);
        $this->set('locationPager', $locationPager);
    }

    public function show()
    {
        $location = $this->objectIfExist();
        $this->set('location', $location);
    }

    public function create()
    {
        $location = new SysLocation();
        $this->set('location', $location);
        $this->view->changeLayout('ajax');
    }

    public function save()
    {
        $results = $this->locationService->insertOrUpdate(Req::all());
        $this->set('location', $results['object']);
        $this->set('success', $results['success']);
        $this->set('errors', $results['errors']);
        $this->renderAsJSON();
    }

    public function edit()
    {
        $location = $this->objectIfExist();
        $this->set('location', $location);
        $this->view->changeLayout('ajax');
    }

    public function update()
    {
        $location = $this->objectIfExist();
        $results = $this->locationService->insertOrUpdate(Req::all(), $location);
        $this->set('location', $location);
        $this->set('success', $results['success']);
        $this->set('errors', $results['errors']);
        $this->renderAsJSON();
    }

    public function delete()
    {
        $location = $this->objectIfExist();
        try {
            $location->delete();
            $this->redirectTo(['action' => 'dataList']);
        } catch (Exception $e) {
            $this->redirectTo(['action' => 'show',
                'id' => $location->getPrimaryKey()]);
        }
    }

    public function objectIfExist()
    {
        try {
            return $this->locationService->findPk($this->id);
        } catch (ChocalaException $che) {
            HttpManager::responseAs404();
        }
    }

}