<link href="<?=CSS_WEB;?>plugins/steps/jquery.steps.css" rel="stylesheet">

<style>
    .wizard > .content > .body {
        position: relative;
    }

    .formFieldset {
        background: #eee;
        /*border-top: 10px solid #0d70b7;*/
    }

    .formFieldset .msg {
        color: #1c84c6;
        display: block;
        font-size: 95%;
        padding-bottom: 10px;
        /*border-top: 10px solid #0d70b7;*/
    }
</style>

<section class="timeline gray-section">

    <div class="container text-left">


        <div class="row">
            <h3>Hola mundo</h3>
        </div>



<div class="row">

    <div class="col-lg-12">
        <div class="ibox">
            <div class="ibox-title">
                <h5>Wizard with Validation</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#">Config option 1</a>
                        </li>
                        <li><a href="#">Config option 2</a>
                        </li>
                    </ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <h2>
                    Validation Wizard Form
                </h2>
                <p>
                    This example show how to use Steps with jQuery Validation plugin.
                </p>

                <form id="form" action="#" class="form-horizontal wizard-big wizard clearfix" role="application" novalidate="novalidate">
                    <div class="steps clearfix">
                        <ul role="tablist">
                            <li role="tab" class="first current" aria-disabled="false" aria-selected="true"><a id="form-t-0" href="#form-h-0" aria-controls="form-p-0"><span class="current-info audible">current step: </span><span class="number">1.</span> Account</a></li><li role="tab" class="disabled" aria-disabled="true"><a id="form-t-1" href="#form-h-1" aria-controls="form-p-1"><span class="number">2.</span> Profile</a></li><li role="tab" class="disabled" aria-disabled="true"><a id="form-t-2" href="#form-h-2" aria-controls="form-p-2"><span class="number">3.</span> Warning</a></li><li role="tab" class="disabled last" aria-disabled="true"><a id="form-t-3" href="#form-h-3" aria-controls="form-p-3"><span class="number">4.</span> Finish</a></li>
                        </ul>
                    </div>
                    <div class="content clearfix">
                        <h1 id="form-h-0" tabindex="-1" class="title current">Account</h1>
                        <fieldset id="form-p-0" role="tabpanel" aria-labelledby="form-h-0" class="body current" aria-hidden="false">
                            <h2>Account Information</h2>
                            <div class="row">
                                <div class="col-lg-8">


<!--                                    <div class="form-group">
                                        <label>Username *</label>
                                        <input id="userName" name="userName" class="form-control required" aria-required="true" type="text">
                                    </div>
                                    <div class="form-group">
                                        <label>Password *</label>
                                        <input id="password" name="password" class="form-control required" aria-required="true" type="text">
                                    </div>
                                    <div class="form-group">
                                        <label>Confirm Password *</label>
                                        <input id="confirm" name="confirm" class="form-control required" aria-required="true" type="text">
                                    </div>-->

                                    <div class="form-group">
                                        <label class="control-label col-xs-4 col-md-3">Email</label>
                                        <div class="col-xs-8 col-md-9">
                                            <p class="form-control-static">
                                                <span class="text-blue"><?=$empresaSuscrita->getEmail();?></span>
                                            </p>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-xs-4 col-md-3">Nombre de <?=$esEmpresaFormal? 'Empresa': 'Negocio';?></label>
                                        <div class="col-xs-8 col-md-9">
                                            <input id="Nombre" name="Nombre" value="<?=$empresaSuscrita->getNombre();?>"
                                                   maxlength="250" minlength="2"
                                                   class="form-control" placeholder="Nombre de Empresa/Negocio" />
                                        </div>
                                    </div>

                                    <?php
                                    if($esEmpresaFormal) {
                                    ?>
                                    <div class="form-group">
                                        <label class="control-label col-xs-4 col-md-3">N.I.T.</label>
                                        <div class="col-xs-8 col-md-9">
                                            <input id="Nit" name="Nit" placeholder="N.I.T."
                                                   class="form-control"/>
                                        </div>
                                    </div>
                                    <?php
                                    }
                                    ?>

                                    <div class="form-group">
                                        <label class="control-label col-xs-4 col-md-3">Ciudad</label>
                                        <div class="col-xs-8 col-md-9">
                                            <select id="EntityTypeId" name="EntityTypeId" class="form-control">
                                                <option value="">- Seleccionar -</option>
                                                <?php
                                                foreach ($locaciones as $locacion) {
                                                ?>
                                                    <option value="<?=$locacion->getId();?>"><?=$locacion->getName();?></option>
                                                <?php
                                                }
                                                ?>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-xs-4 col-md-3">Teléfono</label>
                                        <div class="col-xs-8 col-md-9">
                                            <input id="Telefono" name="Telefono"
                                                   class="form-control" placeholder="Teléfono" />
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-xs-4 col-md-3">Celular</label>
                                        <div class="col-xs-8 col-md-9">
                                            <input id="Celular" name="Celular"
                                                   class="form-control" placeholder="Celular" />
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-xs-4 col-md-3">Representante</label>
                                        <div class="col-xs-8 col-md-9">
                                            <input id="Representante" name="Representante" value="<?=$empresaSuscrita->getRepresentante();?>"
                                                   class="form-control" placeholder="Nombre de Representante" />
                                        </div>
                                    </div>

                                </div>
                                <div class="col-lg-4">
                                    <div class="text-center">
                                        <div style="margin-top: 20px">
                                            <i class="fa fa-sign-in" style="font-size: 180px;color: #e5e5e5 "></i>
                                        </div>
                                    </div>
                                </div>
                                <hr style="clear: both;" >
                            </div>
                        </fieldset>
                        <h1 id="form-h-1" tabindex="-1" class="title">Profile</h1>
                        <fieldset id="form-p-1" role="tabpanel" aria-labelledby="form-h-1" class="body" style="display: none;" aria-hidden="true">
                            <h2>Profile Information</h2>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>First name *</label>
                                        <input id="name" name="name" class="form-control required" aria-required="true" type="text">
                                    </div>
                                    <div class="form-group">
                                        <label>Last name *</label>
                                        <input id="surname" name="surname" class="form-control required" aria-required="true" type="text">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Email *</label>
                                        <input id="email" name="email" class="form-control required email" aria-required="true" type="text">
                                    </div>
                                    <div class="form-group">
                                        <label>Address *</label>
                                        <input id="address" name="address" class="form-control" type="text">
                                    </div>
                                </div>
                            </div>
                        </fieldset>

                        <h1 id="form-h-2" tabindex="-1" class="title">Warning</h1>
                        <fieldset id="form-p-2" role="tabpanel" aria-labelledby="form-h-2" class="body" style="display: none;" aria-hidden="true">
                            <div class="text-center" style="margin-top: 120px">
                                <h2>You did it Man :-)</h2>
                            </div>
                        </fieldset>

                        <h1 id="form-h-3" tabindex="-1" class="title">Finish</h1>
                        <fieldset id="form-p-3" role="tabpanel" aria-labelledby="form-h-3" class="body" style="display: none;" aria-hidden="true">
                            <h2>Terms and Conditions</h2>
                            <input id="acceptTerms" name="acceptTerms" class="required" aria-required="true" type="checkbox"> <label for="acceptTerms">I agree with the Terms and Conditions.</label>
                        </fieldset>
                    </div><div class="actions clearfix"><ul role="menu" aria-label="Pagination"><li class="disabled" aria-disabled="true"><a href="#previous" role="menuitem">Previous</a></li><li aria-hidden="false" aria-disabled="false"><a href="#next" role="menuitem">Next</a></li><li aria-hidden="false"><a href="#finish" role="menuitem">Finish</a></li><li><a href="#cancel" role="menuitem">Cancel</a></li></ul></div></form>
            </div>
        </div>
    </div>

</div>



        <div class="row">
            <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Basic form
                        <small>Simple login form example</small>
                    </h5>
                    <!--                    <div class="ibox-tools">-->
                    <!--                        <a class="collapse-link">-->
                    <!--                            <i class="fa fa-chevron-up"></i>-->
                    <!--                        </a>-->
                    <!--                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">-->
                    <!--                            <i class="fa fa-wrench"></i>-->
                    <!--                        </a>-->
                    <!--                        <ul class="dropdown-menu dropdown-user">-->
                    <!--                            <li><a href="#">Config option 1</a>-->
                    <!--                            </li>-->
                    <!--                            <li><a href="#">Config option 2</a>-->
                    <!--                            </li>-->
                    <!--                        </ul>-->
                    <!--                        <a class="close-link">-->
                    <!--                            <i class="fa fa-times"></i>-->
                    <!--                        </a>-->
                    <!--                    </div>-->
                </div>
                <div class="ibox-content">
                    <div class="row">

                        <form id="form" action="#" class="wizard-big wizard clearfix" role="application">
                            <h1>Account</h1>
                            <fieldset>
                                <h2>Account Information</h2>
                                <div class="row">
                                    <div class="col-lg-8">
                                        <div class="form-group">
                                            <label>Username *</label>
                                            <input id="userName" name="userName" type="text" class="form-control required">
                                        </div>
                                        <div class="form-group">
                                            <label>Password *</label>
                                            <input id="password" name="password" type="text" class="form-control required">
                                        </div>
                                        <div class="form-group">
                                            <label>Confirm Password *</label>
                                            <input id="confirm" name="confirm" type="text" class="form-control required">
                                        </div>
                                    </div>
                                    <div class="col-lg-4">
                                        <div class="text-center">
                                            <div style="margin-top: 20px">
                                                <i class="fa fa-sign-in" style="font-size: 180px;color: #e5e5e5 "></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </fieldset>
                            <h1>Profile</h1>
                            <fieldset>
                                <h2>Profile Information</h2>
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>First name *</label>
                                            <input id="name" name="name" type="text" class="form-control required">
                                        </div>
                                        <div class="form-group">
                                            <label>Last name *</label>
                                            <input id="surname" name="surname" type="text" class="form-control required">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label>Email *</label>
                                            <input id="email" name="email" type="text" class="form-control required email">
                                        </div>
                                        <div class="form-group">
                                            <label>Address *</label>
                                            <input id="address" name="address" type="text" class="form-control">
                                        </div>
                                    </div>
                                </div>
                            </fieldset>

                            <h1>Warning</h1>
                            <fieldset>
                                <div class="text-center" style="margin-top: 120px">
                                    <h2>You did it Man :-)</h2>
                                </div>
                            </fieldset>

                            <h1>Finish</h1>
                            <fieldset>
                                <h2>Terms and Conditions</h2>
                                <input id="acceptTerms" name="acceptTerms" type="checkbox" class="required"> <label for="acceptTerms">I agree with the Terms and Conditions.</label>
                            </fieldset>
                        </form>


                        <form role="form" class="form-horizontal">
                            <div class="col-sm-6 b-r">
                                <h3 class="m-t-none m-b">Información de la empresa</h3>
                                <!--                                <p>Sign in today for more expirience.</p>-->
                                <div class="form-group">
                                    <label class="control-label col-xs-4 col-md-3">Email</label>
                                    <div class="col-xs-8 col-md-9">
                                        <p class="form-control-static">email@example.com</p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-xs-4 col-md-3">Nombre de Empresa/Negocio</label>
                                    <div class="col-xs-8 col-md-9">
                                        <input id="Nombre" name="Nombre" placeholder="Nombre de Empresa/Negocio"
                                               class="form-control"/>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-xs-4 col-md-3">N.I.T.</label>
                                    <div class="col-xs-8 col-md-9">
                                        <input id="Nit" name="Nit" placeholder="N.I.T." class="form-control"/>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-xs-4 col-md-3">Representante</label>
                                    <div class="col-xs-8 col-md-9">
                                        <input id="Representante" name="Representante"
                                               placeholder="Nombre de Representante" class="form-control"/>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-xs-4 col-md-3">Ciudad</label>
                                    <div class="col-xs-8 col-md-9">
                                        <select id="EntityTypeId" name="EntityTypeId" class="form-control">
                                            <option value="">- Seleccionar -</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-xs-4 col-md-3">Teléfono</label>
                                    <div class="col-xs-8 col-md-9">
                                        <input id="Telefono" name="Telefono" placeholder="Teléfono"
                                               class="form-control"/>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-xs-4 col-md-3">Celular</label>
                                    <div class="col-xs-8 col-md-9">
                                        <input id="Celular" name="Celular" placeholder="Celular" class="form-control"/>
                                    </div>
                                </div>

                                <div>
                                    <button class="btn btn-sm btn-primary pull-right m-t-n-xs" type="submit"><strong>Log
                                            in</strong></button>
                                    <label> <input type="checkbox" class="i-checks"> Remember me </label>
                                </div>

                            </div>

                            <div class="col-sm-6">

                                <h3 class="m-t-none m-b">Información de usuario</h3>

                                <div class="form-group">
                                    <label class="control-label col-xs-4 col-md-3" for="firstName">Primer Nombre</label>
                                    <div class="col-sm-8">
                                        <input type="text" id="FirstName" name="FirstName"
                                               value="<?= $person ? $person->getFirstName() : ''; ?>"
                                               size="30" maxlength="30" class="form-control uppercase"
                                               placeholder="Primer nombre..." autocomplete="off"/>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-xs-4 col-md-3">Password</label>
                                    <div class="col-xs-8 col-md-9">
                                        <input type="password" placeholder="Password" class="form-control"/>
                                    </div>
                                </div>

                                <h4>Not a member?</h4>
                                <p>You can create an account:</p>
                                <p class="text-center">
                                    <a href=""><i class="fa fa-sign-in big-icon"></i></a>
                                </p>

                            </div>

                        </form>
                    </div>
                </div>
            </div>
            </div>
        </div>


        <div class="row">
            <div id="divSuscripcion" class="col-lg-4 col-md-6 col-sm-12 col-xs-12 pull-right">

                <fieldset id="form-p-0" role="tabpanel" aria-labelledby="form-h-0" class="body current formFieldset"
                          aria-hidden="false" style="padding: 2.5%;">
                    <h2>¡Anuncia Gratis!</h2>

                    <span class="msg">Suscribe a tu empresa y publica tus requerimientos de personal completamente gratis.</span>

                    <form id="formSuscripcion" action="<?= URI::toPage() . 'suscribirEmpresa'; ?>">

                        <div class="form-group">
                            <label>Nombre de su empresa</label>
                            <input id="Nombre" name="Nombre" class="form-control required" aria-required="true"
                                   type="text">
                        </div>

                        <div class="form-group">
                            <label>Email</label>
                            <input id="Email" name="Email" class="form-control required email" aria-required="true"
                                   type="text">
                        </div>

                        <div class="form-group">
                            <label>Representante</label>
                            <input id="Representante" name="Representante" class="form-control required"
                                   aria-required="true" type="text">
                        </div>

                        <div class="form-group">
                            <label>Tipo de empresa</label>
                            <select id="EntityTypeId" name="EntityTypeId" class="form-control required">
                                <option value="">- Selecciomar -</option>
                                <?php
                                foreach ($entityTypeList as $entityType) {
                                    ?>
                                    <option value="<?= $entityType->getId(); ?>"><?= $entityType->getName(); ?></option>
                                    <?php
                                }
                                ?>
                            </select>
                        </div>

                        <button type="submit" class="btn btn-info dim block full-width m-b"><i class="fa fa-check"></i>
                            <strong>Registrar Empresa</strong></button>

                    </form>

                </fieldset>

            </div>
        </div>

        <div style="clear: both;"></div>


        <div class="row">
            <div class="col-sm-3 text-justify">
                <h2><span class="text-blue">5000+</span> visitas al mes</h2>
                <p><strong>Empleos.Click</strong> ya tiene garantizado un tráfico mensual de más de 5000 personas.
                    Técnicos y profesionales,
                    que visitan nuestro portal y se constituyen en potenciales prospectos en busca de nuevas
                    oportunidades laborales.
                </p>
                <!--                <p><a class="navy-link" href="#" role="button">Details »</a></p>-->
            </div>
            <div class="col-sm-3 text-justify">
                <h2><span class="text-blue">3000+</span> fans en Facebook</h2>
                <p>Sorpresivamente hemos conseguido como portal oficial de empleos, más de 2500 fans en nuestra página
                    de facebook,
                    y tenemos semanalmente mas de 800 interacciones desde nuestra página.</p>
                <!--                <p><a class="navy-link" href="#" role="button">Details »</a></p>-->
            </div>
            <div class="col-sm-3 text-justify">
                <h2><span class="text-blue">600+</span> suscriptores</h2>
                <p>Gracias a la confianza depositada por los visitantes, nuestro sistema ya cuenta con más de 600
                    suscriptores,
                    a quienes notificamos periódicamente sobre convocatorias que detectamos pueden ser de su
                    interés.</p>
                <!--                <p><a class="navy-link" href="#" role="button">Details »</a></p>-->
            </div>
            <div class="col-sm-3 text-justify">
                <h2><span class="text-blue">Máximo</span> rendimiento</h2>
                <p>Desde el mes de septiembre de 2017, <strong>Empleos.Click</strong> se constituye en el portal de
                    referencia para la
                    conexión de empleos, en los pocos meses nuestor alto rendimiento nos consolidadó en un importante
                    mecanismo de contacto
                    entre especialistas y empresas.
                </p>
                <!--                <p><a class="navy-link" href="#" role="button">Details »</a></p>-->
            </div>
        </div>

        <section class="features">
            <div class="container">
                <!--                <div class="row">-->
                <div class="col-lg-12 text-center">
                    <div class="navy-line"></div>
                    <h1>El mejor canal gratuito para tus anuncios</h1>
                    <p>Ponemos tus anuncios al alcance de más de 5000 personas que estan en busca de empleo</p>
                </div>
                <!--                </div>-->
                <!--                <div class="row">-->
                <div class="col-lg-5 col-lg-offset-1 features-text">
                    <small>Empleos.Click</small>
                    <h2>Logra amplia difusión</h2>
                    <i class="fa fa-bullhorn big-icon pull-left"></i>
                    <p>Registra tus ofertas de empleo con tu cuenta de empresa completamente gratis,
                        asi logras amplio alcance a través de nuestros canales de difusión,
                        todo completamente en línea desde la comodidad de tu hogar u oficina.
                    </p>
                </div>
                <div class="col-lg-5 features-text">
                    <small>Empleos.Click</small>
                    <h2>Encuentra los mejores candidatos</h2>
                    <i class="fa fa-users big-icon pull-right"></i>
                    <p>Sabemos que el principal factor de desarrollo de cada empresa es el talento humano,
                        por eso, innovamos en brindar un medio efectivo para la obtención de prospectos y candidatos
                        que puedan cubrir de mejor manera los espacios de empleo requeridos.
                    </p>
                </div>
                <!--                </div>-->
            </div>

        </section>
    </div>

</section>

<br/>

<div class="row">
    <div class="col-lg-12 text-center">
        <p class="m-t-sm">
            Contáctanos y síguenos en nuestros canales sociales
        </p>
        <ul class="list-inline social-icon">
            <li><a href="https://www.twitter.com/EmpleosClick/" target="_blank"><i class="fa fa-twitter"></i></a>
            </li>
            <li><a href="https://www.facebook.com/empleos.clic/" target="_blank"><i class="fa fa-facebook"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-lg-8 col-lg-offset-2 text-center m-t-lg m-b-lg">
        <p><strong>&copy; <?= date('Y'); ?> Empleos.Click</strong><br/> Empleos en Bolivia</p>
    </div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function () {

        $("#formSuscripcion").formAjaxPost({
            'beforeSend': function (xhr) {
                $("#divSuscripcion").parent().mask("");
            },
            'onErrors': function ($form, errors) {
                $form.find('div.help-block').remove();
                $form.find('div.has-error').removeClass('has-error');
                $(errors).each(function (i, el) {
                    $form.find('#' + el.field)
                        .parents('div.form-group')
                        .first()
                        .addClass('has-error');
                    //.append('<div class="help-block">'+el.message+'</div>');
                    $form.find('#' + el.field)
                        .parent()
                        .append('<div class="help-block">' + el.message + '</div>');
                });
                $("#divSuscripcion").parent().unmask();
            },
            'onSuccess': function (data) {
                // $("#formSuscripcion").reset();
                $("#divSuscripcion").parent().unmask();
                alert("Registro completado!");
                $("#myModal .panel-body").html(
                    "<br /><div class=\"alert alert-success\">" +
                    "En breve recibirás un correo de confirmación en: <strong>" + $("#Email").val() + "</strong>" +
                    " , si no lo encuentras en tu Bandeja de Entrada por favor verifica en Spam y márcanos como correo confiable." +
                    " <br /> ¡Empleos.Click siempre a tu servicio!." +
                    "</div>" +
                    "<button type=\"button\" class=\"btn btn-sm btn-success block full-width m-b\" data-dismiss=\"modal\">Ok, revisare mi correo</button>"
                );
            }
        });

    });
</script>

<!-- Steps -->
<script src="<?=JS_WEB;?>plugins/staps/jquery.steps.min.js"></script>