<link href="<?= CSS_WEB; ?>plugins/steps/jquery.steps.css" rel="stylesheet">

<style type="text/css">
.wizard > .content > .body {
    position: relative;
}
.formFieldset {
    background: #eee;
    /*border-top: 10px solid #0d70b7;*/
}
.formFieldset .msg {
    color: #1c84c6;
    display: block;
    font-size: 95%;
    padding-bottom: 10px;
    /*border-top: 10px solid #0d70b7;*/
}

.landing-page section .tyc p {
    color: #666666;
    font-size: 11px;
    text-align: justify;
}
</style>

<section class="timeline gray-section">

    <div class="container text-left">

        <br />

        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-title">
                        <h5>Complete el Registro de su <?= $tipoSuscripcion; ?></h5>
                    </div>
                    <div class="ibox-content">
                        <h2>Registro de <?= $tipoSuscripcion; ?></h2>
                        <p>
                            <span class="text-blue">¡En unos simples pasos podrás completar la suscripción y publicar anuncios gratis!</span>
                        </p>

                        <form id="form" action="#" class="form-horizontal wizard-big">
                            <h1><?= $tipoSuscripcion; ?></h1>
                            <fieldset>
                                <h2>Datos de su <?= $tipoSuscripcion; ?></h2>
                                <div class="row">
                                    <div class="col-lg-8">

                                        <div class="form-group">
                                            <label class="control-label col-xs-4 col-md-3">Email</label>
                                            <div class="col-xs-8 col-md-9">
                                                <p class="form-control-static">
                                                    <span class="text-blue"><?= $empresaSuscrita->getEmail(); ?></span>
                                                </p>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label col-xs-4 col-md-3">Nombre de <?= $tipoSuscripcion; ?></label>
                                            <div class="col-xs-8 col-md-9">
                                                <input id="Nombre" name="Nombre"
                                                       value="<?= $empresaSuscrita->getNombre(); ?>"
                                                       maxlength="250" minlength="2"
                                                       class="form-control"
                                                       placeholder="Nombre de Empresa/Negocio"/>
                                            </div>
                                        </div>

                                        <?php
                                        if ($esEmpresaFormal) {
                                            ?>
                                            <div class="form-group">
                                                <label class="control-label col-xs-4 col-md-3">N.I.T.</label>
                                                <div class="col-xs-8 col-md-9">
                                                    <input id="Nit" name="Nit" placeholder="N.I.T."
                                                           class="form-control"/>
                                                </div>
                                            </div>
                                            <?php
                                        }
                                        ?>

                                        <div class="form-group">
                                            <label class="control-label col-xs-4 col-md-3">Departamento</label>
                                            <div class="col-xs-8 col-md-9">
                                                <select id="LocationId" name="LocationId" class="form-control">
                                                    <option value="">- Seleccionar -</option>
                                                    <?php
                                                    foreach ($locaciones as $locacion) {
                                                        ?>
                                                        <option value="<?= $locacion->getId(); ?>"><?= $locacion->getName(); ?></option>
                                                        <?php
                                                    }
                                                    ?>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label col-xs-4 col-md-3">Dirección</label>
                                            <div class="col-xs-8 col-md-9">
                                                    <textarea id="Direccion" name="Direccion" rows="2"
                                                              class="form-control" placeholder="Dirección"></textarea>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label col-xs-4 col-md-3">Teléfono</label>
                                            <div class="col-xs-8 col-md-9">
                                                <input id="Telefono" name="Telefono"
                                                       class="form-control" placeholder="Teléfono"/>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label col-xs-4 col-md-3">Celular</label>
                                            <div class="col-xs-8 col-md-9">
                                                <input id="Celular" name="Celular"
                                                       class="form-control" placeholder="Celular"/>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label col-xs-4 col-md-3">Representante</label>
                                            <div class="col-xs-8 col-md-9">
                                                <input id="Representante" name="Representante"
                                                       value="<?= $empresaSuscrita->getRepresentante(); ?>"
                                                       class="form-control" placeholder="Nombre de Representante"/>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="control-label col-xs-4 col-md-3" for="logo">Logotipo (opcional)</label>
                                            <div class="col-xs-8 col-md-9">
                                                <input type="file" id="logo" name="logo" class="" />
                                            </div>
                                        </div>

                                    </div>
                                    <div class="col-lg-4">
                                        <div class="text-center">
                                            <div style="margin-top: 20px">
                                                <i class="fa fa-sign-in" style="font-size: 180px;color: #e5e5e5 "></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <input type="hidden" name="hc" value="<?= $empresaSuscrita->getHashCode(); ?>" />

                            </fieldset>
                            <h1>Cuenta de Usuario</h1>
                            <fieldset>

                                <h2>Datos de Cuenta de Usuario</h2>

                                    <div class="col-xs-12">

                                    <div class="alert alert-info">
                                        Esta Cuenta de Usuario servirá para administrar los anuncios de su <?= $tipoSuscripcion; ?>.
                                    </div>

                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="firstName">Primer Nombre</label>
                                                <div class="col-sm-8">
                                                    <input type="text" id="FirstName" name="FirstName" value="<?=$person? $person->getFirstName(): '';?>"
                                                           size="30" maxlength="30" class="form-control uppercase"
                                                           placeholder="Primer nombre..." autocomplete="off" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="MiddleName">Segundo Nombre</label>
                                                <div class="col-sm-8">
                                                    <input type="text" id="MiddleName" name="MiddleName" value="<?=$person? $person->getMiddleName(): '';?>"
                                                           size="30" maxlength="30" class="form-control uppercase"
                                                           placeholder="Segundo nombre..." autocomplete="off" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="LastName">Primer Apellido</label>
                                                <div class="col-sm-8">
                                                    <input type="text" id="LastName" name="LastName" value="<?=$person? $person->getLastName(): '';?>"
                                                           size="30" maxlength="30" class="form-control uppercase"
                                                           placeholder="Primer apellido..." autocomplete="off" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="SecondLastName">Segundo Apellido</label>
                                                <div class="col-sm-8">
                                                    <input type="text" id="SecondLastName" name="SecondLastName" value="<?=$person? $person->getSecondLastName(): '';?>"
                                                           size="30" maxlength="100" class="form-control uppercase"
                                                           placeholder="Segundo apellido..." autocomplete="off" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="IdNumber">Carnet de Identidad</label>
                                                <div class="col-sm-8">
                                                    <input type="text" id="IdNumber" name="IdNumber" value="<?=$person? $person->getIdNumber(): '';?>"
                                                           size="30" maxlength="30" class="form-control"
                                                           placeholder="Cédula de Identidad..." autocomplete="off" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="Gender">Sexo</label>
                                                <div class="col-sm-8">
                                                    <div class="radio-listcc" id="Gender">
                                                        <label>
                                                            <input type="radio" name="Gender" value="MALE"
                                                                   class="form-control radio" <?=$person? ($person->getGender()=='MALE'? 'checked="true" ': ''): '';?>/>
                                                            Masculino
                                                        </label>
                                                        &nbsp;&nbsp;
                                                        <label>
                                                            <input type="radio" name="Gender" value="FEMALE"
                                                                   class="form-control radio" <?=$person? ($person->getGender()=='FEMALE'? 'checked="true" ': ''): '';?>/>
                                                            Femenino
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="Address">Dirección</label>
                                                <div class="col-sm-8">
                                                    <textarea id="Address" name="Address" cols="30" rows="3" class="form-control"
                                                              placeholder="Dirección..."><?=$person? $person->getAddress(): '';?></textarea>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="PhoneWork">Teléfono Fijo</label>
                                                <div class="col-sm-8">
                                                    <div class="input-group">
                                                        <div class="input-group-addon"><i class="fa fa-phone"></i></div>
                                                        <input type="text" id="PhoneWork" name="PhoneWork" value="<?=$person? $person->getPhoneWork(): '';?>"
                                                               size="30" maxlength="30" class="form-control"
                                                               placeholder="" autocomplete="off" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="Cellphone1">Celular</label>
                                                <div class="col-sm-8">
                                                    <div class="input-group">
                                                        <div class="input-group-addon"><i class="fa fa-phone"></i></div>
                                                        <input type="text" id="Cellphone1" name="Cellphone1" value="<?=$person? $person->getCellphone1(): '';?>"
                                                               size="30" maxlength="30" class="form-control"
                                                               placeholder="" autocomplete="off" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                    <h3 class="underline">Cuenta de Usuario</h3>

                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="Email">Email</label>
                                                <div class="col-sm-8">
                                                    <input type="email" id="Email" name="Email" value="<?=$user? $user->getEmail(): '';?>"
                                                           size="30" maxlength="80" class="form-control"
                                                           placeholder="Email..." autocomplete="off" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="Username">Username</label>
                                                <div class="col-sm-8">
                                                    <input type="text" id="Username" name="Username" value="<?=$user? $user->getUsername(): '';?>"
                                                           size="30" maxlength="30" class="form-control"
                                                           placeholder="Username..." autocomplete="off" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="Password">Contraseña</label>
                                                <div class="col-sm-8">
                                                    <input type="password" id="Password" name="Password" value=""
                                                           size="30" maxlength="80" class="form-control"
                                                           placeholder="Contraseña..." autocomplete="off" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="Password2">Repetir contraseña</label>
                                                <div class="col-sm-8">
                                                    <input type="password" id="Password2" name="Password2" value=""
                                                           size="30" maxlength="30" class="form-control"
                                                           placeholder="Repetir contraseña..." autocomplete="off" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <input type="hidden" name="hc" value="<?= $empresaSuscrita->getHashCode(); ?>" />

                            </fieldset>

                            <h1>Anuncio</h1>
                            <fieldset>

                                <h2>Su Requerimiento de Personal</h2>

                                <div class="col-xs-12">

                                    <div class="form-group">
                                        <label class="control-label col-sm-3" for="Cargo">Cargo</label>
                                        <div class="col-sm-9">
                                            <input type="text" id="Cargo" name="Cargo" value="<?=$aviso? $aviso->getCargo(): '';?>"
                                                   class="form-control" maxlength="100" placeholder="Cargo..." />
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-sm-3" for="Code">Teléfonos</label>
                                        <div class="col-sm-3">
                                            <input type="text" id="TelefonoContacto" name="TelefonoContacto" value="<?=$aviso? $aviso->getTelefonoContacto(): '';?>"
                                                   size="30" maxlength="30" class="form-control" placeholder="Telefonos..."
                                                   autocomplete="off" class="validate[required]" />
                                        </div>

                                        <label class="control-label col-sm-2" for="CorreoContacto">Correo Electrónico</label>
                                        <div class="col-sm-4">
                                            <input type="text" id="CorreoContacto" name="CorreoContacto" value="<?=$aviso? $aviso->getCorreoContacto(): '';?>"
                                                   size="25" maxlength="100" class="form-control" placeholder="Email..."
                                                   autocomplete="off" class="validate[required]" />
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <div class="col-sm-6">

                                            <div class="form-group">
                                                <label class="control-label col-sm-6" for="FechaVencimiento">Fecha Vencimiento</label>
                                                <div class="col-sm-6">
                                                    <div class="input-group date">
                                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                        <input type="text" id="FechaVencimiento" name="FechaVencimiento" value="<?=$aviso? $aviso->getFechaVencimiento("d/m/Y"): date('d/m/Y');?>"
                                                               class="form-control datepicker" />
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-sm-3" for="Descripcion">Formaciones</label>
                                        <div class="col-sm-9">
                                            <div id="FormacionesReferencia">
                                                <select name="FormacionReferencia[]" class="form-control formaciones">
                                                    <option value="">-Seleccionar-</option>
                                                    <?php
                                                    foreach($formacionReferenciaList as $formacionReferencia):
                                                        $check = $aviso && $aviso->tieneFormacion($formacionReferencia)? 'checked="yes"': '';
                                                        ?>
                                                        <option value="<?=$formacionReferencia->getNombre();?>"><?=$formacionReferencia->getNombre();?></option>
                                                    <?php
                                                    endforeach;
                                                    ?>
                                                </select>
                                            </div>
                                            <a href="#" class="addFormacion"><i class="fa fa-plus-square"></i> Agregar formación</a>
                                            <span>
                                                &nbsp;
                                                <a href="#" class="removeFormacion text-danger hide"><i class="fa fa-minus-square"></i> Quitar formación</a>
                                            </span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-sm-3" for="Descripcion">Descripción del Puesto</label>
                                        <div class="col-sm-9">
                                            <textarea id="Descripcion"  name="Descripcion"
                                                      class="form-control" rows="2" cols="20" placeholder="Descripción del puesto..."><?=$aviso? $aviso->getDescripcion(): '';?></textarea>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-sm-3" for="Requisito">Requisitos</label>
                                        <div class="col-sm-9">
                                            <textarea id="Requisito" name="Requisito"
                                                      class="form-control" rows="2" cols="20" placeholder="Requisitos del puesto..."><?=$aviso? $aviso->getRequisito(): '';?></textarea>
                                        </div>
                                    </div>



                                    <div class="form-group">
                                        <div class="col-sm-6">

                                            <div class="form-group">
                                                <label class="control-label col-sm-6" for="NivelFormacion">Nivel Formación</label>
                                                <div class="col-sm-6">
                                                    <select id="NivelFormacion" name="NivelFormacion"
                                                            class="form-control">
                                                        <option value="">-Seleccionar-</option>
                                                        <?php
                                                        foreach($nivelesFormacion as $nivelFormacion):
                                                            $sel = $aviso && $aviso->getNivelFormacion() == $nivelFormacion? 'selected="yes"': '';
                                                            ?>
                                                            <option value="<?=$nivelFormacion;?>" <?=$sel;?> ><?=$nivelFormacion;?></option>
                                                        <?php
                                                        endforeach;
                                                        ?>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label col-sm-6" for="AniosExperiencia">Años de Experiencia</label>
                                                <div class="col-sm-6">
                                                    <input type="number" id="AniosExperiencia" name="AniosExperiencia" value="<?=$aviso? $aviso->getAniosExperiencia(): '';?>"
                                                           class="form-control" maxlength="50" placeholder="Años experiencia..." />
                                                </div>
                                            </div>

                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label class="control-label col-sm-6" for="Localizacion">Localización</label>
                                                <div class="col-sm-6">
                                                    <div id="Localizacion" >
                                                    <?php
                                                    foreach($localizaciones as $localizacion):
                                                        $check = $aviso && $aviso->getLocalizacion()==$localizacion? 'checked="yes"': '';
                                                        ?>
                                                        <label class="block">
                                                            <input type="radio" name="Localizacion" value="<?=$localizacion;?>"
                                                                <?=$check;?> style="display: inline;" /> <?=$localizacion;?>
                                                        </label>
                                                    <?php
                                                    endforeach;
                                                    ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                </div>

                                <input type="hidden" name="hc" value="<?= $empresaSuscrita->getHashCode(); ?>" />

                            </fieldset>

                            <h1>Finalizar</h1>
                            <fieldset>

                                <h2>Términos y Condiciones</h2>
                                <div class="tyc">
                                    <?php
                                    include_once("tyc.phtml");
                                    ?>
                                    <div class="form-group">
                                        <input id="Agree" name="Agree" type="checkbox" value="YES" class="required" />
                                        <label for="Agree">Acepto los Términos y Condiciones.</label>

                                        <input type="hidden" name="hc" value="<?= $empresaSuscrita->getHashCode(); ?>" />
                                    </div>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>

        </div>

        <div style="clear: both;"></div>

    </div>

</section>

<br/>

<div class="row">
    <div class="col-lg-12 text-center">
        <p class="m-t-sm">
            Contáctanos y síguenos en nuestros canales sociales
        </p>
        <ul class="list-inline social-icon">
            <li><a href="https://www.twitter.com/EmpleosClick/" target="_blank"><i class="fa fa-twitter"></i></a>
            </li>
            <li><a href="https://www.facebook.com/empleos.clic/" target="_blank"><i class="fa fa-facebook"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-lg-8 col-lg-offset-2 text-center m-t-lg m-b-lg">
        <p><strong>&copy; <?= date('Y'); ?> Empleos.Click</strong><br/> Empleos en Bolivia</p>
    </div>
</div>

<!-- Steps -->
<script src="<?= JS_WEB; ?>plugins/staps/jquery.steps.min.js"></script>

<script type="text/javascript">
var is_async_step = false;
jQuery(document).ready(function () {

    $("#form").steps({
        labels: {
            // current: "current step:",
            // pagination: "Pagination",
            finish: "Finalizar",
            next: "Siguiente",
            previous: "Anterior",
            loading: "Cargando..."
        },
        bodyTag: "fieldset",
        onStepChanging: changeStep,
        onFinished: changeStep
    });

    function changeStep(event, currentIndex, newIndex) {
        $(".datepicker").datepicker({format: 'dd/mm/yyyy', language: 'es'});
        if (currentIndex > newIndex) {
            return true;
        }
        if (is_async_step) {
            is_async_step = false;
            //Allow next step
            return true;
        }
        var arr = $("#form_tag_id").serializeArray();
        arr.push({ name: "one_more_field", value: "one_more_value" });
/*
        $.post("", arr).done(function (data)
        {
            if(data != "ok")
            {
                return;
            }

            is_async_step = true;
            //trigger navigation event
            $("#wizard").steps("next");
        });
*/


        var $form = $("#form-p-" + currentIndex);
        var $formData = new FormData();
        $form.find('input, textarea, select').each(function(){
            var input = $(this);
            var type = input.attr('type');
            switch (type){
                case "checkbox":
                    if (input.is(":checked")) {
                        $formData.append(input.attr('name'), input.val());
                    }
                    break;
                case "radio":
                    if(input.is(":checked")) {
                        $formData.append(input.attr('name'), input.val());
                    }
                    break;
                case "file":
                    $.each(input.prop("files"),function(i,file){
                        $formData.append(input.attr("name"), file);
                    });
                    break;
                default:
                    if(!input.is(":disabled") && type != "submit" && type != "button"){
                        $formData.append(input.attr('name'), input.val());
                    }
            }
        });


        if(newIndex == null && currentIndex<3){
            return false;
        }
        var action = "<?=URI::toPage().'step';?>" + newIndex;
        if(currentIndex == 3) {
            action = "<?=URI::toPage().'finish';?>";
        }
        var fieldset = $("#form-p-" + currentIndex);

        // var success = false;
        fieldset.find('div.help-block').remove();
        fieldset.find('div.has-error').removeClass('has-error');
        $.ajax({
            url: action,
            type: "POST",
            // data: fieldset.serialize(),
            data: $formData,
            cache: false,
            contentType: false,
            processData: false,
            beforeSend: function( xhr ) {
                fieldset.parent().mask("");
            }
        }).done(function(data) {
            var result = eval(data);
            if (!result.success) {
                fieldset.find('div.help-block').remove();
                fieldset.find('div.has-error').removeClass('has-error');
                $(result.errors).each(function(i, el) {
                    fieldset.find('#' + el.field)
                        .parents('div.form-group')
                        .first()
                        .addClass('has-error');
                    fieldset.find('#' + el.field)
                        .parent()
                        .find("div.help-block")
                        .remove();
                    fieldset.find('#' + el.field)
                        .parent()
                        .append('<div class="help-block">'+el.message+'</div>');
                });
            } else {
                // alert("Si ta bueno")
                is_async_step = true;
                if(currentIndex == 3) {
                    window.location = "<?=URI::toPage().'publicada';?>"
                }
            }
        }).fail(function(jqXHR, textStatus){
            alert("ERROR: error en envío de datos");
            fieldset.parent().unmask();
        }).always(function(){
            // alert("ya no se ve")
            fieldset.parent().unmask();
            if(is_async_step) {
                //trigger navigation event
                $("#form").steps("next");
            }
        });

        //forbid the next step because $.post is an asynchronous function
        return false;
    }

    $(".addFormacion").click(function(){
        $(".formaciones").first().clone().appendTo("#FormacionesReferencia");
        verifyAddRemove();
        return false;
    });
    $(".removeFormacion").click(function(){
        $(".formaciones").last().remove();
        verifyAddRemove();
        return false;
    });
    function verifyAddRemove(){
        var selects = $(".formaciones");
        if(selects.size() > 1){
            $(".removeFormacion").removeClass("hide");
        } else {
            $(".removeFormacion").addClass("hide");
        }
        if(selects.size() < 10){
            $(".addFormacion").removeClass("hide");
        } else {
            $(".addFormacion").addClass("hide");
        }
    }

});
</script>