<p><strong>INFORMACIÓN RELEVANTE</strong></p>
<p>Es requisito necesario para el uso de los servicios que se ofrecen en este sitio, que
    lea y acepte los siguientes Términos y Condiciones que a continuación se redactan.
    El uso de nuestros servicios implicará que usted ha leído y aceptado los Términos y
    Condiciones de Uso en el presente documento. Para hacer uso del servicio, será
    necesario el registro por parte del usuario, con ingreso de datos personales
    fidedignos y definición de una contraseña.</p>
<p>El usuario puede elegir y cambiar la clave para su acceso de administración de la
    cuenta en cualquier momento, en caso de que se haya registrado y durante el uso de
    nuestros servicios www.empleos.click no asume la responsabilidad en caso de que
    entregue dicha clave a terceros.</p>
<p>Todas las publicaciones y transacciones que se lleven a cabo por medio de este sitio
    web, están sujetas a un proceso de confirmación y verificación, el cual podría
    incluir la verificación telefónica o de visita, validación de información
    proporcionada, validación de la factura (en caso de existir) y el cumplimiento de
    las condiciones requeridas por el medio de pago seleccionado. En algunos casos puede
    que se requiera una verificación por medio de correo electrónico.</p>
<p><strong>LICENCIA</strong></p>
<p>Empleos.Click a través de su sitio web concede una licencia para que los
    usuarios utilicen los servicios y productos que son promovidos en este sitio web de acuerdo
    a los Términos y Condiciones que se describen en este documento.</p>
<!--<p><strong>USO NO AUTORIZADO</strong></p>
<p>En caso de que aplique (para venta de software, templetes, u otro producto de diseño
    y programación) usted no puede colocar uno de nuestros productos, modificado o sin
    modificar, en un CD, sitio web o ningún otro medio y ofrecerlos para la
    redistribución o la reventa de ningún tipo.</p>
<p><strong>PROPIEDAD</strong></p>
<p>Usted no puede declarar propiedad intelectual o exclusiva dentro de nuestros servicios,
    incluidos casos modificando o sin modificar completa o parcielmante.
    La información generada mediante este portal son de copropiedad con
    los proveedores del contenido en caso de ser anunciantes.
    En caso de que no se especifique lo contrario, nuestros productos se proporcionan
    sin ningún tipo de garantía, expresa o implícita. En ningún caso esta compañía será
    responsables de ningún daño incluyendo, pero no limitado a, daños directos,
    indirectos, especiales, fortuitos o consecuentes u otras pérdidas resultantes del
    uso o de la imposibilidad de utilizar nuestros servicios y productos.</p>
<p><strong>POLÍTICA DE REEMBOLSO Y GARANTÍA</strong></p>
<p>En el caso de servicios de pago, no realizamos reembolsos después del periodo de revisión
    o prueba del servicio, usted tiene la responsabilidad de entender antes de comprarlo.
    Le pedimos que lea
    cuidadosamente antes de comprarlo. Hacemos solamente excepciones con esta regla
    cuando la descripción no se ajusta al servicio o producto. Hay algunos productos y
    servicios que pudieran tener garantía y posibilidad de reembolso pero este será
    especificado al adquirir los mismos. En tales casos la garantía solo cubrirá fallas
    y dentro de las especificaciones detalladas y sólo se hará efectiva cuando el
    producto o servicio se haya usado correctamente. La garantía no cubre
    fallas o daños ocasionados por uso indebido. Los términos de la garantía están
    asociados a fallas de fabricación y funcionamiento en condiciones normales de los
    productos y servicios, y sólo se harán efectivos estos demostrando haber sido usado
    correctamente. Esto incluye:</p>
<p>– De acuerdo a las especificaciones técnicas indicadas para cada producto.<br>– En
    condiciones ambientales acorde con las especificaciones indicadas.<br>–
    En uso específico para la función con que fue diseñado.<br>– En
    condiciones de operación acorde con las especificaciones y tolerancias
    indicadas.</p>-->
<p><strong>COMPROBACIÓN ANTIFRAUDE</strong></p>
<p>La compra del cliente puede ser aplazada para la comprobación antifraude. También
    puede ser suspendida por más tiempo para una investigación más rigurosa, para evitar
    transacciones fraudulentas.</p>
<p><strong>PRIVACIDAD</strong></p>
<p>Este <a href="https://www.empleos.click/" target="_blank">sitio web</a>
    www.empleos.click garantiza que la información personal que usted envía cuenta con
    la seguridad necesaria. Los datos ingresados por usuario o en el caso de requerir
    una validación de los pedidos no serán entregados a terceros, salvo que deba ser
    revelada en cumplimiento a una orden judicial o requerimientos legales.</p>
<p>La suscripción a boletines de correos electrónicos publicitarios es voluntaria y
    podría ser seleccionada al momento de crear su cuenta.</p>
<p>Empleos.Click se reserva los derechos de cambiar o de modificar estos términos sin
    previo aviso.</p>
