<?php
/**
 * Generated by Chocala Framework.
 * 
 */
class AuthService extends GenericService
{
    const TYPE_FACEBOOK = 'FACEBOOK';
    /**
    * @var AuthService
    */
    protected static $instance = null;

    public function createQuery()
    {
        return SysAuthQuery::create();
    }

    /**
     * @return AuthService
     */
    public static function instance()
    {
        return parent::instance(); // TODO: Change the autogenerated stub
    }

    public function findPk($pk)
    {
        $auth = $this->createQuery()->findPk($pk);
        if (!is_object($auth)) {
            throw new ChocalaException(ChocalaErrors::INVALID_RESOURCE);
        }
        return $auth;
    }

    public function insertOrUpdate($data, &$auth = null)
    {
        if(!is_object($auth)){
            $auth = new SysAuth();
        }
        $auth->fromArray($data);
        $auth->save();
        $results['object'] = $auth;
        $results['errors'] = $auth->getErrorsMap();
        return $results;
    }



    /**
     * @param $oFacebookUser
     * @return array|mixed|SysUser
     * @throws \Propel\Runtime\Exception\PropelException
     */
    public function saveUserFromFacebook($oFacebookUser)
    {
        if (is_object($oFacebookUser) && ($accessToken = $oFacebookUser->getId()) != ""
            && ($email = $oFacebookUser->getEmail()) != "") {
            $oAuth = SysAuthQuery::create()
                ->filterByType(AuthService::TYPE_FACEBOOK)
                ->filterByAccessToken($accessToken)
                ->filterByStatus(SysUser::STATUS_CLOSED, Criteria::NOT_EQUAL)
                ->findOne();
            if (!is_object($oAuth)) {
                $oUserAlreadyRegistered = SysUserQuery::create()
                    ->filterByUsername($oFacebookUser->getEmail())
                    ->filterByStatus(SysUser::STATUS_CLOSED, Criteria::NOT_EQUAL)
                    ->findOne();
                $aResult = UserService::instance()->insertOrUpdate([
                    "FirstName" => $oFacebookUser->getName(),
                    "LastName" => $oFacebookUser->getLastName() != ""? $oFacebookUser->getLastName() : "FBUser",
                    "Email" => $oFacebookUser->getEmail(),
                    "Username" => $oFacebookUser->getEmail(),
                    "Password" => "FBUser",
                    "RolId" => 3,
                ], $oUserAlreadyRegistered);
                if(is_object($aResult["object"])){
                    $this->insertOrUpdate([
                        "UserId" => $aResult["object"]->getId(),
                        "Type" => AuthService::TYPE_FACEBOOK,
                        "AccessToken" => $accessToken,
                        "Json" => $oFacebookUser->asJson(),
                    ]);
                    return $aResult["object"];
                }
            }else{
                return $oAuth->getSysUser();
            }

        }
        return null;
    }

    public function verifyEquals($data)
    {
        $result = SysUserQuery::create()
            ->filterByStatus(SysUser::STATUS_CLOSED, Criteria::NOT_EQUAL);
        if(isset($data['pk']) && $data['pk'] != ""){
            $result = $result->filterByPrimaryKey($data['pk']);
        }
        if($data['field'] == 'Username'){
            $result = $result->filterByUsername($data['value']);
        }
        return is_object($result->findOne());
    }

}