<?php
Chocala::import("Model.utils.FacebookApi");
/**
 * Generated by Chocala Framework.
 * 
 */
class AuthController extends PublicWebController
{

    /**
    * @service AuthService Injected service
    * @var AuthService
    */
    protected $authService;

    /**
     * @service admin.user.UserService Injected service
     * @var UserService
     */
    protected $userService;

    public function signin()
    {
        $message = "";
        try{
            if(UserControl::login(Req::_('username'), Req::_('password'))){
                $status = "OK";
            }else{
                throw new Exception("Usuario o password incorrecto.");
            }
        }catch (Exception $e){
            $status = "ERROR";
            $message = $e->getMessage();
        }
        $this->set("status", $status);
        $this->set("message", $message);
        $this->renderAsJSON();
    }

    public function remember()
    {
        try{
            $user = $this->userService->findOneByEmail(Req::_('username'));
            if(is_object($user)){
                if($this->userService->sendResetPassword($user)){
                    $status = "OK";
                    $message = "Se envió correctamente el correo de restauración de acceso.";
                }else{
                    throw new Exception("No se pudo enviar la contraseña, intenta otra vez.");
                }
            }else{
                throw new Exception("Usuario incorrecto.");
            }
        }catch (Exception $e){
            $status = "ERROR";
            $message = $e->getMessage();
        }
        $this->set("status", $status);
        $this->set("message", $message);
        $this->renderAsJSON();
    }

    public function loadPanel()
    {
        if (Req::_("panel") == "register") {
            $this->renderViewWithoutLayout('main.auth.registerPanel');
        } elseif (Req::_("panel") == "remember") {
            $this->renderViewWithoutLayout('main.auth.rememberPanel');
        } else{
            $this->renderViewWithoutLayout('main.auth.loginPanel');
        }
    }

    public function options()
    {
        if (UserControl::isLoggedIn()) {
            $this->renderViewWithoutLayout('main.auth.privateOptions');
        }else{
            $this->renderViewWithoutLayout('main.auth.publicOptions');
        }
    }

    public function signOut()
    {
        UserControl::logout();
        FacebookApi::instance()->logout();
        $this->redirectTo(['uri' => '']);
    }

    public function register()
    {
        $status = "OK";
        $message = "";
        try {
            if (Req::_('username') && Req::_('pass')) {
                if(!$this->authService->verifyEquals(['field'=>'Username', 'value' => Req::_('username')])) {
                    $aResult = $this->userService->insertOrUpdate([
                        "FirstName" => Req::_('name'),
                        "LastName" => Req::_('lastName'),
                        "Email" => Req::_('username'),
                        "Username" => Req::_('username'),
                        "Password" => Req::_('pass'),
                        "RolId" => 3,
                    ]);
                    if(is_object($aResult['object'])){
                        $aResult['object']->setStatus(SysUser::STATUS_ACTIVE)->save();
                        UserControl::login(Req::_('username'), Req::_('pass'));
                    }
                } else {
                    throw new Exception("El email ya ha sido utilizado.");
                }
            } else {
                throw new Exception("Por favor, Llena los campos obligatorios.");
            }
        }catch (Exception $e){
            $status = "ERROR";
            $message = $e->getMessage();
        }
        $this->set("status", $status);
        $this->set("message", $message);
        $this->renderAsJSON();
    }

    public function signinFacebook()
    {
        $status = "OK";
        $statusFacebook = "";
        $message = "";
        $imageUrl = "";
        try {
            if (FacebookApi::instance()->isLoggedIn()) {
                if (!is_object($this->sessionUser)) {
                    $oUser = $this->authService->saveUserFromFacebook(FacebookApi::instance()->getUser());
                    if (is_object($oUser)) {
                        $imageUrlFacebook = FacebookApi::instance()->getPictureUrl();
                        $email = $oUser->getUsername();
                        if($oUser->getImageMime()){
                            $imageUrl = $oUser->imageWeb(SysUser::IMG_THUMBNAIL);
                        }else{
                            $imageUrl = $imageUrlFacebook;
                        }
                        UserControl::saveIntoSession($oUser);
                    } else {
                        $statusFacebook = "FACEBOOK_EMAIL_REQUIRED";
                        FacebookApi::instance()->logout();
                        throw new Exception("Facebook: Necesitamos acceso a tu email.");
                    }
                }
            } else {
                throw new Exception("Facebook: Ingresa a facebook.");
            }
        }catch (Exception $e){
            $status = "ERROR";
            $message = $e->getMessage();
        }
        $this->set("status", $status);
        $this->set("statusFacebook", $statusFacebook);
        $this->set("message", $message);
        $this->set("email", $email);
        $this->set("imageUrl", $imageUrl);
        $this->renderAsJSON();
    }

    public function verifyEquals()
    {
        if (Req::_("fieldId")) {
            Req::set('field', Req::_("fieldId"));
            Req::set('value', Req::_("fieldValue"));
        }
        echo json_encode([
            Req::_("fieldId"),
            !$this->authService->verifyEquals(Req::all()),
            false
        ]);
        exit;
    }

}