<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h4 class="modal-title text-center"><?=("Iniciar sesión");?></h4>
</div>
<form class="form-vertical form-login" name="loginForm" id="loginForm" method="post">
    <div class="modal-body no-padding-bottom">
        <div class="form-group">
            <input type="text" class="form-control validate[required,custom[email]]" name="username" autocomplete="off"
                   placeholder="Correo Electrónico: "/>
        </div>
        <div class="form-group">
            <input type="password" class="form-control validate[required]" name="password" autocomplete="off" placeholder="Contraseña: "/>
        </div>
        <div class="form-group text-center no-margin-bottom">
            <input type="submit" name="Submit" value="<?= ("Ingresar"); ?>"
                   class="btn btn-warning full-width" cho-sign-in-btn>
        </div>
    </div>
</form>
<div class="modal-body no-padding-top no-padding-bottom">
    <div class="form-group text-center">
        <button class="btn btn-success btn-facebook full-width" cho-facebook-sign-in-btn>
            <i class="fa fa-facebook-f"></i> <?= ("Ingresar con facebook"); ?>
        </button>
    </div>
    <div class="form-group text-center">
        <a cho-remember-panel-btn><?=("Olvidé mi contraseña")?></a>
    </div>
</div>
<div class="modal-body">
    <div class="form-group text-center">
        <label><?=("Aún no tienes una cuenta?")?></label>
        <button class="btn btn-transparent full-width" cho-register-panel-btn>
            <?= ("Registrarme"); ?>
        </button>
    </div>
</div>