<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h4 class="modal-title text-center"><?=("Registrarme");?></h4>
</div>
<form class="form-vertical form-login" name="loginForm" id="loginForm" method="post" onsubmit="return false">
    <div class="modal-body no-padding-bottom">
        <div class="form-group">
            <input type="text" class="form-control validate[required]" name="name" autocomplete="off" placeholder="Nombre(s): "/>
        </div>
        <div class="form-group">
            <input type="text" class="form-control validate[required]" name="lastName" autocomplete="off" placeholder="Apellido(s): "/>
        </div>
        <div class="form-group">
            <input type="email" class="form-control validate[required,custom[email], ajax[ajaxUsername]]"
                   name="username" id="Username" autocomplete="off" placeholder="Correo Electrónico: "/>
        </div>
        <div class="form-group">
            <input type="password" class="form-control validate[required]" name="pass" autocomplete="off"
                   placeholder="Contraseña: "/>
        </div>
        <div class="form-group text-center no-margin-bottom">
            <input type="submit" name="Submit" value="<?= ("Registrarme"); ?>"
                   class="btn btn-warning full-width" cho-register-btn>
        </div>
    </div>
</form>
<div class="modal-body no-padding-top no-padding-bottom">
    <div class="form-group text-center">
        <button class="btn btn-success btn-facebook full-width" cho-facebook-sign-in-btn>
            <i class="fa fa-facebook-f"></i> <?= ("Registrarme con facebook"); ?>
        </button>
    </div>
</div>
<div class="modal-body">
    <div class="form-group text-center">
        <label><?=("Tienes una cuenta?")?></label>
        <button class="btn btn-transparent full-width" cho-login-panel-btn>
            <?= ("Iniciar sesión"); ?>
        </button>
    </div>
</div>