<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Alcance de Publicación</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<?=URI::createURLTo(['uri' => 'cliente/']);?>">Empresa Suscrita</a>
            </li>
            <li>
                <a href="<?=URI::createURLTo(['uri' => 'cliente/avisos/']);?>">Anuncios</a>
            </li>
            <li class="active">
                <strong>Alcance de Publicación</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

    <?= BarView::renderBar('messages'); ?>

    <div class="row">

    </div>

</div>
