<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Mi Empresa</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<?=URI::toModule();?>">Empresa Suscrita</a>
            </li>
            <li>
                <a href="<?=URI::toPage();?>">Anuncios</a>
            </li>
            <li class="active">
                <strong>Mi Empresa</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

    <?= BarView::renderBar('messages'); ?>

    <div class="landing-page">

        <?php if (file_exists($empresaSuscrita->imageDir())) { ?>
            <img src="<?= $empresaSuscrita->imageWeb(); ?>" alt="LOGO EMPRESA">
        <?php } ?>

    </div>

</div>
