<?php

use Chocala\System\Flash;

if(Flash::message()){
    ?>
    <div class="alert alert-info">
        <?=Flash::message();?>
    </div>
    <?php
}
if(Flash::success()){
    ?>
    <div class="alert alert-success">
        <?=Flash::success();?>
    </div>
    <?php
}
if(Flash::info()){
    ?>
    <div class="alert alert-info">
        <?=Flash::info();?>
    </div>
    <?php
}
if(Flash::warning()){
    ?>
    <div class="alert alert-warning">
        <?=Flash::warning();?>
    </div>
    <?php
}
if(Flash::error()){
    ?>
    <div class="alert alert-danger">
        <?=Flash::error();?>
    </div>
    <?php
}
?>