<!-- BEGIN AJAX MODAL CONTAINERS -->
<div class="modal fade in" id="ajax-modal" role="dialog" aria-labelledby="ajax-modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>

<div class="modal fade bs-modal-sm in" id="ajax-modal-sm" role="dialog" aria-labelledby="ajax-modal-sm" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content"></div>
    </div>
</div>

<div class="modal fade bs-modal-lg in" id="ajax-modal-lg" role="dialog" aria-labelledby="ajax-modal-lg" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content"></div>
    </div>
</div>

<div class="modal fade in" id="ajax-modal-static" role="dialog" aria-labelledby="ajax-modal-static" aria-hidden="false" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>

<div id="modalLoadingContent" class="hidden">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        &nbsp;
    </div>
    <div class="modal-body text-center">
        <br />
        <img src="<?=IMG_WEB;?>assets/loading-spinner-grey.gif" alt="" class="loading" />
        <span>&nbsp;&nbsp;<?=__('Loading...');?></span>
        <br /><br />
    </div>
</div>
<!-- END AJAX MODAL CONTAINERS -->
<!-- BEGIN MODALS JAVASCRIPTS -->
<script>
jQuery(document).ready(function() {
    var _modalLoadingContent = $("#modalLoadingContent").html();
    $("#ajax-modal, #ajax-modal-sm, #ajax-modal-lg, #ajax-modal-static").on("hidden.bs.modal", function(e){
        $(this).removeData("bs.modal").find(".modal-content").empty().html(_modalLoadingContent);
    });
    $("#ajax-modal, #ajax-modal-sm, #ajax-modal-lg, #ajax-modal-static").
        removeData("bs.modal").find(".modal-content").empty().html(_modalLoadingContent);
});
</script>