<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Oficios</h2>
        <ol class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>
                <a>Oficios</a>
            </li>
            <li class="active">
                <strong>Listado General</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

    <?= BarView::renderBar('messages'); ?>

    <div class="row">
        <div class="col-lg-12">

            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Lista de Oficios</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">Opción 1</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">

                    <div class="btn-group">
                        <a href="<?= URI::toPage().'create'; ?>" class="btn btn-sm btn-primary btn-rounded" data-toggle="modal" data-target="#ajax-modal">
                            <span class="fa fa-plus-square"></span> Agregar Oficio</a>
                    </div>

                    <div class="table-responsive">

                        <table class="table table-striped table-bordered table-hover dataTables" >
                            <thead>
                                <tr>
                                    <th width="5%">Nº</th>

                                    <th>Nombre</th>

                                    <th>Descripción</th>

                                    <th>Verificado</th>

                                    <th width="15%">Acciones</th>

                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $linkToDetails = URI::toPage().'show/';
                                $linkToEdit = URI::toPage().'edit/';
                                $linkToDelete = URI::toPage().'delete/';
                                $i = 0;
                                foreach($jobOficioPager as $jobOficio):
                                    $pk = $jobOficio->getId();

                                ?>
                                <tr role="row">
                                    <td><?= $jobOficioPager->getFirstIndex() + $i; ?></td>

                                    <td><?= $jobOficio->getNombre(); ?></td>

                                    <td><?= $jobOficio->getDescripcion(); ?></td>

                                    <td><?= $jobOficio->getVerificado(); ?></td>

                                    <td class="text-center">
                                        <a href="<?= $linkToDetails.$pk; ?>" class="btn btn-sm btn-success btn-circle"><i class="fa fa-eye"></i></a>

                                        <a href="<?= $linkToEdit.$pk; ?>" class="btn btn-sm btn-warning btn-circle"><i class="fa fa-edit"></i></a>

                                        <a href="<?= $linkToDelete.$pk; ?>" class="btn btn-sm btn-danger btn-circle"><i class="fa fa-times"></i></a>
                                    </td>
                                </tr>
                                <?php
                                    $i++;
                                endforeach;
                                ?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td class="paginateButtons" colspan="7">
                                        <?php if($jobOficioPager->haveToPaginate()): ?>
                                            <p>Page <?= $jobOficioPager->getPage(); ?> of <?= $jobOficioPager->getLastPage(); ?> </p>
                                            <p>Displaying results <?= $jobOficioPager->getFirstIndex(); ?> to <?= $jobOficioPager->getLastIndex(); ?>
                                                on a total of <?= $jobOficioPager->getNbResults(); ?> </p>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>

                    </div>

                </div>

            </div>

        </div>
    </div>
</div>

<script>
$(document).ready(function(){
    $('.dataTables').DataTable({
        "language": {
            "emptyTable": "No se encontraron registros"
        },
        dom: '<"html5buttons"B>lTfgitp',
        buttons: [
            {extend: 'copy', title: 'Copiar'},
            {extend: 'csv', title: 'Reporte CSV'},
            {extend: 'excel', title: 'Reporte Excel'},
            {extend: 'pdf', title: 'Reporte PDF'},
            {extend: 'print',
                customize: function (win){
                    $(win.document.body).addClass('white-bg');
                    $(win.document.body).css('font-size', '10px');
                    $(win.document.body).find('table')
                        .addClass('compact')
                        .css('font-size', 'inherit');
                }
            }
        ]
    });
});
</script>