<?= BarView::renderBar('messages'); ?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title"><i class="fa fa-plus-square-o"></i> <?=$jobOficio->isNew()? Configs::value('dialog.create.title'): Configs::value('dialog.edit.title');?> Oficio</h4>
</div>

<form action="<?= URI::toPage() . ($jobOficio->isNew()? 'save': 'update'.$jobOficio->getId()); ?>" method="post" role="form" class="ajaxPost form-horizontal">
    <div class="modal-body">

        <strong>Hola, soy el edit</strong>
        <?php include('form.phtml'); ?>

    </div>
    <div class="modal-footer clearfix">
        <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Aceptar</button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Cancelar</button>
    </div>
</form>

<script type="text/javascript">
    $().ready(function(){
        $('.ajaxPost').formAjaxPost();
    });
</script>