<?php
/**
 * Generated by Chocala Framework.
 *
 * @method JobOficioQuery validsQuery()
 */
class OficioService extends JobService
{

    /**
    * @var OficioService
    */
    protected static $instance = null;

    protected static $class = 'JobOficio';

    public function data()
    {
        $areas = static::filterValid(JobAreaQuery::data())->find();
        return $areas;
    }

    public function findPk($pk)
    {
        $object = $this->validsQuery()->findPk($pk);
        if (!is_object($object)) {
            throw new ChocalaException(ChocalaErrors::INVALID_RESOURCE);
        }
        return $object;
    }

    /**
     * @param array $filters
     * @return JobOficio[]|\Propel\Runtime\Util\PropelModelPager
     */
    public function dataList($filters=[])
    {
        $query = $this->validsQuery()
            ->_if(isset($filters['nombre']))
                ->filterByNombre($filters['nombre'], Criteria::ILIKE)
            ->_endif()
            ->_if(isset($filters['verificado']))
                ->filterByNombre($filters['verificado'], Criteria::ILIKE)
            ->_endif()
        ;
        /**
         * put here your filters code
         *
        if(isset($filters['field'])){
            $query->filterByField(filters['field']);
        }
         */
        $_page = $filters['_page']?: 1;
        $_max = $filters['_max']?: $query->count();
        return $query->paginate($_page, $_max);
    }

    /**
     * @param array $data
     * @param JobOficio|null $object
     * @return mixed
     * @throws \Propel\Runtime\Exception\PropelException
     */
    public function insertOrUpdate($data, &$object = null)
    {
        if(!is_object($object)){
            $object = new JobOficio();
        }
        $object->fromArray($data);
        $results['success'] = $object->validate();
        if ($results['success']) {
            $object->save();
        }
        $results['object'] = $object;
        $results['errors'] = $object->getErrorsMap();
        return $results;
    }

}