<?php
/**
 * Generated by Chocala Framework.
 * 
 */
class OficioController extends AdminWebController
{

    /**
    * @service OficioService
    * @var OficioService
    */
    protected $oficioService;

    public function index()
    {
        $this->redirectTo(['action' => 'dataList']);
    }

    public function dataList()
    {
        $filters = Req::all();
        $filters['_page'] = $filters['_page']?: 1;
        $filters['_max'] = $filters['_max']?: 10;
        $jobOficioPager = $this->oficioService->dataList($filters);
        $this->set('jobOficioPager', $jobOficioPager);
    }

    public function show()
    {
        $jobOficio = $this->oficioService->findPk($this->id);
        $this->set('jobOficio', $jobOficio);
    }

    public function create()
    {
        $jobOficio = new JobOficio();
        $this->set('jobOficio', $jobOficio);
        $this->view->changeLayout('ajax');
//        $this->renderView('oficio/edit', 'params');
    }

    public function save()
    {
        $results = $this->oficioService->insertOrUpdate(Req::all());
        $jobOficio = $results['object'];
        $this->set('jobOficio', $jobOficio);
        $this->set('success', $results['success']);
        if (!$results['success']) {
            $this->set('errors', $results['errors']);
        }
        $this->renderAsJSON();
    }

    public function edit()
    {
        $jobOficio = $this->oficioService->findPk($this->id);
        $this->set('jobOficio', $jobOficio);
        $this->view->changeLayout('ajax');
    }

    public function update()
    {
        $jobOficio = $this->oficioService->findPk($this->id);
        $results = $this->oficioService->insertOrUpdate(Req::all(), $jobOficio);
        $this->set('jobOficio', $jobOficio);
        $this->set('success', $results['success']);
        if (!$results['success']) {
            $this->set('errors', $results['errors']);
        }
        $this->renderAsJSON();
    }

    public function delete()
    {
        $jobOficio = $this->oficioService->findPk($this->id);
        try {
            $jobOficio->delete();
            $this->redirectTo(['action' => 'dataList']);
        } catch (Exception $e) {
            $this->redirectTo(['action' => 'show',
                'id' => $jobOficio->getPrimaryKey()]);
        }
    }

}