<?= BarView::renderBar('messages'); ?>
<div class="dialog" style="padding: 0 250px">

    <div class="btn-group">
        <a href="<?= URI::toPage().'dataList'; ?>" class="linkGoBack">Go to data list</a>
        <a href="<?= URI::toPage().'edit/'.$jobOficio->getPrimaryKey(); ?>" class="linkEdit">Edit JobOficio</a>
        <a href="<?= URI::toPage().'delete/'.$jobOficio->getPrimaryKey(); ?>" class="linkDelete" onclick="return confirm('¿Do you sure to delete this record?');">Delete JobOficio</a>
    </div>
    <h1>Oficio Details</h1>
    <hr />
    
        
    <div class="input">
        <label class="name">Nombre</label>
        <div class="value">
            <?= $jobOficio->getNombre(); ?>
        </div>
    </div>
            
    <div class="input">
        <label class="name">Descripcion</label>
        <div class="value">
            <?= $jobOficio->getDescripcion(); ?>
        </div>
    </div>
            
    <div class="input">
        <label class="name">Verificado</label>
        <div class="value">
            <?= $jobOficio->getVerificado(); ?>
        </div>
    </div>
            
    <div class="input">
        <label class="name">Status</label>
        <div class="value">
            <?= $jobOficio->getStatus(); ?>
        </div>
    </div>
            
    <div class="input">
        <label class="name">Last User Id</label>
        <div class="value">
            <?= $jobOficio->getLastUserId(); ?>
        </div>
    </div>
            
    <div class="input">
        <label class="name">Creation Date</label>
        <div class="value">
            <?= $jobOficio->getCreationDate(); ?>
        </div>
    </div>
            
    <div class="input">
        <label class="name">Modification Date</label>
        <div class="value">
            <?= $jobOficio->getModificationDate(); ?>
        </div>
    </div>
            
</div>