<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Correos Electrónicos</h2>
        <ol class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>
                <a href="<?= URI::toPage() ?>">Correos Electrónicos</a>
            </li>
            <li>
                <a href="<?= URI::toPage().'show/'.$email->getId() ?>">Correo Electrónico</a>
            </li>
            <li class="active">
                <strong>Edición de Correo Electrónico</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

    <?= BarView::renderBar('messages'); ?>

    <div class="row">

        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <div class="btn-group pull-right">
                        <?php if(PageControl::canUpdate()){ ?>
                            <a href="<?= URI::toPage().'show/'.$email->getId(); ?>" class="btn btn-sm btn-info btn-rounded">
                                <i class="fa fa-arrow-circle-left"></i> Regresar</a>
                        <?php } ?>
                    </div>
                    <h5>Correo Electrónico</h5>
                    <br />&nbsp;
                </div>
                <div class="ibox-content">
                    <div class="row">

                        <div class="form-group">
                            <label class="col-lg-12 control-label">Código</label>
                            <div class="col-lg-12">
                                <p class="form-control-static"><?=$email->getCode();?></p>
                                <br />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-12 control-label">Nombre</label>
                            <div class="col-lg-12">
                                <p class="form-control-static"><?=$email->getName();?></p>
                                <br />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-12 control-label">Asunto</label>
                            <div class="col-lg-12">
                                <p class="form-control-static"><?=$email->getSubject();?></p>
                                <br />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-12 control-label">Descripción</label>
                            <div class="col-lg-12">
                                <p class="form-control-static"><?=$email->getDescription();?></p>
                                <br />
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>

        <div class="col-lg-8 animated fadeInRight">
            <div class="mail-box-header">
                <h2>Correo: <?=$email->getName();?></h2>
            </div>
            <div class="mail-box">
                <form action="<?=URI::toPage();?>updateMail" method="post" role="form" class="ajaxPost form-horizontal" onsubmit="return postForm()">
                    <input type="hidden" id="id" name="id" value="<?=$email->getId();?>" />

                    <div class="mail-body">

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Asunto:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="Subject" max="200" value="<?=$email->getSubject();?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">From Name:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="FromName" max="100" value="<?=$email->getFromName();?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">From:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="FromEmail" max="100" value="<?=$email->getFromEmail();?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Cc:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="Cc" max="2000" value="<?=$email->getCc();?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Bcc:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="Bcc" max="500" value="<?=$email->getBcc();?>">
                            </div>
                        </div>

                    </div>

                    <div class="mail-text h-200">
                        <textarea id="Body" name="Body"><?=$email->getBody();?></textarea>

                        <div class="clearfix"></div>
                    </div>

                    <div class="mail-body text-right tooltip-demo">
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-check"></i> Aceptar</button>
                        <button type="button" class="btn btn-sm btn-default" data-dismiss="modal" onclick="window.location='<?=URI::toPage().'show/'.$email->getId();?>'"><i class="fa fa-times"></i> Cancelar</button>
                    </div>

                </form>

            </div>

        </div>

    </div>
</div>

<!-- Summernote jquery plugin -->
<link href="<?=WEB_ROOT;?>css/plugins/summernote/summernote.css" rel="stylesheet" />
<link href="<?=WEB_ROOT;?>css/plugins/summernote/summernote-bs3.css" rel="stylesheet" />
<script src="<?=WEB_ROOT;?>js/plugins/summernote/summernote.min.js"></script>

<script type="text/javascript">
$().ready(function(){
//    $('.ajaxPost').formAjaxPost();
    $('#Body').summernote({
//        onKeyup: function(e) {
//            var elem = $(this);
//            alert(elem.code());
//            $("#Body").val(elem.code());
//        }
    });
});
</script>