<?php
/**
 * Generated by Chocala Framework.
 *
 * @method static EmailService instance()
 */
class EmailService extends GenericService
{

    /**
    * @var EmailService
    */
    protected static $instance = null;

    /**
     * @param bool|true $noDeletes
     * @return SysEmailQuery
     */
    public function validsQuery($noDeletes=true)
    {
        return SysEmailQuery::createValids($noDeletes);
    }

    /**
     * @param $pk
     * @return array|mixed|SysEmail
     * @throws NotFoundException
     */
    public function findPk($pk)
    {
        $email = $this->validsQuery()->findPk($pk);
        if (!is_object($email)) {
            throw new NotFoundException(ChocalaErrors::INVALID_RESOURCE);
        }
        return $email;
    }

    /**
     * @param $code
     * @return SysEmail
     * @throws NotFoundException
     */
    public function findByCode($code)
    {
        $email = $this->validsQuery()->findOneByCode($code);
        if (!is_object($email)) {
            throw new NotFoundException(ChocalaErrors::INVALID_RESOURCE);
        }
        return $email;
    }

    /**
     * @param array $filters
     * @return \Propel\Runtime\Util\PropelModelPager|SysEmail[]
     */
    public function dataList($filters=[])
    {
        $query = $this->validsQuery()
            ->_if(isset($filters['code']))
                ->filterByCode('%'.$filters['code'].'%', Criteria::ILIKE)
            ->_endif()
            ->orderByCode()
        ;
        $_page = $filters['_page']?: 1;
        $_max = $filters['_max']?: $query->count();
        return $query->paginate($_page, $_max);
    }

    /**
     * @param $data
     * @param SysEmail|null $email
     * @return array|mixed
     * @throws \Propel\Runtime\Exception\PropelException
     */
    public function insertOrUpdate($data, SysEmail &$email = null)
    {
        if(!is_object($email)){
            $email = new SysEmail();
            $email->setFromName(Config::_('email.info.fromName'));
            $email->setFromEmail(Config::_('email.info.address'));
            $email->setBody($data['Description']);
        }
        $email->fromArray($data);
        $results['success'] = $email->validate();
        if ($results['success']) {
            $email->save();
        }
        $results['object'] = $email;
        $results['errors'] = $email->getErrorsMap();
        return $results;
    }

    /**
     * @return array
     */
    public function emailTemplates()
    {
        $templates = [];
        if(is_dir(EMAILS_DIR)){
            if($dh = opendir(EMAILS_DIR)){
                while(($file = readdir($dh)) !== false){
                    if(!is_dir(EMAILS_DIR . $file) && $file!='.' && $file!='..'){
                        array_push($templates, str_replace(Chocala::TEMPLATE_EXTENSION, "", $file));
                    }
                }
                closedir($dh);
            }
        }
        return $templates;
    }

}