<?php
/**
 * Generated by Chocala Framework.
 * 
 */
class EmailController extends AdminWebController
{

    /**
    * @service EmailService Injected service
    * @var EmailService
    */
    protected $emailService;

    public function index()
    {
        $this->redirectTo(['action' => 'dataList']);
    }

    public function dataList()
    {
        $filters = Req::all();
        $filters['_page'] = $filters['_page']?: 1;
        $filters['_max'] = $filters['_max']?: 10;
        $emailPager = $this->emailService->dataList($filters);
        $this->set('emailPager', $emailPager);
    }

    public function show()
    {
        $email = $this->objectIfExist();
        $this->set('email', $email);
    }

    public function create()
    {
        if(PageControl::canCreate()){
            $email = new SysEmail();
            $this->set('email', $email);
            $this->set('templates', $this->emailService->emailTemplates());
        }
        $this->view->changeLayout('ajax');
    }

    public function save()
    {
        if(PageControl::canCreate()){
            $results = $this->emailService->insertOrUpdate(Req::all());
            $this->set('email', $results['object']);
            $this->set('success', $results['success']);
            $this->set('errors', $results['errors']);
        }
        $this->renderAsJSON();
    }

    public function edit()
    {
        if(PageControl::canUpdate()){
            $email = $this->objectIfExist();
            $this->set('email', $email);
            $this->set('templates', $this->emailService->emailTemplates());
        }
        $this->view->changeLayout('ajax');
    }

    public function update()
    {
        if(PageControl::canUpdate()){
            $email = $this->objectIfExist();
            $results = $this->emailService->insertOrUpdate(Req::all(), $email);
            $this->set('email', $email);
            $this->set('success', $results['success']);
            $this->set('errors', $results['errors']);
        }
        $this->renderAsJSON();
    }

    public function editMail()
    {
        if(PageControl::canUpdate()){
            $email = $this->objectIfExist();
            $this->set('email', $email);
        }
    }

    public function updateMail()
    {
        $email = $this->objectIfExist();;
        if(PageControl::canUpdate()){
            $results = $this->emailService->insertOrUpdate(Req::all(), $email);
            $this->set('email', $email);
            $this->set('success', $results['success']);
            $this->set('errors', $results['errors']);
        }
        $this->redirectTo(['url' => URI::toPage().'show/'.$email->getId()]);
    }

    public function delete()
    {
        $email = $this->objectIfExist();
        try {
            $email->delete();
            $this->redirectTo(['action' => 'dataList']);
        } catch (Exception $e) {
            $this->redirectTo(['action' => 'show',
                'id' => $email->getPrimaryKey()]);
        }
    }

    public function objectIfExist()
    {
        try {
            return $this->emailService->findPk($this->id);
        } catch (ChocalaException $che) {
            HttpManager::responseAs404();
        }
    }

}