
<div class="form-group">
    <label class="control-label col-sm-3" for="MainId">Main Id</label>
    <div class="col-sm-9">
        
        <input type="text" id="MainId" name="MainId" value="<?=$location? $location->getMainId(): '';?>" placeholder="MainId..."
               class="form-control" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Code">Code</label>
    <div class="col-sm-9">
        
        <input type="text" id="Code" name="Code" value="<?=$location? $location->getCode(): '';?>" placeholder="Code..."
               class="form-control" maxlength="30" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Status">Status</label>
    <div class="col-sm-9">
        
        <input type="text" id="Status" name="Status" value="<?=$location? $location->getStatus(): '';?>" placeholder="Status..."
               class="form-control" maxlength="30" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Name">Name</label>
    <div class="col-sm-9">
        
        <input type="text" id="Name" name="Name" value="<?=$location? $location->getName(): '';?>" placeholder="Name..."
               class="form-control" maxlength="200" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Type">Type</label>
    <div class="col-sm-9">
        
        <input type="text" id="Type" name="Type" value="<?=$location? $location->getType(): '';?>" placeholder="Type..."
               class="form-control" maxlength="30" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Level">Level</label>
    <div class="col-sm-9">
        
        <input type="text" id="Level" name="Level" value="<?=$location? $location->getLevel(): '';?>" placeholder="Level..."
               class="form-control" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Lft">Lft</label>
    <div class="col-sm-9">
        
        <input type="text" id="Lft" name="Lft" value="<?=$location? $location->getLft(): '';?>" placeholder="Lft..."
               class="form-control" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Rgt">Rgt</label>
    <div class="col-sm-9">
        
        <input type="text" id="Rgt" name="Rgt" value="<?=$location? $location->getRgt(): '';?>" placeholder="Rgt..."
               class="form-control" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="LastUserId">Last User Id</label>
    <div class="col-sm-9">
        
        <input type="text" id="LastUserId" name="LastUserId" value="<?=$location? $location->getLastUserId(): '';?>" placeholder="LastUserId..."
               class="form-control" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="CreationDate">Creation Date</label>
    <div class="col-sm-9">
        
        <input type="text" id="CreationDate" name="CreationDate" value="<?=$location? $location->getCreationDate(): '';?>" placeholder="CreationDate..."
               class="form-control" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="ModificationDate">Modification Date</label>
    <div class="col-sm-9">
        
        <input type="text" id="ModificationDate" name="ModificationDate" value="<?=$location? $location->getModificationDate(): '';?>" placeholder="ModificationDate..."
               class="form-control" />
        
    </div>
</div>
    
<script type="text/javascript">
    $().ready(function(){
        $('.ajaxPost').formAjaxPost();
    });
</script>