<?php
/**
 * Generated by Chocala Framework.
 * 
 */
class LocationService extends GenericService
{

    /**
    * @var LocationService
    */
    protected static $instance = null;

    public function createQuery()
    {
        return SysLocationQuery::create();
    }

    public function findPk($pk)
    {
        $location = $this->createQuery()->findPk($pk);
        if (!is_object($location)) {
            throw new ChocalaException(ChocalaErrors::INVALID_RESOURCE);
        }
        return $location;
    }

    public function dataList($filters=[])
    {
        $query = $this->createQuery();
        /**
         * put here your filters code
         *
        if(isset($filters['field'])){
            $query->filterByField(filters['field']);
        }
         */
        $_page = $filters['_page']?: 1;
        $_max = $filters['_max']?: $query->count();
        return $query->paginate($_page, $_max);
    }

    public function insertOrUpdate($data, &$location = null)
    {
        if(!is_object($location)){
            $location = new SysLocation();
        }
        $location->fromArray($data);
        $results['success'] = $location->validate();
        if ($results['success']) {
            $location->save();
        }
        $results['object'] = $location;
        $results['errors'] = $location->getErrorsMap();
        return $results;
    }

}