<?php
/**
 * Generated by Chocala Framework.
 * 
 */
class EmailSentService extends GenericService
{

    /**
    * @var EmailSentService
    */
    protected static $instance = null;

    /**
     * @param bool|true $noDeletes
     * @return SysEmailSentQuery
     */
    public function validsQuery($noDeletes=true)
    {
        return SysEmailSentQuery::createValids($noDeletes);
    }

    /**
     * @param $pk
     * @return array|mixed|SysEmailSent
     * @throws ChocalaException
     */
    public function findPk($pk)
    {
        $emailSent = $this->validsQuery()->findPk($pk);
        if (!is_object($emailSent)) {
            throw new ChocalaException(ChocalaErrors::INVALID_RESOURCE);
        }
        return $emailSent;
    }

    /**
     * @param $hashString
     * @return SysEmailSent
     * @throws ChocalaException
     */
    public function findByHashString($hashString)
    {
        $emailSent = $this->validsQuery()->findOneByHashString($hashString);
        if (!is_object($emailSent)) {
            throw new ChocalaException(ChocalaErrors::INVALID_RESOURCE);
        }
        return $emailSent;
    }

    /**
     * @param array $filters
     * @return \Propel\Runtime\Util\PropelModelPager|SysEmailSent[]
     */
    public function dataList($filters=[])
    {
        $query = $this->validsQuery()
            ->_if(isset($filters['emailId']))
                ->filterByEmailId($filters['emailId'])
            ->_endif()
            ->_if(isset($filters['userId']))
                ->filterByUserId($filters['userId'])
            ->_endif()
        ;
        $_page = $filters['_page']?: 1;
        $_max = $filters['_max']?: $query->count();
        return $query->paginate($_page, $_max);
    }

    /**
     * THIS METHOD IS NOT USED
     *
     * @param $data
     * @param SysEmailSent|null $emailSent
     * @return mixed
     * @throws \Propel\Runtime\Exception\PropelException
     */
    public function insertOrUpdate($data, SysEmailSent &$emailSent = null)
    {
        if(!is_object($emailSent)){
            $emailSent = new SysEmailSent();
        }
        $emailSent->fromArray($data);
        $results['success'] = $emailSent->validate();
        if ($results['success']) {
            $emailSent->save();
        }
        $results['object'] = $emailSent;
        $results['errors'] = $emailSent->getErrorsMap();
        return $results;
    }

    /**
     * @param $hashString
     * @return bool
     * @throws ChocalaException
     * @throws \Propel\Runtime\Exception\PropelException
     */
    public function hashTracking($hashString)
    {
        $emailSent = $this->findByHashString($hashString);
        if(is_object($emailSent)){
            if(!$emailSent->getOpeningDate()){
                $emailSent->setOpeningDate(new DateTime());
                $emailSent->save();
                return true;
            }
        }
        return false;
    }

}