<?php
/**
 * Generated by Chocala Framework.
 * 
 */
class EmailSentController extends AdminWebController
{

    /**
    * @service EmailSentService Injected service
    * @var EmailSentService
    */
    protected $emailSentService;

    /**
     * @service system.email.EmailService Injected service
     * @var EmailService
     */
    protected $emailService;

    public function index()
    {
        $this->redirectTo(['action' => 'dataList']);
    }

    public function dataList()
    {
        $filters = Req::all();
        $filters['_page'] = $filters['_page']?: 1;
        $filters['_max'] = $filters['_max']?: 10;
        $emailSentPager = $this->emailSentService->dataList($filters);
        $this->set('emailSentPager', $emailSentPager);
    }

    public function email()
    {
        $email = $this->emailService->findPk($this->id);
        $filters = Req::all();
        $filters['_page'] = $filters['_page']?: 1;
        $filters['_max'] = $filters['_max']?: 10;
        $filters['emailId'] = $email->getId();
        $emailSentPager = $this->emailSentService->dataList($filters);
        $this->set('emailSentPager', $emailSentPager);
        $this->renderView('system.emailSent.dataList');
    }

    public function show()
    {
        $emailSent = $this->objectIfExist();
        $this->set('emailSent', $emailSent);
    }

    public function create()
    {
        $emailSent = new SysEmailSent();
        $sysEmailList = SysEmailQuery::create()
                ->orderBy()->find();
        $this->set('sysEmailList', $sysEmailList);
        $sysUserList = SysUserQuery::create()
                ->orderBy()->find();
        $this->set('sysUserList', $sysUserList);
        $this->set('emailSent', $emailSent);
        $this->view->changeLayout('ajax');
    }

    public function save()
    {
        $results = $this->emailSentService->insertOrUpdate(Req::all());
        $this->set('emailSent', $results['object']);
        $this->set('success', $results['success']);
        $this->set('errors', $results['errors']);
        $this->renderAsJSON();
    }

    public function edit()
    {
        $emailSent = $this->objectIfExist();
    $sysEmailList = SysEmailQuery::create()
                ->orderBy()->find();
        $this->set('sysEmailList', $sysEmailList);
    $sysUserList = SysUserQuery::create()
                ->orderBy()->find();
        $this->set('sysUserList', $sysUserList);
        $this->set('emailSent', $emailSent);
        $this->view->changeLayout('ajax');
    }

    public function update()
    {
        $emailSent = $this->objectIfExist();
        $results = $this->emailSentService->insertOrUpdate(Req::all(), $emailSent);
        $this->set('emailSent', $emailSent);
        $this->set('success', $results['success']);
        $this->set('errors', $results['errors']);
        $this->renderAsJSON();
    }

    public function delete()
    {
        $emailSent = $this->objectIfExist();
        try {
            $emailSent->delete();
            $this->redirectTo(['action' => 'dataList']);
        } catch (Exception $e) {
            $this->redirectTo(['action' => 'show',
                'id' => $emailSent->getPrimaryKey()]);
        }
    }

    public function objectIfExist()
    {
        try {
            return $this->emailSentService->findPk($this->id);
        } catch (ChocalaException $che) {
            HttpManager::responseAs404();
        }
    }

}