<?= BarView::renderBar('messages'); ?>
<div class="dialog" style="padding: 0 250px">

    <div class="fRight">
        <a href="<?= URI::toPage().'dataList'; ?>" class="linkGoBack">Go to data list</a>
        <a href="<?= URI::toPage().'edit/'.$emailSent->getPrimaryKey(); ?>" class="linkEdit">Edit EmailSent</a>
        <a href="<?= URI::toPage().'delete/'.$emailSent->getPrimaryKey(); ?>" class="linkDelete" onclick="return confirm('¿Do you sure to delete this record?');">Delete EmailSent</a>
    </div>
    <h1>EmailSent Details</h1>
    <hr />
    
        
    <div class="input">
        <label class="name">SysEmail</label>
        <div class="value">
            <a href="<?= WEB_ROOT.'sysEmail/show/'.$emailSent->getSysEmail()->getID(); ?>"><?= $emailSent->getSysEmail()->get(); ?></a>
        </div>
    </div>
            
    <div class="input">
        <label class="name">SysUser</label>
        <div class="value">
            <a href="<?= WEB_ROOT.'sysUser/show/'.$emailSent->getSysUser()->getID(); ?>"><?= $emailSent->getSysUser()->get(); ?></a>
        </div>
    </div>
            
    <div class="input">
        <label class="name">Sender Id</label>
        <div class="value">
            <?= $emailSent->getSenderId(); ?>
        </div>
    </div>
            
    <div class="input">
        <label class="name">Hash String</label>
        <div class="value">
            <?= $emailSent->getHashString(); ?>
        </div>
    </div>
            
    <div class="input">
        <label class="name">From Name</label>
        <div class="value">
            <?= $emailSent->getFromName(); ?>
        </div>
    </div>
            
    <div class="input">
        <label class="name">From Email</label>
        <div class="value">
            <?= $emailSent->getFromEmail(); ?>
        </div>
    </div>
            
    <div class="input">
        <label class="name">To Email</label>
        <div class="value">
            <?= $emailSent->getToEmail(); ?>
        </div>
    </div>
            
    <div class="input">
        <label class="name">Cc</label>
        <div class="value">
            <?= $emailSent->getCc(); ?>
        </div>
    </div>
            
    <div class="input">
        <label class="name">Bcc</label>
        <div class="value">
            <?= $emailSent->getBcc(); ?>
        </div>
    </div>
            
    <div class="input">
        <label class="name">Subject</label>
        <div class="value">
            <?= $emailSent->getSubject(); ?>
        </div>
    </div>
            
    <div class="input">
        <label class="name">Content</label>
        <div class="value">
            <?= $emailSent->getContent(); ?>
        </div>
    </div>
            
    <div class="input">
        <label class="name">Is Success</label>
        <div class="value">
            <?= $emailSent->getIsSuccess(); ?>
        </div>
    </div>
            
    <div class="input">
        <label class="name">Shipping Date</label>
        <div class="value">
            <?= $emailSent->getShippingDate(); ?>
        </div>
    </div>
            
    <div class="input">
        <label class="name">Opening Date</label>
        <div class="value">
            <?= $emailSent->getOpeningDate(); ?>
        </div>
    </div>
            
</div>