<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Roles de Usuario</h2>
        <ol class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>
                <a>Roles de Usuario</a>
            </li>
            <li class="active">
                <strong>Listado General</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

    <?= BarView::renderBar('messages'); ?>

    <div class="row">

<!--        <div class="col-lg-12 col-sm-12 ">-->

            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Lista de Roles de Usuario</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">Opción 1</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">

                    <div class="btn-group">
                        <?php if(PageControl::canCreate()){ ?>
                        <a href="<?= URI::toPage().'create'; ?>" class="btn btn-sm btn-primary btn-rounded" data-toggle="modal" data-target="#ajax-modal">
                            <span class="fa fa-plus-square"></span> Agregar Rol de Usuario</a>
                        <?php } ?>
                    </div>

                    <div class="table-responsive">

                        <table class="table table-striped table-bordered table-hover dataTables" >
                            <thead>
                                <tr>
                                    <th width="5%">Nº</th>
                                    <th>Nombre</th>
                                    <th>Código</th>
                                    <th>Descripción</th>
                                    <th width="15%">Acciones</th>
                                </tr>
                            </thead>

                            <tbody>
                            <?php
                            $i = 0;
                            $toEditLink = URI::toPage().'edit/';
                            $toDeleteLink = URI::toPage().'delete/';
                            foreach($rolPager as $rol){
                                $i++;
                                $pk = $rol->getId();
                                ?>
                                <tr class="<?=($i%2==0)? 'odd': 'even';?>">
                                    <td class="text-center"><?= $i; ?></td>
                                    <td class="text-left"><?= $rol->getName(); ?></td>
                                    <td class="text-left"><?= $rol->getCode(); ?></td>
                                    <td class="text-left"><?= $rol->getDescription(); ?></td>
                                    <td class="text-center">
                                    <?php
                                    if(PageControl::canUpdate()){
                                    ?>
                                        <a href="<?=$toEditLink.$pk;?>" class="btn btn-warning btn-circle" data-toggle="modal" data-target="#ajax-modal"><i class="fa fa-edit"></i></a>
                                    <?php
                                    }
                                    if(PageControl::canDelete()){
                                    ?>
                                        <a href="<?=$toDeleteLink.$pk;?>" class="btn btn-danger btn-circle"><i class="fa fa-times"></i></a>
                                    <?php
                                    }
                                    ?>
                                    </td>
                                </tr>
                            <?php
                            }
                            ?>
                            </tbody>

                        </table>

                    </div>
                </div>
            </div>

<!--        </div>-->

    </div>
</div>

<!-- page script -->
<script type="text/javascript">
$().ready(function(){
    $('.dataTables').DataTable({
        "language": {
            "emptyTable": "No se encontraron registros"
        },
        dom: '<"html5buttons"B>lTfgitp',
        buttons: [
            {extend: 'copy', title: 'Copiar'},
            {extend: 'csv', title: 'Reporte CSV'},
            {extend: 'excel', title: 'Reporte Excel'},
            {extend: 'pdf', title: 'Reporte PDF'},
            {extend: 'print',
                customize: function (win){
                    $(win.document.body).addClass('white-bg');
                    $(win.document.body).css('font-size', '10px');
                    $(win.document.body).find('table')
                        .addClass('compact')
                        .css('font-size', 'inherit');
                }
            }
        ]
    });
});
</script>