<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title"><i class="fa fa-edit"></i> Eliminar Rol de Usuario</h4>
</div>
<form action="" method="post" role="form" class="ajaxPost">
    <input type="hidden" id="action" name="action" value="delete" />
    <input type="hidden" id="id" name="id" value="<?=$rol->getId();?>" />

    <div class="modal-body">
        ¿Esta seguro que desea eliminar este registro?
    </div>
    <div class="modal-footer clearfix">
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Cancelar</button>
        <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Aceptar</button>
    </div>
</form>

<script type="text/javascript">
$().ready(function(){
    $('.ajaxPost').formAjaxPost();
});
</script>