<form action="<?=URI::toPage();?>enviarAmigo" method="post" role="form" class="ajaxPost form-horizontal">

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                    class="sr-only">Cerrar</span></button>
        <h1 class="modal-title text-success">Enviar Oferta laboral</h1>
    </div>
    <div id="diselo-fields" class="modal-body">

        <input type="hidden" id="id" name="id" value="<?=$aviso->getId();?>" />


        <div class="form-group">
            <label class="control-label col-sm-3">Oferta laboral</label>
            <div class="col-sm-9">
                <strong><?=$aviso->getCargo();?></strong>
                <br />
                <span class="text-success"><?=$aviso->getNombreEmpresa();?></span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="remitente">Remitente</label>
            <div class="col-sm-9">

                <input type="text" id="remitente" name="remitente" value="" placeholder="Tu nombre..."
                       class="form-control" maxlength="30" />

            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="nombre">Tu amigo</label>
            <div class="col-sm-9">

                <input type="text" id="nombre" name="nombre" value="" placeholder="Nombre de tu amigo..."
                       class="form-control" maxlength="30" />

            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="email">Email</label>
            <div class="col-sm-9">

                <input type="text" id="email" name="email" value="" placeholder="Email de tu amigo..."
                       class="form-control" maxlength="100" />

            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3"></label>
            <div class="col-sm-9 captcha">
                <img src="<?= $captchaUrl; ?>" id="imageCaptcha" width="200"/>
                <span class="input-group-addon" id="refreshCaptcha"><i class="fa fa-refresh"></i></span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3">Captcha</label>
            <div class="col-sm-9">
                <input style="width: 80px" type="text" id="captcha" name="captcha" value="" placeholder=""
                       class="form-control" maxlength="4" />
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <?php
        if (HttpManager::isAJAXRequest()) {
            ?>
            <button type="submit" class="btn btn-primary">Enviar oferta</button>

            <button type="button" class="btn btn-success" data-dismiss="modal">Cerrar</button>
            <?php
        }
        ?>
    </div>

</form>

<?php
if (strtoupper(Configs::value('app.run.environment')) != 'DEVELOPMENT') {
    ?>
    <script type="text/javascript">
        $().ready(function () {
            ga("send", "pageview", "<?=URI::toId() . SpecialStrings::text2Url($aviso->getCargo());?>");
        });
    </script>
    <?php
}
?>
<script type="text/javascript">
$().ready(function () {
    function refreshCaptcha() {
        $.get("<?=WEB_ROOT?>bolsa/trabajo/changeCaptcha",function(response){
            $("#imageCaptcha").attr('src', response.captchaImageUrl);
        });
    }
    $("#refreshCaptcha").click(refreshCaptcha);
    $(".ajaxPost").formAjaxPost({
        'beforeSend': function(xhr){
            $("#diselo-fields").parent().mask("");
            $("#formSuscripcion").find('div.help-block').remove();
            $("#formSuscripcion").find('div.has-error').removeClass('has-error');
        },
        'onErrors': function ($form, errors) {
            $form.find('div.help-block').remove();
            $form.find('div.has-error').removeClass('has-error');
            $(errors).each(function(i, el) {
                $form.find('#' + el.field)
                    .parents('div.form-group')
                    .first()
                    .addClass('has-error');
                //.append('<div class="help-block">'+el.message+'</div>');
                $form.find('#' + el.field)
                    .parent()
                    .append('<div class="help-block">'+el.message+'</div>');
                if(el.field == 'captcha'){
                    refreshCaptcha();
                }
            });
            $("#diselo-fields").parent().unmask();
        },
        'onSuccess': function (data) {
            // $("#formSuscripcion").reset();
            var message = "<br />" +
                "<div class=\"alert alert-success\">" +
                "Hemos enviado un correo a <strong>" + $("#email").val() + "</strong>" +
                " invitando a conocer la oferta laboral a <strong>" + $("#nombre").val() + "</strong>" +
                " <br /> ¡Empleos.Click te conecta con las mejores oportunidades laborales!." +
                "</div>"
            ;
            $("#diselo-fields").parent().unmask();
            // $("#myModal .panel-body").html(
            $("#diselo-fields").parent().html(
                message  +
                "<button type=\"button\" class=\"btn btn-sm btn-success block full-width m-b\" data-dismiss=\"modal\">Ok, entendido</button>"
            );
            // $("#myModal").modal('show');
        }
    });
});
</script>

