<div class="gray-section" itemscope itemtype="http://schema.org/JobPosting">
    <meta itemprop="specialCommitments" content="<?=$aviso->getAreasReferencia()!=''? $aviso->getAreasReferencia(): "Trabajo en ".$aviso->getLocalizacion();?>" />

    <div class="container">

        <h1 class="text-success" itemprop="title"><?=$aviso->getCargo();?></h1>

        <div class="col-md-3">
                <div class="form-group" itemprop="hiringOrganization" itemscope itemtype="http://schema.org/Organization">
                    <label class="control-label">Empresa</label>
                    <div itemprop="name">
                        <?=$aviso->getNombreEmpresa();?>
                    </div>
                </div>

                <?php
                if($aviso->getDescripcion() != '') {
                ?>
                <div class="form-group" itemprop="description">
                    <label class="control-label">Descripción</label>
                    <div class="">
                        <?= nl2br($aviso->getDescripcion()); ?>
                    </div>
                </div>
                <?php
                }
                ?>

                <div class="form-group" itemprop="skills">
                    <label class="control-label ">Requisitos</label>
                    <div class="">
                        <?=nl2br($aviso->getRequisito());?>
                    </div>
                </div>

                <?php
                if($aviso->getCompetencias() != '') {
                    ?>
                    <div class="form-group" itemprop="jobSkills" itemscope itemtype="http://schema.org/Skills">
                        <label class="control-label">Competencias</label>
                        <div class=""><?=$aviso->getCompetencias();?></div>
                    </div>
                    <?php
                }
                ?>


                <?php
                if($aviso->getDireccion() != '') {
                    ?>
                    <div class="form-group" itemprop="jobLocation" itemscope itemtype="http://schema.org/Place">
                        <label class="control-label">Dirección</label>
                        <div itemprop="address"><?=$aviso->getDireccion();?></div>
                    </div>
                    <?php
                }
                ?>

                <?php
                if($aviso->getTelefonoContacto() != '') {
                    ?>
                    <div class="form-group" itemscope itemtype="http://schema.org/Organization">
                        <label class="control-label">Teléfono</label>
                        <div itemprop="telephone"><?=$aviso->getTelefonoContacto();?></div>
                    </div>
                    <?php
                }
                ?>

                <?php
                if($aviso->getCorreoContacto() != '') {
                    ?>
                    <div class="form-group" itemscope itemtype="http://schema.org/Organization">
                        <label class="control-label ">Email</label>
                        <div itemprop="email"><?=$aviso->getCorreoContacto();?></div>
                    </div>
                    <?php
                }
                ?>

                <?php
                if($aviso->getAniosExperiencia() != '') {
                    ?>
                    <div class="form-group">
                        <label class="control-label ">Años de Experiencia</label>
                        <div itemprop="experienceRequirements"><?=$aviso->getAniosExperiencia();?></div>
                    </div>
                    <?php
                }
                ?>
                <?php
                if($aviso->getNivelFormacion() != '') {
                    ?>
                    <div class="form-group">
                        <label class="control-label">Formación</label>
                        <div itemprop="educationRequirements"><?=$aviso->getNivelFormacion();?></div>
                    </div>
                    <?php
                }
                ?>
                <div class="form-group" itemprop="jobLocation" itemscope itemtype="http://schema.org/Place">
                    <label class="control-label ">Ciudad</label>
                    <div itemprop="addressLocality"><?=$aviso->getLocalizacion();?></div>
                </div>

                <div class="form-group">
                    <label class="control-label">Fecha de Publicación</label>
                    <div itemprop="datePosted"><?=$aviso->getFechaPublicacion("d/m/Y");?></div>
                </div>

                <div class="form-group">
                    <label class="control-label">Fecha de Vencimiento</label>
                    <div itemprop="endDate"><?=$aviso->getFechaVencimiento("d/m/Y");?></div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <label class="control-label ">Fuente</label>
                        <div class=""><?=$aviso->getFuente();?></div>
                    </div>
                </div>

        </div>
        <div class="col-md-8">
            <?php
            if(file_exists(PUBLIC_DIR.'files/avisos/'.$aviso->getId().'.jpg')){
            ?>
                <img itemprop="photo" src="<?=WEB_ROOT.'files/avisos/'.$aviso->getId().'.jpg';?>" alt="Requerimiento para <?=$aviso->getCargo();?>" class="col-sm-12" style="max-width: 100%;">
            <?php
            } else {
            ?>
                <img itemprop="photo" src="<?=WEB_ROOT.'files/avisos/'.$aviso->getId().'.png';?>" alt="Requerimiento para <?=$aviso->getCargo();?>" class="col-sm-12" style="max-width: 100%;">
            <?php
            }
            ?>
        </div>
    </div>
</div>
