<style>
.formFieldset{
    background: #eee;
    /*border-top: 10px solid #0d70b7;*/
}
.formFieldset .msg{
    color: #1c84c6;
    display: block;
    font-size: 95%;
    padding-bottom: 10px;
    /*border-top: 10px solid #0d70b7;*/
}
</style>

<section class="timeline gray-section">

    <div class="container text-left" style="background: url(http://localhost/empleos.click/App/public/img/banner-empresa.jpg) no-repeat !important;">
        <div class="row">
            <div id="divSuscripcion" class="col-lg-4 col-md-6 col-sm-12 col-xs-12 pull-right">

                <fieldset id="form-p-0" role="tabpanel" aria-labelledby="form-h-0" class="body current formFieldset" aria-hidden="false" style="padding: 2.5%;">
                    <h2>¡Anuncia Gratis!</h2>

                    <span class="msg">Suscribe a tu empresa y publica tus requerimientos de personal completamente gratis.</span>

                    <form id="formSuscripcion" action="<?=URI::toPage().'suscribir';?>">

                        <div class="form-group">
                            <label>Nombre de su empresa</label>
                            <input id="nombre" name="nombre" class="form-control required" aria-required="true" type="text">
                        </div>

                        <div class="form-group">
                            <label>Email</label>
                            <input id="email" name="email" class="form-control required email" aria-required="true" type="text">
                        </div>

                        <div class="form-group">
                            <label>Representante</label>
                            <input id="entityTypeId" name="entityTypeId" class="form-control required" aria-required="true" type="text">
                        </div>

                        <div class="form-group">
                            <label>Tipo de empresa</label>
                            <select class="form-control required">
                                <?php
                                foreach ($entityTypeList as $entityType) {
                                ?>
                                    <option value="<?=$entityType->getId();?>"><?=$entityType->getName();?></option>
                                <?php
                                }
                                ?>
                            </select>
                        </div>

                        <button type="submit" class="btn btn-info dim block full-width m-b"><i class="fa fa-check"></i> <strong>Registrar Empresa</strong></button>

                    </form>

                </fieldset>

            </div>
        </div>

        <div style="clear: both;"></div>


        <div class="row">
            <div class="col-sm-3 text-justify">
                <h2><span class="text-blue">5000+</span> visitas al mes</h2>
                <p><strong>Empleos.Click</strong> ya tiene garantizado un tráfico mensual de más de 5000 personas. Técnicos y profesionales,
                    que visitan nuestro portal y se constituyen en potenciales prospectos en busca de nuevas oportunidades laborales.
                </p>
<!--                <p><a class="navy-link" href="#" role="button">Details »</a></p>-->
            </div>
            <div class="col-sm-3 text-justify">
                <h2><span class="text-blue">3000+</span> fans en Facebook</h2>
                <p>Sorpresivamente hemos conseguido como portal oficial de empleos, más de 2500 fans en nuestra página de facebook,
                    y tenemos semanalmente mas de 800 interacciones desde nuestra página.</p>
<!--                <p><a class="navy-link" href="#" role="button">Details »</a></p>-->
            </div>
            <div class="col-sm-3 text-justify">
                <h2><span class="text-blue">600+</span> suscriptores</h2>
                <p>Gracias a la confianza depositada por los visitantes, nuestro sistema ya cuenta con más de 600 suscriptores,
                    a quienes notificamos periódicamente sobre convocatorias que detectamos pueden ser de su interés.</p>
<!--                <p><a class="navy-link" href="#" role="button">Details »</a></p>-->
            </div>
            <div class="col-sm-3 text-justify">
                <h2>...en solo <span class="text-blue">3 meses</span></h2>
                <p>Desde el mes de septiembre de 2017, <strong>Empleos.Click</strong> se constituye en el portal de referencia para la
                    conexión de empleos, en un poco más de 3 meses nos hemos consolidado en un importante mecanismo de contacto
                    entre especialistas y empresas.
                </p>
<!--                <p><a class="navy-link" href="#" role="button">Details »</a></p>-->
            </div>
        </div>

        <section class="features">
            <div class="container">
<!--                <div class="row">-->
                    <div class="col-lg-12 text-center">
                        <div class="navy-line"></div>
                        <h1>El mejor canal gratuito para tus anuncios</h1>
                        <p>Ponemos tus anuncios al alcance de más de 5000 personas que estan en busca de empleo</p>
                    </div>
<!--                </div>-->
<!--                <div class="row">-->
                    <div class="col-lg-5 col-lg-offset-1 features-text">
                        <small>Empleos.Click</small>
                        <h2>Logra amplia difusión</h2>
                        <i class="fa fa-bullhorn big-icon pull-left"></i>
                        <p>Registra tus ofertas de empleo con tu cuenta de empresa completamente gratis,
                            asi logras amplio alcance a través de nuestros canales de difusión,
                            todo completamente en línea desde la comodidad de tu hogar u oficina.
                        </p>
                    </div>
                    <div class="col-lg-5 features-text">
                        <small>Empleos.Click</small>
                        <h2>Encuentra los mejores candidatos</h2>
                        <i class="fa fa-users big-icon pull-right"></i>
                        <p>Sabemos que el principal factor de desarrollo de cada empresa es el talento humano,
                            por eso, innovamos en brindar un medio efectivo para la obtención de prospectos y candidatos
                            que puedan cubrir de mejor manera los espacios de empleo requeridos.
                        </p>
                    </div>
<!--                </div>-->
            </div>

        </section>
    </div>

</section>

<br />

<div class="row">
    <div class="col-lg-12 text-center">
        <p class="m-t-sm">
            Contáctanos y síguenos en nuestros canales sociales
        </p>
        <ul class="list-inline social-icon">
            <li><a href="https://www.twitter.com/EmpleosClick/" target="_blank"><i class="fa fa-twitter"></i></a>
            </li>
            <li><a href="https://www.facebook.com/empleos.clic/" target="_blank"><i class="fa fa-facebook"></i></a>
            </li>
        </ul>
    </div>
    <div class="col-lg-8 col-lg-offset-2 text-center m-t-lg m-b-lg">
        <p><strong>&copy; <?=date('Y');?> Empleos.Click</strong><br/> Empleos en Bolivia</p>
    </div>
</div>

<script type="text/javascript">
jQuery(document).ready(function() {

    $("#formSuscripcion").formAjaxPost({
        'beforeSend': function(xhr){
            $("#divSuscripcion").parent().mask("");
        },
        'onErrors': function ($form, errors) {
            $form.find('div.help-block').remove();
            $form.find('div.has-error').removeClass('has-error');
            $(errors).each(function(i, el) {
                $form.find('#' + el.field)
                    .parents('div.form-group')
                    .first()
                    .addClass('has-error');
                //.append('<div class="help-block">'+el.message+'</div>');
                $form.find('#' + el.field)
                    .parent()
                    .append('<div class="help-block">'+el.message+'</div>');
            });
            $("#divSuscripcion").parent().unmask();
        },
        'onSuccess': function (data) {
            $("#myModal .panel-body").html(
                "<br /><div class=\"alert alert-success\">" +
                "En breve recibirás un correo de confirmación en: <strong>" + $("#Email").val()+ "</strong>" +
                " , si no lo encuentras en tu Bandeja de Entrada por favor verifica en Spam y márcanos como correo confiable." +
                " <br /> ¡Empleos.Click siempre a tu servicio!." +
                "</div>" +
                "<button type=\"button\" class=\"btn btn-sm btn-success block full-width m-b\" data-dismiss=\"modal\">Ok, revisare mi correo</button>"
            );
            $("#divSuscripcion").parent().unmask();
        }
    });


});
</script>