<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title"><i class="fa fa-edit"></i> Editar Sucursal</h4>
</div>
<form action="" method="post" role="form" class="ajaxPost form-horizontal">
    <input type="hidden" id="action" name="action" value="update" />
    <input type="hidden" id="id" name="id" value="<?=$entityBranch->getId();?>" />

    <div class="modal-body">
        <?php include('form.phtml'); ?>
    </div>
    <div class="modal-footer clearfix">
        <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Aceptar</button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Cancelar</button>
    </div>
</form>