<?= CodeGenerator::TAG_OPEN;?>

/**
 * Generated by Chocala Framework.
 * 
 */
class #MODEL_CLASS_NAME#Controller extends AdminWebController
{

    /**
    * @service #MODEL_CLASS_NAME#Service Injected service
    * @var #MODEL_CLASS_NAME#Service
    */
    protected $#MODEL_NAME#Service;

    public function index()
    {
        $this->redirectTo(['action' => 'dataList']);
    }

    public function dataList()
    {
        $filters = Req::all();
        $filters['_page'] = $filters['_page']?: 1;
        $filters['_max'] = $filters['_max']?: 10;
        $#MODEL_NAME#Pager = $this->#MODEL_NAME#Service->dataList($filters);
        $this->set('#MODEL_NAME#Pager', $#MODEL_NAME#Pager);
    }

    public function show()
    {
        $#MODEL_NAME# = $this->objectIfExist();
        $this->set('#MODEL_NAME#', $#MODEL_NAME#);
    }

    public function create()
    {
        $#MODEL_NAME# = new #CLASS_NAME#();
<?php
    foreach($mapedColumns as $columnMap){
//        print_r($columnMap); exit();
        $camelName = SpecialStrings::camelCase($columnMap->getName());
        $pascalName = SpecialStrings::pascalCase($columnMap->getName());
        if($columnMap->isForeignKey()){
            $relatedClassName = SpecialStrings::camelCase($columnMap->getRelatedTableName());
            $relatedFieldName = SpecialStrings::camelCase(strtolower($hashColumns[$columnMap->getName()]['field']));
            $pascalRelatedClassName = SpecialStrings::pascalCase($relatedClassName);
            $relatedColumnName = SpecialStrings::camelCase($columnMap->getRelatedColumnName());
?>
        $<?= $pascalRelatedClassName;?>List = <?= $relatedClassName;?>Query::create()
                ->orderBy<?= $relatedFieldName;?>()->find();
        $this->set('<?= $pascalRelatedClassName;?>List', $<?= $pascalRelatedClassName;?>List);
<?php
        }
    }
?>
        $this->set('#MODEL_NAME#', $#MODEL_NAME#);
        $this->view->changeLayout('ajax');
    }

    public function save()
    {
        $results = $this->#MODEL_NAME#Service->insertOrUpdate(Req::all());
        $this->set('#MODEL_NAME#', $results['object']);
        $this->set('success', $results['success']);
        $this->set('errors', $results['errors']);
        $this->renderAsJSON();
    }

    public function edit()
    {
        $#MODEL_NAME# = $this->objectIfExist();
<?php
    foreach($mapedColumns as $columnMap){
        $camelName = SpecialStrings::camelCase($columnMap->getName());
        $pascalName = SpecialStrings::pascalCase($columnMap->getName());
        if($columnMap->isForeignKey()){
            $relatedClassName = SpecialStrings::camelCase($columnMap->getRelatedTableName());
            $relatedFieldName = SpecialStrings::camelCase(strtolower($hashColumns[$columnMap->getName()]['field']));
            $pascalRelatedClassName = SpecialStrings::pascalCase($relatedClassName);
            $relatedColumnName = SpecialStrings::camelCase($columnMap->getRelatedColumnName());
?>
    $<?= $pascalRelatedClassName;?>List = <?= $relatedClassName;?>Query::create()
                ->orderBy<?= $relatedFieldName;?>()->find();
        $this->set('<?= $pascalRelatedClassName;?>List', $<?= $pascalRelatedClassName;?>List);
<?php
        }
    }
?>
        $this->set('#MODEL_NAME#', $#MODEL_NAME#);
        $this->view->changeLayout('ajax');
    }

    public function update()
    {
        $#MODEL_NAME# = $this->objectIfExist();
        $results = $this->#MODEL_NAME#Service->insertOrUpdate(Req::all(), $#MODEL_NAME#);
        $this->set('#MODEL_NAME#', $#MODEL_NAME#);
        $this->set('success', $results['success']);
        $this->set('errors', $results['errors']);
        $this->renderAsJSON();
    }

    public function delete()
    {
        $#MODEL_NAME# = $this->objectIfExist();
        try {
            $#MODEL_NAME#->delete();
            $this->redirectTo(['action' => 'dataList']);
        } catch (Exception $e) {
            $this->redirectTo(['action' => 'show',
                'id' => $#MODEL_NAME#->getPrimaryKey()]);
        }
    }

    public function objectIfExist()
    {
        try {
            return $this->#MODEL_NAME#Service->findPk($this->id);
        } catch (ChocalaException $che) {
            HttpManager::responseAs404();
        }
    }

}