<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title"><i class="fa fa-plus-square-o"></i> Agregar #MODEL_CLASS_NAME#</h4>
</div>
<form action="<?=CodeGenerator::TAG_OPEN_SHORT;?>URI::toPage();<?=CodeGenerator::TAG_CLOSE;?>save" method="post" role="form" class="ajaxPost form-horizontal">

    <div class="modal-body">

        <?=CodeGenerator::TAG_OPEN;?> include('form.phtml');<?=CodeGenerator::TAG_CLOSE;?>


    </div>
    <div class="modal-footer clearfix">
        <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Aceptar</button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Cancelar</button>
    </div>
</form>