<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>#MODEL_CLASS_NAME#s</h2>
        <ol class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>
                <a>#MODEL_CLASS_NAME#s</a>
            </li>
            <li class="active">
                <strong>Listado General</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>



<div class="wrapper wrapper-content animated fadeInRight">

    <?=CodeGenerator::TAG_OPEN_SHORT;?> BarView::renderBar('messages'); <?=CodeGenerator::TAG_CLOSE;?>


    <div class="row">

        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>#MODEL_CLASS_NAME#s List</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#">Opción 1</a>
                        </li>
                    </ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">

                <div class="fRight">
                    <a href="<?=CodeGenerator::TAG_OPEN_SHORT;?> URI::toPage().'create'; <?=CodeGenerator::TAG_CLOSE;?>" class="btn btn-primary btn-rounded" data-toggle="modal" data-target="#ajax-modal">
                        <span class="fa fa-plus-square"></span> Create #MODEL_CLASS_NAME#</a>
                </div>

                <div class="table-responsive">

                    <table class="table table-striped table-bordered table-hover dataTables" >
                        <thead>
                            <tr>
                                <th width="5%">Nº</th>
                            <?php
                            foreach($hashColumns as $hashColumn):
                                $columnMap = $hashColumn['maped'];
                                $camelName = SpecialStrings::camelCase($columnMap->getName());
                                $pascalName = SpecialStrings::pascalCase($columnMap->getName());
                                $capitalizedName = ucwords(strtolower(str_replace('_',' ', $columnMap->getName())));
                                if($columnMap->isForeignKey()):
                                    $relatedClassName = SpecialStrings::camelCase($columnMap->getRelatedTableName());
                                    $relatedFieldName = SpecialStrings::camelCase($hashColumn['field']);
                                ?>

                                <th><?= $relatedClassName;?></th>
                                <?php
                                elseif(!$columnMap->isPrimaryKey()):
                                ?>

                                <th><?= $capitalizedName;?></th>
                                <?php
                                endif;
                            endforeach;
                            ?>

                                <th width="15%">Actions</th>

                            </tr>
                        </thead>
                        <tbody>
                            <?=CodeGenerator::TAG_OPEN;?>

                            $toDetailsLink = URI::toPage().'show/';
                            $toEditLink = URI::toPage().'edit/';
                            $toDeleteLink = URI::toPage().'delete/';
                            $i = 0;
                            foreach($#MODEL_NAME#Pager as $#MODEL_NAME#):
                            <?php
                            if(sizeof($pkColumns) > 0) {
                                $pks = implode('.\'*\'.', array_map(function($obj){ return '$#MODEL_NAME#->get'.$obj->getPhpName().'()';}, $pkColumns));
                            ?>

                                $pk = <?=$pks;?>;
                            <?php
                            }
                            ?>

                            <?=CodeGenerator::TAG_CLOSE;?>

                            <tr role="row">
                                <td><?=CodeGenerator::TAG_OPEN_SHORT;?> $#MODEL_NAME#Pager->getFirstIndex() + $i; <?=CodeGenerator::TAG_CLOSE;?></td>
                                <?php
                                $nColumns = 0;
                                foreach($hashColumns as $hashColumn):
                                    $columnMap = $hashColumn['maped'];
                                    $camelName = SpecialStrings::camelCase($columnMap->getPhpName());
                                    $pascalName = SpecialStrings::pascalCase($columnMap->getPhpName());
                                    $capitalizedName = ucwords(strtolower(str_replace('_',' ', $columnMap->getName())));
                                    if($columnMap->isForeignKey()):
                                        $relatedClassName = SpecialStrings::camelCase($columnMap->getRelatedTableName());
                                        $relatedFieldName = SpecialStrings::camelCase($hashColumn['field']);
                                        $nColumns++;
                                        if($className == $relatedClassName):
                                            $relatedClassName = SpecialStrings::camelCase($columnMap->getRelatedTableName());
                                            $columnName = SpecialStrings::camelCase($columnMap->getPhpName());
                                            ?>

                                <td><?=CodeGenerator::TAG_OPEN_SHORT;?> $#MODEL_NAME#->get<?= $relatedClassName;?>RelatedBy<?= $columnName;?>()?  $#MODEL_NAME#->get<?= $relatedClassName;?>RelatedBy<?= $columnName;?>()->get<?= $relatedFieldName;?>(): '-'; <?=CodeGenerator::TAG_CLOSE;?></td>
                                <?php
                                        else:
                                ?>

                                <td><?=CodeGenerator::TAG_OPEN_SHORT;?> $#MODEL_NAME#->get<?= $relatedClassName;?>()->get<?= $relatedFieldName;?>(); <?=CodeGenerator::TAG_CLOSE;?></td>
                                <?php
                                        endif;
                                    elseif(!$columnMap->isPrimaryKey()):
                                        $nColumns++;
                                ?>

                                <td><?=CodeGenerator::TAG_OPEN_SHORT;?> $#MODEL_NAME#->get<?= $camelName;?>(); <?=CodeGenerator::TAG_CLOSE;?></td>
                                <?php
                                    endif;
                                endforeach;
                                ?>

                                <td class="text-center">
                                    <a href="<?=CodeGenerator::TAG_OPEN_SHORT;?> $toDetailsLink.$pk; <?=CodeGenerator::TAG_CLOSE;?>" class="btn btn-success btn-circle"><i class="fa fa-eye"></i></a>

                                    <a href="<?=CodeGenerator::TAG_OPEN_SHORT;?> $toEditLink.$pk; <?=CodeGenerator::TAG_CLOSE;?>" class="btn btn-warning btn-circle" data-toggle="modal" data-target="#ajax-modal"><i class="fa fa-edit"></i></a>

                                    <a href="<?=CodeGenerator::TAG_OPEN_SHORT;?> $toDeleteLink.$pk; <?=CodeGenerator::TAG_CLOSE;?>" class="btn btn-danger btn-circle"><i class="fa fa-times"></i></a>
                                </td>
                            </tr>
                            <?=CodeGenerator::TAG_OPEN;?>

                            $i++;
                            endforeach;
                            <?=CodeGenerator::TAG_CLOSE;?>

                        </tbody>

                    </table>

                </div>

            </div>

        </div>

    </div>
</div>

<script>
$(document).ready(function(){
    $('.dataTables').DataTable({
        "language": {
            "emptyTable": "No se encontraron registros"
        },
        dom: '<"html5buttons"B>lTfgitp',
        buttons: [
            {extend: 'copy', title: 'Copiar'},
            {extend: 'csv', title: 'Reporte CSV'},
            {extend: 'excel', title: 'Reporte Excel'},
            {extend: 'pdf', title: 'Reporte PDF'},
            {extend: 'print',
                customize: function (win){
                    $(win.document.body).addClass('white-bg');
                    $(win.document.body).css('font-size', '10px');
                    $(win.document.body).find('table')
                        .addClass('compact')
                        .css('font-size', 'inherit');
                }
            }
        ]
    });
});
</script>