<?= CodeGenerator::TAG_OPEN;?>

/**
 * Generated by Chocala Framework.
 * 
 */
class #MODEL_CLASS_NAME#Service extends GenericService
{

    /**
    * @var #MODEL_CLASS_NAME#Service
    */
    protected static $instance = null;

    public function createQuery()
    {
        return #CLASS_NAME#Query::create();
    }

    public function findPk($pk)
    {
        $#MODEL_NAME# = $this->createQuery()->findPk($pk);
        if (!is_object($#MODEL_NAME#)) {
            throw new ChocalaException(ChocalaErrors::INVALID_RESOURCE);
        }
        return $#MODEL_NAME#;
    }

    public function dataList($filters=[])
    {
        $query = $this->createQuery();
        /**
         * put here your filters code
         *
        if(isset($filters['field'])){
            $query->filterByField(filters['field']);
        }
         */
        $_page = $filters['_page']?: 1;
        $_max = $filters['_max']?: $query->count();
        return $query->paginate($_page, $_max);
    }

    public function insertOrUpdate($data, &$#MODEL_NAME# = null)
    {
        if(!is_object($#MODEL_NAME#)){
            $#MODEL_NAME# = new #CLASS_NAME#();
        }
        $#MODEL_NAME#->fromArray($data);
        $results['success'] = $#MODEL_NAME#->validate();
        if ($results['success']) {
            $#MODEL_NAME#->save();
        }
        $results['object'] = $#MODEL_NAME#;
        $results['errors'] = $#MODEL_NAME#->getErrorsMap();
        return $results;
    }

}