<?= CodeGenerator::TAG_OPEN;?>

/**
 * Generated by Chocala Framework.
 * 
 */
class #MODEL_CLASS_NAME#Controller extends WebController
{

    /**
    * @service #MODEL_CLASS_NAME#Service
    * @var #MODEL_CLASS_NAME#Service
    */
    protected $#MODEL_NAME#Service;

    public function index()
    {
        $this->redirectTo(array('action' => 'dataList'));
    }

    public function dataList()
    {
        $filters = Req::all();
        $filters['_page'] = $filters['_page']?: 1;
        $filters['_max'] = $filters['_page']?: 10;
        #CLASS_PAGER# = $this->#MODEL_NAME#Service->dataList($filters);
        $this->set('#CLASS_PAGER_TO_VIEW#', #CLASS_PAGER#);
    }

    public function show()
    {
        #CLASS_INSTANCE# = $this->getObjectIfExist();
        $this->set('#CLASS_INSTANCE_TO_VIEW#', #CLASS_INSTANCE#);
    }

    public function create()
    {
        #CLASS_INSTANCE# = new #CLASS_NAME#();
<?php
    foreach($mapedColumns as $columnMap){
//        print_r($columnMap); exit();
        $camelName = SpecialStrings::camelCase($columnMap->getName());
        $pascalName = SpecialStrings::pascalCase($columnMap->getName());
        if($columnMap->isForeignKey()){
            $relatedClassName = SpecialStrings::camelCase($columnMap->getRelatedTableName());
            $relatedFieldName = SpecialStrings::camelCase($hashColumns[$columnMap->getName()]['field']);
            $pascalRelatedClassName = SpecialStrings::pascalCase($relatedClassName);
            $relatedColumnName = SpecialStrings::camelCase($columnMap->getRelatedColumnName());
?>
        $<?= $pascalRelatedClassName;?>List = <?= $relatedClassName;?>Query::create()
                ->orderBy<?= $relatedFieldName;?>()->find();
        $this->set('<?= $pascalRelatedClassName;?>List', $<?= $pascalRelatedClassName;?>List);
<?php
        }
    }
?>
        $this->set('#CLASS_INSTANCE_TO_VIEW#', #CLASS_INSTANCE#);
    }

    public function save()
    {
        $results = $this->#MODEL_NAME#Service->insertOrUpdate(Req::all());
        #CLASS_INSTANCE# = $results['object'];
        if ($results['success']) {
            $this->redirectTo(array('action' => 'show',
                'id' => #CLASS_INSTANCE#->getPrimaryKey()));
        } else {
            $this->set('#CLASS_INSTANCE_TO_VIEW#', #CLASS_INSTANCE#);
            $this->set('errors', $results['errors']);
            $this->renderView('create');
        }
    }

    public function edit()
    {
        #CLASS_INSTANCE# = $this->getObjectIfExist();
<?php
    foreach($mapedColumns as $columnMap){
        $camelName = SpecialStrings::camelCase($columnMap->getName());
        $pascalName = SpecialStrings::pascalCase($columnMap->getName());
        if($columnMap->isForeignKey()){
            $relatedClassName = SpecialStrings::camelCase($columnMap->getRelatedTableName());
            $relatedFieldName = SpecialStrings::camelCase($hashColumns[$columnMap->getName()]['field']);
            $pascalRelatedClassName = SpecialStrings::pascalCase($relatedClassName);
            $relatedColumnName = SpecialStrings::camelCase($columnMap->getRelatedColumnName());
?>
    $<?= $pascalRelatedClassName;?>List = <?= $relatedClassName;?>Query::create()
                ->orderBy<?= $relatedFieldName;?>()->find();
        $this->set('<?= $pascalRelatedClassName;?>List', $<?= $pascalRelatedClassName;?>List);
<?php
        }
    }
?>
        $this->set('#CLASS_INSTANCE_TO_VIEW#', #CLASS_INSTANCE#);
    }

    public function update()
    {
        #CLASS_INSTANCE# = $this->getObjectIfExist();
        $results = $this->#MODEL_NAME#Service->insertOrUpdate(Req::all(), #CLASS_INSTANCE#);
        if ($results['success']) {
            $this->redirectTo(array('action' => 'show',
                'id' => #CLASS_INSTANCE#->getPrimaryKey()));
        } else {
            $this->set('#CLASS_INSTANCE_TO_VIEW#', #CLASS_INSTANCE#);
            $this->set('errors', $results['errors']);
            $this->renderView('edit');
        }
    }

    public function delete()
    {
        #CLASS_INSTANCE# = $this->getObjectIfExist();
        try {
            #CLASS_INSTANCE#->delete();
            $this->redirectTo(array('action' => 'dataList'));
        } catch (Exception $e) {
            $this->redirectTo(array('action' => 'show',
                'id' => #CLASS_INSTANCE#->getPrimaryKey()));
        }
    }

    public function getObjectIfExist()
    {
        try {
            return $this->#MODEL_NAME#Service->findPk($this->id);
        } catch (ChocalaException $che) {
            HttpManager::responseAs404();
        }
    }

}