<?=CodeGenerator::TAG_OPEN_SHORT;?> BarView::renderBar('messages'); <?=CodeGenerator::TAG_CLOSE;?>

<div class="dialog" style="padding: 0 250px">
    
    <div class="fRight">
        <a href="<?=CodeGenerator::TAG_OPEN_SHORT;?> URI::toPage(); <?=CodeGenerator::TAG_CLOSE;?>" class="linkGoBack">Cancel edition</a>
    </div>
    
    <h1>Update #MODEL_CLASS_NAME#</h1>
    <hr class="clear" />
    
    <form method="POST" action="<?=CodeGenerator::TAG_OPEN_SHORT;?> URI::toPage(); <?=CodeGenerator::TAG_CLOSE;?>update/<?=CodeGenerator::TAG_OPEN_SHORT;?> #CLASS_INSTANCE#->getPrimaryKey(); <?=CodeGenerator::TAG_CLOSE;?>">

        <?=CodeGenerator::TAG_OPEN;?> include('form.phtml');<?=CodeGenerator::TAG_CLOSE;?>


        <div class="input">
            <div class="value">
                <input type="submit" name="update" value="Update" />
            </div>
        </div>

    </form>

</div>