<?= CodeGenerator::TAG_OPEN;?>

/**
 * Generated by Chocala Framework.
 * 
 */
class #MODEL_CLASS_NAME#Service extends ChocalaSingleService
{

    /**
    * @var #MODEL_CLASS_NAME#Service
    */
    protected static $instance = null;

    public function createQuery()
    {
        return #CLASS_NAME#Query::create();
    }

    public function findPk($pk)
    {
        $object = $this->createQuery()->findPk($pk);
        if (!is_object($object)) {
            throw new ChocalaException(ChocalaErrors::INVALID_RESOURCE);
        }
        return $object;
    }


    public function dataList($filters=[])
    {
        $query = $this->createQuery();
        /**
         * put here your filters code
         *
        if(isset($filters['field'])){
            $query->filterByField(filters['field']);
        }
         */
        $_page = $filters['_page']?: 1;
        $_max = $filters['_max']?: $query->count();
        return $query->paginate($_page, $_max);
    }

    public function insertOrUpdate($data, &$object = null)
    {
        if(!is_object($object)){
            $object = new #CLASS_NAME#();
        }
        $object->fromArray($data);
        $results['success'] = $object->validate();
        if ($results['success']) {
            $object->save();
        }
        $results['object'] = $object;
        $results['errors'] = $object->getErrorsMap();
        return $results;
    }

}