<?php
/**
 * Generated by Chocala Framework.
 *
 */
class PostulanteService extends AuditService
{
    /**
     * @var PostulanteService
     */
    protected static $instance = null;
    protected $aAppliedAnnouncements = null;

    public function createQuery()
    {
        return JobPostulanteQuery::create();
    }

    /**
     * @param $pk
     * @return array|JobPostulante|mixed
     * @throws NotFoundException
     */
    public function findPk($pk)
    {
        $auth = $this->createQuery()->findPk($pk);
        if (!is_object($auth)) {
            throw new NotFoundException(ChocalaErrors::INVALID_RESOURCE);
        }
        return $auth;
    }

    /**
     * @return PostulanteService
     */
    public static function instance()
    {
        return parent::instance(); // TODO: Change the autogenerated stub
    }

    public function insertOrUpdate($data, &$postulante = null)
    {
        if(!is_object($postulante)){
            $postulante = new JobPostulante();
        }
        $postulante->fromArray($data);
        $postulante->save();
        $results['object'] = $postulante;
        $results['errors'] = [];//$postulante->getErrorsMap();
        return $results;
    }

    public function getArrayAppliedAnnouncements($idPostulante)
    {
        if($this->aAppliedAnnouncements == null){
            $this->aAppliedAnnouncements = JobPostulanteAvisoQuery::create()
                ->filterByIdPostulante($idPostulante)
                ->find()
                ->toKeyValue("IdAviso", "IdAviso");
        }
        return $this->aAppliedAnnouncements;
    }

    public function hasBeenApplied($idAviso, $idPostulante)
    {
        return in_array($idAviso, $this->getArrayAppliedAnnouncements($idPostulante));
    }

    /**
     * @param $user SysUser
     */
    public function getIdPostulante($user)
    {
        if (is_object($user)) {
            $postulante = JobPostulanteQuery::create()
                ->filterByUserId($user->getId())
                ->filterByEstado(JobPostulante::ESTADO_ELIMINADO, Criteria::NOT_EQUAL)
                ->findOne();
            return is_object($postulante) ? $postulante->getId() : null;
        }
        return null;
    }
}