<?php
/**
 * Generated by Chocala Framework.
 *
 */
class PostulanteService extends GenericService
{
    /**
     * @var PostulanteService
     */
    protected static $instance = null;

    public function createQuery()
    {
        return JobPostulanteQuery::create();
    }

    public function findPk($pk)
    {
        $auth = $this->createQuery()->findPk($pk);
        if (!is_object($auth)) {
            throw new ChocalaException(ChocalaErrors::INVALID_RESOURCE);
        }
        return $auth;
    }

    /**
     * @return PostulanteService
     */
    public static function instance()
    {
        return parent::instance(); // TODO: Change the autogenerated stub
    }

    public function insertOrUpdate($data, &$postulante = null)
    {
        if(!is_object($postulante)){
            $postulante = new JobPostulante();
        }
        $postulante->fromArray($data);
        $postulante->save();
        $results['object'] = $postulante;
        $results['errors'] = [];//$postulante->getErrorsMap();
        return $results;
    }
}