<?php
$uPk = $uri->getId();
?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title"><i class="fa fa-key"></i> Roles de Acceso en URI: <?=$uri->getTitle();?></h4>
</div>
<div class="modal-body">
    <input type="hidden" id="onImg" value="<?=ICO_16;?>flag_On.png" alt="" title="" />
    <input type="hidden" id="offImg" value="<?=ICO_16;?>flag_Off.png" alt="" title="" />

    <table id="aclTable" class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th>Rol</th>
            <th width="12%">Permitido</th>
            <th width="12%">Leer</th>
            <th width="12%">Crear</th>
            <th width="12%">Actualizar</th>
            <th width="12%">Borrar</th>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach($roles as $rol){
            $rPk = $rol->getId();
            $rolUri = null;
            foreach ($rolesUri as $rolXUri){
                if($rolXUri->getRolId() == $rPk){
                    $rolUri = $rolXUri;
                }
            }
            $pk = $urlsPk.'*'.$rPk;
            $aut = is_object($rolUri);
            $autRead = is_object($rolUri)? $rolUri->getAutRead(): false;
            $autCreate = is_object($rolUri)? $rolUri->getAutCreate(): false;
            $autUpdate = is_object($rolUri)? $rolUri->getAutUpdate(): false;
            $autDelete = is_object($rolUri)? $rolUri->getAutDelete(): false;
            ?>
            <tr id="tr<?=$rPk;?>">
                <td><?=$rol->getName();?> <span>(<?=$rol->getCode();?>)</span></td>
                <td class="text-center">
                    <img src="<?=ICO_16.($aut? 'flag_On':'flag_Off');?>.png" alt="" title="" rel="<?=$rPk;?>" class="mainAutImg autImg pointer" />
                    <img src="<?=ICO_16;?>loading.gif" alt="" title="" class="autLoadImg" style="display: none;" />
                </td>
                <td class="text-center">
                    <img src="<?=ICO_16.($autRead? 'flag_On':'flag_Off');?>.png" alt="" title="" rel="<?=$rPk;?>" class="autReadImg autDetail autImg" type="read" />
                    <img src="<?=ICO_16;?>loading.gif" alt="" title="" class="autLoadImg" style="display: none;" />
                </td>
                <td class="text-center">
                    <img src="<?=ICO_16.($autCreate? 'flag_On':'flag_Off');?>.png" alt="" title="" rel="<?=$rPk;?>" class="autDetail autImg" type="create" />
                    <img src="<?=ICO_16;?>loading.gif" alt="" title="" class="autLoadImg" style="display: none;" />
                </td>
                <td class="text-center">
                    <img src="<?=ICO_16.($autUpdate? 'flag_On':'flag_Off');?>.png" alt="" title="" rel="<?=$rPk;?>" class="autDetail autImg" type="update" />
                    <img src="<?=ICO_16;?>loading.gif" alt="" title="" class="autLoadImg" style="display: none;" />
                </td>
                <td class="text-center">
                    <img src="<?=ICO_16.($autDelete? 'flag_On':'flag_Off');?>.png" alt="" title="" rel="<?=$rPk;?>" class="autDetail autImg" type="delete" />
                    <img src="<?=ICO_16;?>loading.gif" alt="" title="" class="autLoadImg" style="display: none;" />
                </td>
            </tr>
        <?php
        }
        ?>
        </tbody>
    </table>
</div>

<!-- page script -->
<script type="text/javascript">
$().ready(function(){
//    $(".loadContent").loadContent();
    $(".mainAutImg").click(function(){
        var rolId = $(this).attr("rel");
        var onImgSrc = $("#onImg").val();
        var offImgSrc = $("#offImg").val();
        $.ajax({
            url: "<?=  URI::toPage().'changeMainPermission/?uriId='.$uPk;?>",
            type: "POST",
            data: {rolId: rolId},
            beforeSend: function( xhr ) {
                $("#tr"+rolId+" .autImg").hide();
                $("#tr"+rolId+" .autLoadImg").show();
            }
        })
        .done(function(results) {
            $("#tr"+rolId+" .autImg").attr('src', offImgSrc);
            if (results && results.permission) {
                $("#tr"+rolId+" .mainAutImg").attr('src', onImgSrc);
                $("#tr"+rolId+" .autReadImg").attr('src', onImgSrc);
            }
        })
        .always(function(result){
            $("#tr"+rolId+" .autImg").show();
            $("#tr"+rolId+" .autLoadImg").hide();
        });
    });
    $(".autDetail").click(function(){
        var img = $(this);
        var rolId = $(this).attr("rel");
        var onImgSrc = $("#onImg").val();
        var offImgSrc = $("#offImg").val();
        $.ajax({
            url: "<?=  URI::toPage().'changePermissionType/?uriId='.$uPk;?>",
            type: "POST",
            data: {rolId: rolId, type: img.attr("type")},
            beforeSend: function( xhr ) {
                img.hide();
                img.siblings().show();
            }
        })
        .done(function(results) {
            if (results && results.permission) {
                img.attr('src', onImgSrc);
            }else{
                img.attr('src', offImgSrc);
            }
        })
        .always(function(result){
            img.show();
            img.siblings().hide();
        });
    });
});
</script>