<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Entidades</h2>
        <ol class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>
                <a href="<?= URI::toPage() ?>">Entidades</a>
            </li>
            <li class="active">
                <strong>Datos de Entidad</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

    <?= BarView::renderBar('messages'); ?>

    <div class="row">

        <div class="col-lg-6">
            <div class="ibox float-e-margins">

                <div class="ibox-title">
                    <h5>Datos Generales</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">

                    <div class="btn-group">
                        <?php if(PageControl::canUpdate()){ ?>
                            <a href="<?= URI::toPage().'edit/'.$entity->getId(); ?>" class="btn btn-sm btn-warning btn-rounded" data-toggle="modal" data-target="#ajax-modal-lg">
                                <span class="fa fa-edit"></span> Editar Datos</a>
                        <?php } ?>
                    </div>

                    <div class="table-responsive">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <th class="col-md-4">Nombre Comercial:</th>
                                    <td><?=$entity->getComercialName();?></td>
                                </tr>
                                <tr>
                                    <th>Nombre Formal:</th>
                                    <td><?=$entity->getFormalName();?></td>
                                </tr>
                                <tr>
                                    <th>Código:</th>
                                    <td><?=$entity->getCode();?></td>
                                </tr>
                                <tr>
                                    <th>Tipo de Entidad:</th>
                                    <td><?=$entity->getSysEntityType()->getName();?></td>
                                </tr>
                                <tr>
                                    <th>N.I.T.:</th>
                                    <td><?=$entity->getNit();?></td>
                                </tr>
                                <tr>
                                    <th>Actividades:</th>
                                    <td><?=$entity->getActivities();?></td>
                                </tr>
                                <tr>
                                    <th>Descripción:</th>
                                    <td><?=$entity->getDescription();?></td>
                                </tr>
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>

        </div>

        <div class="col-lg-6">
            <div class="ibox float-e-margins">

                <div class="ibox-title">
                    <h5>Datos de Contacto</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">

                    <h4>Oficina Central</h4>

                    <div class="table-responsive">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <th class="col-md-4">Email:</th>
                                    <td><?=$entity->getEmail();?></td>
                                </tr>
                                <tr>
                                    <th>Dirección:</th>
                                    <td><?=$entity->getAddress();?></td>
                                </tr>
                                <tr>
                                    <th>Ciudad:</th>
                                    <td><?=$entity->getSysLocation()->getName();?></td>
                                </tr>
                                <tr>
                                    <th>Teléfono:</th>
                                    <td><?=$entity->getPhone();?></td>
                                </tr>
                                <tr>
                                    <th>Celular:</th>
                                    <td><?=$entity->getCellphone();?></td>
                                </tr>

                            </tbody>
                        </table>

                    </div>

                    <hr />
                    <h4>Configuración y Uso</h4>
                    <hr />
                    <div class="text-center">

                        <a href="<?= URI::toModule().'entityParam/entity/'.$entity->getId(); ?>" class="btn btn-sm btn-success btn-rounded">
                            <span class="fa fa-cogs"></span> Ver Parámetros</a>

                        &nbsp;&nbsp;

                        <a href="<?= URI::toModule().'entityUser/entity/'.$entity->getId(); ?>" class="btn btn-sm btn-info btn-rounded">
                            <span class="fa fa-group"></span> Ver Usuarios</a>

                    </div>

                </div>
            </div>

        </div>

    </div>

    <div class="row">
        <div class=" col-lg-12">

            <div class="ibox float-e-margins">

                <div class="ibox-title">
                    <h5>Sucursales</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">

                    <div class="btn-group">
                        <?php if(PageControl::canCreate()){ ?>
                            <a href="<?= URI::toModule().'entityBranch/create/'.$entity->getId(); ?>" class="btn btn-sm btn-primary btn-rounded" data-toggle="modal" data-target="#ajax-modal">
                                <span class="fa fa-plus-square"></span> Agregar Sucursal</a>
                        <?php } ?>
                    </div>

                    <div class="table-responsive">

                        <table class="table table-striped dataTables">
                            <thead>
                                <tr>
                                    <th width="5%">N°</th>
                                    <th>Nombre</th>
                                    <th>Dirección</th>
                                    <th width="10%">Teléfono</th>
                                    <th width="10%">Celular</th>
                                    <th width="10%">Fax</th>
                                    <th>Descripción</th>
                                    <th width="15%">Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php
                            $i = 0;
                            $toEditLink = URI::toModule().'entityBranch/edit/';
                            $toDeleteLink = URI::toModule().'entityBranch/delete/';
                            foreach($entity->branches() as $entityBranch){
                                $i++;
                                $pk = $entityBranch->getId();
                                ?>
                                <tr class="<?=($i%2==0)? 'odd': 'even';?>">
                                    <td class="text-center"><?=$i;?></td>
                                    <td class="text-left"><?=$entityBranch->getName();?></td>
                                    <td class="text-left">
                                        <?=$entityBranch->getAddress();?>
                                        <br />
                                        <i><?=$entityBranch->getSysLocation()->getName();?></i>
                                    </td>
                                    <td class="text-center"><?=$entityBranch->getPhone();?></td>
                                    <td class="text-center"><?=$entityBranch->getCellphone();?></td>
                                    <td class="text-center"><?=$entityBranch->getFax();?></td>
                                    <td class="text-left"><?=$entityBranch->getDescription();?></td>
                                    <td class="text-center">
                                        <?php
                                        if(PageControl::canUpdate()){
                                            ?>
                                            <a href="<?= $toEditLink.$pk; ?>" class="btn btn-sm btn-warning btn-circle" data-toggle="modal" data-target="#ajax-modal"><i class="fa fa-edit"></i></a>
                                            <?php
                                        }
                                        if(PageControl::canDelete()){
                                            ?>
                                            <a href="<?= $toDeleteLink.$pk; ?>" class="btn btn-sm btn-danger btn-circle"><i class="fa fa-times"></i></a>
                                            <?php
                                        }
                                        ?>
                                    </td>
                                </tr>
                            <?php
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>

                </div>

            </div>
        </div>

    </div>

</div>


<script>
$(document).ready(function(){
    $('.dataTables').DataTable({
        "language": {
            "emptyTable": "No se encontraron registros"
        },
        dom: '<"html5buttons"B>lTfgitp',
        buttons: [
            {extend: 'copy', title: 'Copiar'},
            {extend: 'csv', title: 'Reporte CSV'},
            {extend: 'excel', title: 'Reporte Excel'},
            {extend: 'pdf', title: 'Reporte PDF'},
            {extend: 'print',
                customize: function (win){
                    $(win.document.body).addClass('white-bg');
                    $(win.document.body).css('font-size', '10px');
                    $(win.document.body).find('table')
                        .addClass('compact')
                        .css('font-size', 'inherit');
                }
            }
        ]
    });
});
</script>