<section class="timeline gray-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="col-md-3 col-lg-3">
                    <img src="img/Logo-Buscar-Empleos-Click.png" alt="Empleos.click" class="img-responsive text-center" />
                </div>
                <div class="col-md-9 col-lg-6">
                    <h1 class="text-success">Tu Titulo</h1>
                    <p>Catálogo de ofertas laborales en Bolivia</p>
                </div>
            </div>
        </div>
        <div class="row ibox">
            <div class="ibox-content">
                <h3 class="text-blue">¡Bienvenido a Empleos.Click!</h3>
                <h4>Tenemos publicaciones</h4>
                <div class="row text-center">
                    <h2>SKELETON SECTION</h2>
                </div>
            </div>
        </div>
    </div>

</section>