<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
    <h1 class="modal-title text-success"><?=$aviso->getCargo();?></h1>
</div>
<div class="modal-body aviso-details">

    <?php
    if(!$aviso->getTieneImagen()) {
    ?>
    <div class="row">
        <div class="form-group">
            <label class="control-label col-sm-3">Empresa</label>
            <div class="col-sm-9">
                <?=$aviso->getNombreEmpresa();?>
            </div>
        </div>
    </div>

<!--    <div class="row">-->
<!--        <div class="form-group">-->
<!--            <label class="control-label col-sm-3">Descripción</label>-->
<!--            <div class="col-sm-9">-->
<!--                --><?//=nl2br($aviso->getDescripcion());?>
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!---->
    <div class="row">
        <div class="form-group">
            <label class="control-label col-sm-3">Requisitos</label>
            <div class="col-sm-9">
                <?=nl2br($aviso->getRequisito());?>
            </div>
        </div>
    </div>

    <?php
    if($aviso->getCompetencias() != '') {
        ?>
        <div class="row">
            <div class="form-group">
                <label class="control-label col-sm-3">Competencias</label>
                <div  class="col-sm-9"><?=$aviso->getCompetencias();?></div>
            </div>
        </div>
        <?php
    }
    ?>


    <?php
    if($aviso->getDireccion() != '') {
    ?>
        <div class="row">
            <div class="form-group">
                <label class="control-label col-sm-3">Dirección</label>
                <div class="col-sm-9"><?=$aviso->getDireccion();?></div>
            </div>
        </div>
    <?php
    }
    ?>

    <?php
    if($aviso->getTelefonoContacto() != '') {
    ?>
        <div class="row">
            <div class="form-group">
                <label class="control-label col-sm-3">Teléfono</label>
                <div class="col-sm-9"><?=$aviso->getTelefonoContacto();?></div>
            </div>
        </div>
    <?php
    }
    ?>

    <?php
    if($aviso->getCorreoContacto() != '') {
    ?>
        <div class="row">
            <div class="form-group">
                <label class="control-label col-sm-3">Email</label>
                <div class="col-sm-9"><?=$aviso->getCorreoContacto();?></div>
            </div>
        </div>
    <?php
    }
    ?>

    <div class="row">
        <div class="form-group">
            <?php
            if($aviso->getAniosExperiencia() != '') {
                ?>
                <label class="control-label col-sm-3">Años de Experiencia</label>
                <div class="col-sm-3"><?=$aviso->getAniosExperiencia();?></div>
                <?php
            }
            ?>
            <?php
            if($aviso->getNivelFormacion() != '') {
                ?>
                <label class="control-label col-sm-3">Formación</label>
                <div class="col-sm-3"><?=$aviso->getNivelFormacion();?></div>

                <?php
            }
            ?>
        </div>
    </div>

    <div class="row">
        <div class="form-group">
            <label class="control-label col-sm-3">Fecha de Publicación</label>
            <div class="col-sm-3"><?=$aviso->getFechaPublicacion("d/m/Y");?></div>

            <label class="control-label col-sm-3">Fecha de Vencimiento</label>
            <div class="col-sm-3"><?=$aviso->getFechaVencimiento("d/m/Y");?></div>
        </div>
    </div>

    <?php
    }else {
    ?>
    <div class="row">

        <div class="col-md-3">
                <div class="row">
                    <div class="form-group">
                        <label class="control-label">Empresa</label>
                        <div class="">
                            <?=$aviso->getNombreEmpresa();?>
                        </div>
                    </div>
                </div>

                <?php
                /*if($aviso->getDescripcion() != '') {
                ?>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label">Descripción</label>
                            <div class="">
                                <?= nl2br($aviso->getDescripcion()); ?>
                            </div>
                        </div>
                    </div>
                <?php
                }*/
                ?>

                <div class="row">
                    <div class="form-group">
                        <label class="control-label">Requisitos</label>
                        <div class="">
                            <?=nl2br($aviso->getRequisito());?>
                        </div>
                    </div>
                </div>

                <?php
                if($aviso->getCompetencias() != '') {
                    ?>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label">Competencias</label>
                            <div class=""><?=$aviso->getCompetencias();?></div>
                        </div>
                    </div>
                    <?php
                }
                ?>

                <?php
                if($aviso->getDireccion() != '') {
                    ?>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label">Dirección</label>
                            <div class=""><?=$aviso->getDireccion();?></div>
                        </div>
                    </div>
                    <?php
                }
                ?>

                <?php
                if($aviso->getTelefonoContacto() != '') {
                    ?>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label">Teléfono</label>
                            <div class=""><?=$aviso->getTelefonoContacto();?></div>
                        </div>
                    </div>
                    <?php
                }
                ?>

                <?php
                if($aviso->getCorreoContacto() != '') {
                    ?>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label ">Email</label>
                            <div class=""><?=$aviso->getCorreoContacto();?></div>
                        </div>
                    </div>
                    <?php
                }
                ?>

                <?php
                if($aviso->getAniosExperiencia() != '') {
                    ?>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label ">Años de Experiencia</label>
                            <div class=""><?=$aviso->getAniosExperiencia();?></div>
                        </div>
                    </div>
                    <?php
                }
                ?>
                <?php
                if($aviso->getNivelFormacion() != '') {
                    ?>
                    <div class="row">
                        <div class="form-group">
                            <label class="control-label">Formación</label>
                            <div class=""><?=$aviso->getNivelFormacion();?></div>
                        </div>
                    </div>
                    <?php
                }
                ?>
                <div class="row">
                    <div class="form-group">
                        <label class="control-label ">Ciudad</label>
                        <div class=""><?=$aviso->getLocalizacion();?></div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <label class="control-label">Fecha de Publicación</label>
                        <div class=""><?=$aviso->getFechaPublicacion("d/m/Y");?></div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <label class="control-label">Fecha de Vencimiento</label>
                        <div class=""><?=$aviso->getFechaVencimiento("d/m/Y");?></div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <label class="control-label ">Fuente</label>
                        <div class=""><?=$aviso->getFuente();?></div>
                    </div>
                </div>

        </div>
        <div class="col-md-8">
            <?php
            if(file_exists(PUBLIC_DIR.'files/avisos/'.$aviso->getId().'.jpg')){
            ?>
                <img src="<?=WEB_ROOT.'files/avisos/'.$aviso->getId().'.jpg';?>" alt="" class="col-sm-12" style="max-width: 100%;">
            <?php
            } else {
            ?>
                <img src="<?=WEB_ROOT.'files/avisos/'.$aviso->getId().'.png';?>" alt="" class="col-sm-12" style="max-width: 100%;">
            <?php
            }
            ?>
        </div>
    </div>
    <?php
    }
    ?>

</div>
<div class="modal-footer">
    <?php
    if (HttpManager::isAJAXRequest()) {
    ?>
    <button type="button" class="btn btn-success" data-dismiss="modal">Cerrar</button>
    <?php
    }
    ?>
</div>

<?php
if(strtoupper(Config::_('app.run.environment')) != 'DEVELOPMENT') {
?>
<script type="text/javascript">
$().ready(function () {
    ga("send", "pageview", "<?=URI::toId() . SpecialStrings::text2Url($aviso->getCargo());?>");
});
</script>
<?php
}
?>