<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title"><i class="fa fa-plus-square-o"></i> Agregar Usuario</h4>
</div>
<form action="" method="post" role="form" class="ajaxPost form-horizontal">
    <input type="hidden" id="action" name="action" value="save" />

    <div class="modal-body">

        <?php include('formUser.phtml'); ?>

        <div class="row">

            <div class="col-sm-6">
                <div class="form-group">
                    <label class="control-label col-sm-4" for="Rol">Rol Principal</label>
                    <div class="col-sm-8">
                        <select id="RolId" name="RolId" class="form-control">
                            <?php
                            foreach($rols as $rol) {
                                ?>
                                <option value="<?=$rol->getId;?>"><?=$rol->getName();?></option>
                                <?php
                            }
                            ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>

        <?php include('formPerson.phtml'); ?>

    </div>
    <div class="modal-footer clearfix">
        <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Aceptar</button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Cancelar</button>
    </div>
</form>
<script type="text/javascript">
$().ready(function() {
    $(".ajaxPost").formAjaxPost();
});
</script>