<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title"><i class="fa fa-edit"></i> Editar Datos de Usuario</h4>
</div>
<form action="" method="post" role="form" class="form-horizontal ajaxPost">
    <input type="hidden" id="action" name="action" value="update" />
    <input type="hidden" id="id" name="id" value="<?=$user->getId();?>" />

    <div class="modal-body">

        <?php include('formUser.phtml'); ?>

        <?php include('formPerson.phtml'); ?>

    </div>
    <div class="modal-footer clearfix">
        <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Aceptar</button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Cancelar</button>
    </div>
</form>

<script type="text/javascript">
$().ready(function() {
    $(".ajaxPost").formAjaxPost({
        onSuccess: function (response) {
            window.location = "<?=  URI::toPage();?>show/"+response.user.Id;
        }
    });
});
</script>
