<fieldset>
    <h3 class="underline">Cuenta de Usuario</h3>

    <div class="row">

        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label col-sm-4" for="Email">Email</label>
                <div class="col-sm-8">
                    <input type="email" id="Email" name="Email" value="<?=$user? $user->getEmail(): '';?>"
                           size="30" maxlength="80" class="form-control"
                           placeholder="Email..." autocomplete="off" />
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="control-label col-sm-4" for="Username">Username</label>
                <div class="col-sm-8">
                    <input type="text" id="Username" name="Username" value="<?=$user? $user->getUsername(): '';?>"
                           size="30" maxlength="30" class="form-control"
                           placeholder="Username..." autocomplete="off" />
                </div>
            </div>
        </div>
    </div>

</fieldset>
