<div class="table-responsive">

    <table class="table">
        <tbody>
        <tr>
            <th class="col-md-5">Primer Nombre:</th>
            <td><?=$person->getFirstName();?></td>
        </tr>
        <tr>
            <th>Segundo Nombre:</th>
            <td><?=$person->getMiddleName();?></td>
        </tr>
        <tr>
            <th>Primer Apellido:</th>
            <td><?=$person->getLastName();?></td>
        </tr>
        <tr>
            <th>Segundo Apellido:</th>
            <td><?=$person->getSecondLastName();?></td>
        </tr>
        <tr>
            <th>D.N.I.:</th>
            <td><?=$person->getIdNumber();?> <?=$person->getIdExtension();?></td>
        </tr>
        <tr>
            <th>Sexo:</th>
            <td><?=$person->getGender();?></td>
        </tr>
        <tr>
            <th>Fecha de Nacimiento:</th>
            <td><?=$person->getDateOfBirth('d/M/Y')?: '-----';?></td>
        </tr>
        <tr>
            <th>Lugar de Nacimiento:</th>
            <td><?=$person->getPlaceOfBirth()?: '-----';?></td>
        </tr>
        <tr>
            <th>Dirección:</th>
            <td>
                <?=$person->getAddress()?: '-----';?>
                <br />
                <small><?=$person->getCity()? '<strong>Ciudad:</strong> '.$person->getCity(): '';?></small>
            </td>
        </tr>
        <tr>
            <th>Casilla Postal:</th>
            <td><?=$person->getPob()?: '-----';?></td>
        </tr>
        <tr>
            <th>Teléfonos:</th>
            <td>
                <small>
                    <?php
                    if($person->getPhoneHome()){
                        ?>
                        <strong>Domicilio:</strong> <?=$person->getPhoneHome();?>
                        <br />
                        <?php
                    }
                    if($person->getPhoneWork()){
                        ?>
                        <strong>Domicilio:</strong> <?=$person->getPhoneWork();?>
                        <br />
                        <?php
                    }
                    if($person->getCellphone1()){
                        ?>
                        <strong>Celular 1:</strong> <?=$person->getCellphone1();?>
                        <br />
                        <?php
                    }
                    if($person->getCellphone2()){
                        ?>
                        <strong>Celular 2:</strong> <?=$person->getCellphone2();?>
                        <br />
                        <?php
                    }
                    ?>
                    ____________________
                </small>
            </td>
        </tr>
        </tbody>
    </table>

</div>