<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title"><i class="fa fa-mail-forward"></i> Restablecimiento de Acceso de Usuario</h4>
</div>
<div class="form-horizontal">
    <div class="modal-body">

        <div class="form-group">
            <label class="control-label col-sm-4" for="Email">Usuario</label>
            <div class="col-sm-8">
                <?=$user->getUsername();?>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-4" for="Email">Email</label>
            <div class="col-sm-8">
                <?=$user->getEmail();?>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-4" for="Email">Nombre Completo</label>
            <div class="col-sm-8">
                <?=$user->person()? $user->person()->formalName(): '';?>
            </div>
        </div>

        <div id="loadForm">
        </div>

    </div>
    <div class="modal-footer clearfix text-center">
        <a id="linkSend" href="<?=URI::toPage().'sendRequestPassword/'.$user->getId();;?>" class="btn btn-sm btn-success btn-rounded">
            <i class="fa fa-mail-forward"></i> Enviar restauración de acceso a usuario</a>
    </div>
</div>

<script type="text/javascript">
$().ready(function() {
    $("#linkSend").click(function(){
        var $link = $(this);
        $link.attr("disabled", "yes");
        $("#loadForm").load($link.attr("href"), function(data){
            $link.parent().remove();
            $("#loadForm").fadeIn();
        });
        return false;
    });
});
</script>