<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title"><i class="fa fa-plus"></i> Asignar Rol de Usuario</h4>
</div>
<form action="" method="post" role="form" class="form-horizontal ajaxPost">
    <input type="hidden" id="action" name="action" value="rolSave" />
    <input type="hidden" id="UserId" name="UserId" value="<?=$user->getId();?>" />

    <div class="modal-body">
        <div class="form-group">
            <label class="control-label col-sm-3">Usuario</label>
            <div class="col-sm-9">
                <?=$user->formalName();?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3" for="RolId">Rol</label>
            <div class="col-sm-9">
                <select id="RolId" name="RolId" class="form-control">
                    <option value="">Seleccionar...</option>
                    <?php
                    foreach($availableRols as $availableRol){
                        ?>
                        <option value="<?=$availableRol->getId();?>"><?=$availableRol->getName();?></option>
                    <?php
                    }
                    ?>
                </select>
            </div>
        </div>
    </div>
    <div class="modal-footer clearfix">
        <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Aceptar</button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Cancelar</button>
    </div>
</form>
<script type="text/javascript">
$().ready(function(){
    $('.ajaxPost').formAjaxPost();
    //$("#simplePanel form").validationEngine();
});
</script>