<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Usuarios del Sistema</h2>
        <ol class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>
                <a href="<?= URI::toPage() ?>">Usuarios del Sistema</a>
            </li>
            <li class="active">
                <strong>Datos de Usuario</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

    <?= BarView::renderBar('messages'); ?>

    <div class="row">

        <div class="col-lg-6">
            <div class="ibox float-e-margins">

                <div class="ibox-title">
                    <h5>Datos Personales</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">

                    <div class="btn-group">
                        <?php if(PageControl::canUpdate()){ ?>
                            <a href="<?= URI::toPage().'edit/'.$user->getId(); ?>" class="btn btn-sm btn-warning btn-rounded" data-toggle="modal" data-target="#ajax-modal-lg">
                                <i class="fa fa-edit"></i> Editar Datos</a>
                        <?php } ?>
                    </div>

                    <?php include_once('personData.phtml');?>

                </div>

            </div>
        </div>

        <div class="col-lg-6">
            <div class="ibox float-e-margins">

                <div class="ibox-title">
                    <h5>Datos de Usuario</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">

                    <?php if(PageControl::canUpdate()){ ?>
                        <a href="<?=URI::toPage().'resetPassword/'.$user->getId();;?>" class="btn btn-sm btn-success btn-rounded" data-toggle="modal" data-target="#ajax-modal">
                            <i class="fa fa-mail-forward"></i> Restaurar datos de acceso</a>
                        <a href="<?=URI::toPage().'changeStatus/'.$user->getId();;?>" class="btn btn-sm btn-success btn-rounded" data-toggle="modal" data-target="#ajax-modal">
                            <i class="fa fa-toggle-on"></i> Cambiar Estado</a>
                    <?php } ?>

                    <div class="table-responsive">

                        <table class="table">
                            <tbody>
                                <tr>
                                    <th class="col-md-4">Email:</th>
                                    <td><?=$user->getEmail();?></td>
                                </tr>
                                <tr>
                                    <th>Username:</th>
                                    <td><?=$user->getUsername();?></td>
                                </tr>
                                <tr>
                                    <th>Password:</th>
                                    <td>
                                        *****
                                    </td>
                                </tr>
                                <tr>
                                    <th>Estado:</th>
                                    <td><?=SysUser::statusFrom($user->getStatus());?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>

            <div class="ibox float-e-margins">

                <div class="ibox-title">
                    <h5>Roles de Usuario</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">

                    <div class="btn-group">
                        <?php if(PageControl::canUpdate()){ ?>
                            <a href="<?=URI::toPage().'rolAdd/'.$user->getId();;?>" class="btn btn-sm btn-primary btn-rounded" data-toggle="modal" data-target="#ajax-modal-sm">
                                <i class="fa fa-plus"></i> Asignar Rol</a>
                        <?php } ?>
                    </div>

                    <div class="table-responsive">
                        <?php
                        $userRols = $user->inOrderRols();
                        if($userRols->count()>0){
                            ?>
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Rol de Usuario</th>
                                    <th width="20%">Quitar</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                foreach ($userRols as $userRol){
                                    ?>
                                    <tr>
                                        <td><?=$userRol->getName();?></td>
                                        <td class="text-center">
                                            <a href="<?=URI::toPage().'rolDelete/'.$user->getId().'?rolId='.$userRol->getId();?>" class="btn btn-circle btn-danger"><i class="fa fa-times"></i></a>
                                        </td>
                                    </tr>
                                    <?php
                                }
                                ?>
                                </tbody>
                            </table>
                            <?php
                        } else {
                            ?>
                            <p class="text-center">
                                * No se asignaron roles de usuario *
                            </p>
                            <?php
                        }
                        ?>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
$().ready(function(){
});
</script>