<?php
/**
 * Generated by Chocala Framework.
 * 
 */
class RelacionAreasController extends AdminWebController
{

    /**
    * @service RelacionAreasService
    * @var RelacionAreasService
    */
    protected $relacionAreasService;

    public function index()
    {
        $this->redirectTo(array('action' => 'dataList'));
    }

    public function dataList()
    {
        $filters = Req::all();
        $filters['_page'] = $filters['_page']?: 1;
        $filters['_max'] = $filters['_max']?: 10;
        $jobAreaRelacionadaPager = $this->relacionAreasService->dataList($filters);
        $this->set('jobAreaRelacionadaPager', $jobAreaRelacionadaPager);
    }

    public function show()
    {
        $jobAreaRelacionada = $this->relacionAreasService->findPk($this->id);
        $this->set('jobAreaRelacionada', $jobAreaRelacionada);
    }

    public function create()
    {
        $jobAreaRelacionada = new JobAreaRelacionada();
        $jobAreaTecnicaList = JobAreaTecnicaQuery::create()
                ->orderBy()->find();
        $this->set('jobAreaTecnicaList', $jobAreaTecnicaList);
        $jobAreaTecnicaList = JobAreaTecnicaQuery::create()
                ->orderBy()->find();
        $this->set('jobAreaTecnicaList', $jobAreaTecnicaList);
        $this->set('jobAreaRelacionada', $jobAreaRelacionada);
    }

    public function save()
    {
        $results = $this->relacionAreasService->insertOrUpdate(Req::all());
        $jobAreaRelacionada = $results['object'];
        if ($results['success']) {
            $this->redirectTo(array('action' => 'show',
                'id' => $jobAreaRelacionada->getPrimaryKey()));
        } else {
            $this->set('jobAreaRelacionada', $jobAreaRelacionada);
            $this->set('errors', $results['errors']);
        }
        $this->renderAsJSON();
    }

    public function edit()
    {
        $jobAreaRelacionada = $this->relacionAreasService->findPk($this->id);
    $jobAreaTecnicaList = JobAreaTecnicaQuery::create()
                ->orderBy()->find();
        $this->set('jobAreaTecnicaList', $jobAreaTecnicaList);
    $jobAreaTecnicaList = JobAreaTecnicaQuery::create()
                ->orderBy()->find();
        $this->set('jobAreaTecnicaList', $jobAreaTecnicaList);
        $this->set('jobAreaRelacionada', $jobAreaRelacionada);
    }

    public function update()
    {
        $jobAreaRelacionada = $this->relacionAreasService->findPk($this->id);
        $results = $this->relacionAreasService->insertOrUpdate(Req::all(), $jobAreaRelacionada);
        if ($results['success']) {
            $this->redirectTo(array('action' => 'show',
                'id' => $jobAreaRelacionada->getPrimaryKey()));
        } else {
            $this->set('jobAreaRelacionada', $jobAreaRelacionada);
            $this->set('errors', $results['errors']);
        }
        $this->renderAsJSON();
    }

    public function delete()
    {
        $jobAreaRelacionada = $this->relacionAreasService->findPk($this->id);
        try {
            $jobAreaRelacionada->delete();
            $this->redirectTo(array('action' => 'dataList'));
        } catch (Exception $e) {
            $this->redirectTo(array('action' => 'show',
                'id' => $jobAreaRelacionada->getPrimaryKey()));
        }
    }

}