
<div class="form-group">
    <label class="control-label col-sm-3" for="Visibility">Visibilidad</label>
    <div class="col-sm-9">
        <select id="Visibility" name="Visibility" class="form-control">
        <?php
        foreach(SysParam::visibilityMap('es') as $kVisibility => $vVisibility):
            $sel = $param && $param->getVisibility()==$kVisibility? 'selected="yes"': '';
        ?>
            <option value="<?=$kVisibility?>"><?=$vVisibility?></option>
        <?php
        endforeach;
        ?>
        </select>
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="Code">Código</label>
    <div class="col-sm-9">
        <input type="text" id="Code" name="Code" value="<?=$param? $param->getCode(): '';?>" placeholder="Code..."
               class="form-control" maxlength="30" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Name">Nombre</label>
    <div class="col-sm-9">
        <input type="text" id="Name" name="Name" value="<?=$param? $param->getName(): '';?>" placeholder="Name..."
               class="form-control" maxlength="100" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Type">Tipo</label>
    <div class="col-sm-9">
        <select id="Type" name="Type" class="form-control">
            <?php
            foreach(SysParam::typeList() as $vType):
                $sel = $param && $param->getType()==$vType? 'selected="yes"': '';
                ?>
                <option value="<?=$vType?>" <?=$sel;?>><?=$vType?></option>
                <?php
            endforeach;
            ?>
        </select>
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="Value">Valor</label>
    <div class="col-sm-9">
        <input type="text" id="Value" name="Value" value="<?=$param? $param->getValue(): '';?>" placeholder="Value..."
               class="form-control" maxlength="2000" />
    </div>
</div>
    
<div class="form-group" id="divOptions">
    <label class="control-label col-sm-3" for="Options">Opciones</label>
    <div class="col-sm-9">
        <input type="text" id="Options" name="Options" value="<?=$param? $param->getOptions(): '';?>" placeholder=""
               class="form-control" maxlength="2000" />
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="Customizable">Administrable</label>
    <div class="col-sm-1 text-left">
        <input type="checkbox" id="Customizable" name="Customizable" value="yes" <?=($param && $param->getCustomizable())? 'checked': '';?>
               class="form-control text-left" />
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Description">Descripción</label>
    <div class="col-sm-9">
        <textarea id="Description"  name="Description" placeholder="Description..."
                  class="form-control" rows="2" cols="25"><?=$param? $param->getDescription(): '';?></textarea>

    </div>
</div>

<script type="text/javascript">
    $().ready(function(){
        $('.ajaxPost').formAjaxPost();
    });
</script>