<?php
/**
 * Generated by Chocala Framework.
 * 
 */
class ParamService extends GenericService
{

    /**
    * @var ParamService
    */
    protected static $instance = null;

    /**
     * @param bool|true $noDeletes
     * @return SysParamQuery
     */
    public function validsQuery($noDeletes=true)
    {
        return SysParamQuery::createValids($noDeletes);
    }

    /**
     * @param $pk
     * @return array|mixed|SysParam
     * @throws ChocalaException
     */
    public function findPk($pk)
    {
        $object = $this->validsQuery()->findPk($pk);
        if (!is_object($object)) {
            throw new ChocalaException(ChocalaErrors::INVALID_RESOURCE);
        }
        return $object;
    }

    /**
     * @param array $filters
     * @return \Propel\Runtime\Util\PropelModelPager|SysParam[]
     */
    public function dataList($filters=[])
    {
        $query = $this->validsQuery()
            ->_if(isset($filters['visibility']))
                ->filterByVisibility($filters['visibility'])
            ->_endif()
            ->_if(isset($filters['code']))
                ->filterByCode('%'.$filters['code'].'%', Criteria::ILIKE)
            ->_endif()
            ->_if(isset($filters['name']))
                ->filterByName('%'.$filters['name'].'%', Criteria::ILIKE)
            ->_endif()
            ->_if(isset($filters['type']))
                ->filterByType($filters['type'])
            ->_endif()
            ->_if(isset($filters['customizable']))
                ->filterByCustomizable($filters['customizable'])
            ->_endif()
            ->orderByCode()
        ;
        $_page = $filters['_page']?: 1;
        $_max = $filters['_max']?: $query->count();
        return $query->paginate($_page, $_max);
    }

    /**
     * @param array $data
     * @param SysParam|null $object
     * @return array|mixed
     * @throws \Propel\Runtime\Exception\PropelException
     */
    public function insertOrUpdate($data, &$object = null)
    {
        if(!is_object($object)){
            $object = new SysParam();
        }
        $object->fromArray($data);
        $results['success'] = $object->validate();
        if ($results['success']) {
            $object->save();
        }
        $results['object'] = $object;
        $results['errors'] = $object->getErrorsMap();
        return $results;
    }

    /**
     * @param string $visibility
     * @param bool|null $customizables
     * @param array $filters
     * @return \Propel\Runtime\Util\PropelModelPager|SysParam[]
     */
    public function availableForVisibility($visibility, $customizables=null, $filters=[])
    {
        $filters['visibility'] = $visibility;
        if($customizables!==null){
            $filters['customizable'] = $customizables;
        }
        return $this->dataList($filters);
    }

    /**
     * @param array $filters
     * @return \Propel\Runtime\Util\PropelModelPager|SysParam[]
     */
    public function availableGlobals($filters=[])
    {
        return $this->availableForVisibility(SysParam::VISIBILITY_GLOBAL, null, $filters);
    }

    /**
     * @param bool|null $customizables If it's null then return all available, else apply the customizable filter
     * @param array $filters
     * @return \Propel\Runtime\Util\PropelModelPager|SysParam[]
     */
    public function availableForEntities($customizables=null, $filters=[])
    {
        return $this->availableForVisibility(SysParam::VISIBILITY_ENTITY, $customizables, $filters);
    }

    /**
     * @param bool|null $customizables If it's null then return all available, else apply the customizable filter
     * @param array $filters
     * @return \Propel\Runtime\Util\PropelModelPager|SysParam[]
     */
    public function availableForUsers($customizables=null, $filters=[])
    {
        return $this->availableForVisibility(SysParam::VISIBILITY_USER, $customizables, $filters);
    }

}