<?php
/**
 * Generated by Chocala Framework.
 * 
 */
class ParamController extends AdminWebController
{

    /**
    * @service ParamService Injected service
    * @var ParamService
    */
    protected $paramService;

    public function index()
    {
        $this->redirectTo(['action' => 'dataList']);
    }

    public function dataList()
    {
        $filters = Req::all();
        $filters['_page'] = $filters['_page']?: 1;
//        $filters['_max'] = $filters['_max']?: 10;
        $paramPager = $this->paramService->dataList($filters);
        $this->set('paramPager', $paramPager);
    }

    public function show()
    {
        $param = $this->objectIfExist();
        $this->set('param', $param);
    }

    public function create()
    {
        if(PageControl::canCreate()){
            $param = new SysParam();
            $this->set('param', $param);
        }
        $this->view->changeLayout('ajax');
    }

    public function save()
    {
        if(PageControl::canCreate()){
            $results = $this->paramService->insertOrUpdate(Req::all());
            $this->set('param', $results['object']);
            $this->set('success', $results['success']);
            $this->set('errors', $results['errors']);
        }
        $this->renderAsJSON();
    }

    public function edit()
    {
        if(PageControl::canUpdate()){
            $param = $this->objectIfExist();
            $this->set('param', $param);
        }
        $this->view->changeLayout('ajax');
    }

    public function update()
    {
        if(PageControl::canUpdate()){
            $param = $this->objectIfExist();
            $results = $this->paramService->insertOrUpdate(Req::all(), $param);
            $this->set('param', $param);
            $this->set('success', $results['success']);
            $this->set('errors', $results['errors']);
        }
        $this->renderAsJSON();
    }

    public function delete()
    {
        $param = $this->objectIfExist();
        try {
            $param->delete();
            $this->redirectTo(['action' => 'dataList']);
        } catch (Exception $e) {
            $this->redirectTo(['action' => 'show',
                'id' => $param->getPrimaryKey()]);
        }
    }

    public function objectIfExist()
    {
        try {
            return $this->paramService->findPk($this->id);
        } catch (ChocalaException $che) {
            HttpManager::responseAs404();
        }
    }

}