# Application code

app.code=CHOCALA_DEMO

# Application base configs
app.base.name=demo
app.base.description=Chocala Framework
app.base.version=1.0

# The run mode of deployment for application.
# Values: development | test | production
app.run.environment=production

# The debuging flag mode status.
# Values: off | on
app.run.debug=off

# The flag for run on modular mode.
# Values: off | on
app.run.modular=on

# The language in the app running
# Values: default | en | es | fr | de | it | ...
app.run.lang=

# The application default timezone
app.default.timezone=America/La_Paz

# The application default module
app.default.module=bolsa

# The application default controller
app.default.controller=trabajo

# The application default action
app.default.action=index

# The application no route
app.default.404=noRoute

# The application default layout
app.default.layout=default

# The application default template
app.default.template=index

# Default cookie name
cookie.default.name=jobs

# Default time to expire cookie
cookie.default.expire=86400

# Application name
system.name=demo

# Application name
system.description=Chocala Framework

# Application version
system.version=1.0