# Custom configurations are here
custom.config.name=value

email.info.address=info@empleos.click
email.info.fromName=El equipo de Empleos.Click
email.contact.address=contacto@empleos.click
email.contact.fromName=Contacto Empleos.Click
email.support.address=soporte@empleos.click
email.support.fromName=Soporte Empleos.Click
#email.tracker.uri=main/system/mailTracking/

google.key.development=00000000000
google.key.test=00000000000
google.key.production=00000000000
recaptcha.key.public=6Le3d94SAAAAA
recaptcha.key.private=6Le3d94SAAAAAA

dialog.create.title=Agregar
dialog.edit.title=Editar