<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Eventos
        <small>Sistema</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="index.html"><i class="fa fa-dashboard"></i> Inicio</a>
        </li>
        <li>
            <a>Eventos</a>
        </li>
        <li class="active">
            <strong>Listado General</strong>
        </li>
    </ol>
</section>

<?= BarView::renderBar('messages'); ?>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <?php if (PageControl::canCreate()): ?>
                <a href="<?= URI::toPage() . 'create'; ?>" class="btn btn-sm btn-primary btn-rounded"
                   data-toggle="modal" data-target="#ajax-modal">
                    <span class="fa fa-sm fa-plus-square"></span> Agregar Evento</a>
            <?php endif; ?>
            <div class="box-tools pull-right">
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">

            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover dataTables">
                    <thead>
                    <tr>
                        <th width="5%">Nº</th>
                        <th>Código</th>
                        <th>Nombre</th>
                        <th>Descripción</th>
                        <th width="15%">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    $toEditLink = URI::toPage() . 'edit/';
                    $toDeleteLink = URI::toPage() . 'delete/';
                    $i = 0;
                    foreach ($eventPager as $event):

                        $pk = $event->getId();

                        ?>
                        <tr role="row">
                            <td><?= $eventPager->getFirstIndex() + $i; ?></td>
                            <td><?= $event->getCode(); ?></td>
                            <td><?= $event->getName(); ?></td>
                            <td><?= $event->getDescription(); ?></td>
                            <td class="text-center">
                                <a href="<?= $toEditLink . $pk; ?>" class="btn btn-warning btn-circle"
                                   data-toggle="modal" data-target="#ajax-modal"><i class="fa fa-edit"></i></a>

                                <a href="<?= $toDeleteLink . $pk; ?>" class="btn btn-danger btn-circle"
                                   onclick="return confirm('¿Esta seguro de eliminar este registro?');"><i
                                            class="fa fa-times"></i></a>
                            </td>
                        </tr>
                        <?php
                        $i++;
                    endforeach;
                    ?>
                    </tbody>
                </table>
            </div>

        </div>
        <!-- /.box-body -->
        <div class="box-footer">
        </div>
        <!-- /.box-footer-->
    </div>
    <!-- /.box -->

</section>
<!-- /.content -->


<script>
    $(document).ready(function () {
        $('.dataTables').DataTable({
            language: {
                "emptyTable": "No se encontraron registros"
            },
            dom: '<"pull-right btn-group"B>lTfgitp',
            buttons: [
                {extend: 'copy', text: 'Copiar', className: 'btn-sm'},
                {extend: 'csv', text: 'CSV', className: 'btn-sm'},
                {extend: 'excel', text: 'Excel', className: 'btn-sm'},
                {extend: 'pdf', text: 'PDF', className: 'btn-sm'},
                {extend: 'print', text: 'Imprimir', className: 'btn-sm',
                    customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');
                        $(win.document.body).find('table')
                            .addClass('compact')
                            .css('font-size', 'inherit');
                    }
                }
            ]
        });
    });
</script>