<?php
/* @var SysEvent $event*/
?>
<div class="form-group">
    <label class="control-label col-sm-3" for="Code">Código</label>
    <div class="col-sm-9">
        
        <input type="text" id="Code" name="Code" value="<?=$event? $event->getCode(): '';?>" placeholder="Code..."
               class="form-control" maxlength="30" />
        
    </div>
</div>
    
<div class="form-group">
    <label class="control-label col-sm-3" for="Name">Nombre</label>
    <div class="col-sm-9">
        
        <input type="text" id="Name" name="Name" value="<?=$event? $event->getName(): '';?>" placeholder="Name..."
               class="form-control" maxlength="100" />
        
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="Type">Tipo</label>
    <div class="col-sm-9">

        <select id="Type" name="Type" class="form-control">
            <option value="">*Seleccionar*</option>
            <?php
            foreach($types as $kType => $vType) {
                $sel = ($event && $event->getType()==$kType)? 'selected="yes"': '';
            ?>
            <option value="<?=$kType;?>" <?=$sel;?>><?=__('SysEvent.type.'.$vType);?></option>
            <?php
            }
            ?>
        </select>

    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="Level">Nivel</label>
    <div class="col-sm-9">

        <select id="Level" name="Level" class="form-control">
            <option value="">*Seleccionar*</option>
            <?php
            foreach($levels as $kLevel => $vLevel) {
                $sel = ($event && $event->getLevel()==$kLevel)? 'selected="yes"': '';
            ?>
            <option value="<?=$kLevel;?>" <?=$sel;?>><?=__('SysEvent.level.'.$vLevel);?></option>
            <?php
            }
            ?>
        </select>

    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="Description">Descripción</label>
    <div class="col-sm-9">
        
        <textarea id="Description"  name="Description" placeholder="Description..."
                  class="form-control" rows="2" cols="25"><?=$event? $event->getDescription(): '';?></textarea>
        
    </div>
</div>
    
<script type="text/javascript">
$().ready(function(){
    $('.ajaxPost').formAjaxPost();
});
</script>