<?php
/**
 * Generated by Chocala Framework.
 * 
 */
class EntityParamController extends AdminWebController
{

    /**
    * @service EntityParamService Injected service
    * @var EntityParamService
    */
    protected $entityParamService;

    /**
    * @service customers.entity.EntityService Injected service
    * @var EntityService
    */
    protected $entityService;

    /**
    * @service admin.param.ParamService Injected service
    * @var ParamService
    */
    protected $paramService;

    public function index()
    {
        $this->redirectTo(['action' => 'dataList']);
    }

    public function dataList()
    {
        $filters = Req::all();
        $filters['_page'] = $filters['_page']?: 1;
        $filters['_max'] = $filters['_max']?: 10;
        $entityParamPager = $this->entityParamService->dataList($filters);
        $this->set('entityParamPager', $entityParamPager);
    }

    public function entity()
    {
        $entity = $this->entityService->findPk($this->id);
        $availableParams = $this->entityParamService->forEntitiesAvailable();
        $appliedParams = $this->entityParamService->appliedList($entity, true);
        $noAppliedParams = $this->entityParamService->noAppliedParams($entity, true);
        $genericParams = $this->entityParamService->forEntitiesAvailable(false);
        $this->set('entity', $entity);
        $this->set('availableParams', $availableParams);
        $this->set('appliedParams', $appliedParams);
        $this->set('noAppliedParams', $noAppliedParams);
        $this->set('genericParams', $genericParams);
    }

    public function editParam()
    {
        $param = $this->paramService->findPk(Req::_('paramId'));
        $entity = $this->entityService->findPk($this->id);
        $entityParam = $param->entityParam($entity);
        if(!is_object($entityParam)){
            $entityParam = new SysEntityParam();
            $entityParam->setSysEntity($entity);
            $entityParam->setSysParam($param);
        }
        $this->set('param', $param);
        $this->set('entityParam', $entityParam);
        $this->view->changeLayout('ajax');
    }

    public function updateParam()
    {
        $param = $this->paramService->findPk(Req::_('paramId'));
        $entity = $this->entityService->findPk(Req::_('entityId'));
        $entityParam = $param->entityParam($entity);
        if(!is_object($entityParam)){
            $entityParam = new SysEntityParam();
            $entityParam->setSysEntity($entity);
            $entityParam->setSysParam($param);
        }
        $results = $this->entityParamService->insertOrUpdate(Req::all(), $entityParam);
        $this->set('entityParam', $entityParam);
        $this->set('success', $results['success']);
        $this->set('errors', $results['errors']);
        $this->renderAsJSON();
    }

    public function delete()
    {
        $entityParam = $this->entityParamService->findPk($this->id);
        try {
            $entityParam->delete();
            $this->redirectTo(['action' => 'dataList']);
        } catch (Exception $e) {
            $this->redirectTo(['action' => 'show',
                'id' => $entityParam->getPrimaryKey()]);
        }
    }

}