<?php
/**
 * Generated by Chocala Framework.
 * 
 */
class EntityParamService extends GenericService
{

    /**
    * @var EntityParamService
    */
    protected static $instance = null;

    /**
     * @param bool|true $noDeletes
     * @return SysEntityParamQuery
     */
    public function validsQuery($noDeletes=true)
    {
        return SysEntityParamQuery::createValids($noDeletes);
    }

    /**
     * @param $pk
     * @return array|mixed|SysEntityParam
     * @throws NotFoundException
     */
    public function findPk($pk)
    {
        $entityParam = $this->validsQuery()->findPk($pk);
        if (!is_object($entityParam)) {
            throw new NotFoundException(ChocalaErrors::INVALID_RESOURCE);
        }
        return $entityParam;
    }

    /**
     * @param array $filters
     * @return \Propel\Runtime\Util\PropelModelPager|SysEntityParam[]
     * @throws \Propel\Runtime\Exception\PropelException
     */
    public function dataList($filters=[])
    {
        $query = $this->validsQuery()
            ->_if(isset($filters['entityId']))
                ->filterBySysEntity($filters['entityId'])
            ->_endif()
            ->_if(isset($filters['paramId']))
                ->filterBySysParam($filters['paramId'])
            ->_endif()
        ;
        $_page = $filters['_page']?: 1;
        $_max = $filters['_max']?: $query->count();
        return $query->paginate($_page, $_max);
    }

    /**
     * @param array $data
     * @param SysEntityParam|null $entityParam
     * @return mixed
     * @throws \Propel\Runtime\Exception\PropelException
     */
    public function insertOrUpdate($data, &$entityParam = null)
    {
        if(!is_object($entityParam)){
            $entityParam = new SysEntityParam();
        }
        $entityParam->fromArray($data);
        $results['success'] = $entityParam->validate();
        if ($results['success']) {
            $entityParam->save();
        }
        $results['object'] = $entityParam;
        $results['errors'] = $entityParam->getErrorsMap();
        return $results;
    }

    /**
     * @param bool|null $customizables
     * @param bool|true $noDeletes
     * @return \Propel\Runtime\Collection\ObjectCollection|SysParam[]
     */
    public function forEntitiesAvailable($customizables=null, $noDeletes=true)
    {
        return SysParamQuery::createForEntities($customizables, $noDeletes)->orderByName()->find();
    }

    /**
     * @param SysEntity $entity
     * @param bool|true $noDeletes
     * @return \Propel\Runtime\Collection\ObjectCollection|SysEntityParam[]
     * @throws \Propel\Runtime\Exception\PropelException
     */
    public function appliedList(SysEntity $entity, $noDeletes=true)
    {
        return SysEntityParamQuery::createForEntity($entity, $noDeletes)->find();
    }

    /**
     * @param SysEntity $entity
     * @param bool|null $customizables
     * @return \Propel\Runtime\Collection\ObjectCollection|SysParam[]
     */
    public function appliedParams(SysEntity $entity, $customizables=null)
    {
        $appliedIds = $this->appliedList($entity)->getArrayCopy('ParamId');
        return SysParamQuery::createForEntities($customizables)->filterById($appliedIds, Criteria::IN)->find();

    }

    /**
     * @param SysEntity $entity
     * @param array|null $customizables
     * @return \Propel\Runtime\Collection\ObjectCollection|SysParam[]
     */
    public function noAppliedParams(SysEntity $entity, $customizables=null)
    {
        $appliedIds = array_keys($this->appliedList($entity)->toArray('ParamId'));
        return SysParamQuery::createForEntities($customizables)->filterById($appliedIds, Criteria::NOT_IN)->find();
    }

}