<html>
<head>
    <meta name="generator" content="Chocala Framework" />
    <title>#SUBJECT#</title>
</head>
<body>
<div style="font-size: 13px; margin: 5px; padding: 10px; text-align: center;">
    <table align="center" border="0" cellpadding="0" cellspacing="0" width="600" style="border-collapse: collapse; margin: 0 auto; text-align: left;">
<!--        <tr><td style="color: #E36C0A; font-family: 'Calibri', Arial; font-size: 0.9em; font-style: italic; font-weight: bold;" width="100%">-->
<!--                <img src="--><?//=IMG_WEB;?><!--email/head.jpg" alt="Mi contador" title="" border="0" />-->
<!--            </td>-->
<!--        </tr>-->
        <tr><td style="border-left: 1px solid #D3D3D3; border-right: 1px solid #D3D3D3; color: #222222; font-family: 'Calibri', Arial; padding: 5px 10px;">
                #CONTENT#
            </td>
        </tr>
<!--        <tr><td style="color: #E36C0A; font-family: 'Calibri', Arial; font-size: 0.9em; font-style: italic; font-weight: bold;">-->
<!--                <img src="--><?//=IMG_WEB;?><!--email/foot.jpg" alt="Mi Contador" title="" border="0" />-->
<!--            </td>-->
<!--        </tr>-->
    </table>
    <img class="changeTrackingSrc" src="#TRACING_LINK#" alt="" title="">
</div>
</body>
</html>