<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Directorio Web de Empresas</h2>
        <ol class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li class="active">
                <strong>Datos Generales</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

    <?= BarView::renderBar('messages'); ?>

    <div class="row">

        <div class="col-lg-4 col-sm-12 ">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Lectura de Directorio Web</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">

                    <div class="btn-group">
                    </div>

                    <form id="formScraping" action="" method="post" role="form" class="ajaxPost form-horizontal">
                        <input type="hidden" id="action" name="action" value="readPages" />

                        <div class="form-group">
                            <label class="control-label col-sm-4" for="Departamento">Departamento</label>
                            <div class="col-sm-8">
                                <select id="Departamento" name="Departamento" class="form-control">
                                    <option value="">-Seleccionar-</option>
                                    <?php
                                    foreach($departamentos as $kDpto => $vDpto):
                                        $sel = Req::_('Departamento') ==  $kDpto? 'selected="yes"': '';
                                        ?>
                                        <option value="<?=$kDpto;?>" <?=$sel;?>><?=$vDpto;?></option>
                                        <?php
                                    endforeach;
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-4" for="Tiempo">Tiempo</label>
                            <div class="col-sm-8">
                                <select id="Tiempo" name="Tiempo" class="form-control">
                                    <?php
                                    for($t = 5; $t<=25; $t++):
                                        ?>
                                        <option value="<?=$t;?>"><?=$t;?> segundos</option>
                                        <?php
                                    endfor;
                                    ?>
                                </select>
                            </div>
                        </div>

                        <div class="text-right">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Leer Páginas</button>
                        </div>
                    </form>

                </div>
                <div class="ibox-footer">

                </div>
            </div>
        </div>

        <div class="col-lg-8 col-sm-12 ">

            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Páginas Leidas de Directorio Web - FUNDEMPRESA </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">

                    <div class="btn-group">
                    </div>

                    <div class="table-responsive">

                        <table class="table table-striped table-bordered table-hover dataTables" >
                            <thead>
                                <tr>
                                    <th width="5%">Nº</th>
                                    <th>Departamento</th>
                                    <th>Empresas</th>
                                    <th>Páginas Leidas</th>
                                    <th width="15%">Acciones</th>
                                </tr>
                            </thead>

                            <tbody>
                            <?php
                            $i = 0;
                            $toDepartamentoLink = URI::toPage().'departamento/';
                            foreach($resumenData as $infoDepto){
                                $i++;
                                $pk = $infoDepto['codigo'];
                                ?>
                                <tr class="<?=($i%2==0)? 'odd': 'even';?>">
                                    <td class="text-center"><?= $i; ?></td>
                                    <td class="text-left"><?= $infoDepto['nombre']; ?></td>
                                    <td class="text-right"><?= $infoDepto['cantidad']; ?></td>
                                    <td class="text-right"><?= $infoDepto['numPaginas']; ?></td>
                                    <td class="text-center">
                                        <a href="<?=$toEditLink.$pk;?>" class="btn btn-success btn-circle" title="Ver Detalles"><i class="fa fa-eye"></i></a>
                                    </td>
                                </tr>
                            <?php
                            }
                            ?>
                            </tbody>

                        </table>

                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

<!-- page script -->
<script type="text/javascript">
$().ready(function(){
    $('.dataTables').DataTable({
        "language": {
            "emptyTable": "No se encontraron registros"
        },
        dom: '<"html5buttons"B>lTfgitp',
        buttons: [
            {extend: 'copy', title: 'Copiar'},
            {extend: 'csv', title: 'Reporte CSV'},
            {extend: 'excel', title: 'Reporte Excel'},
            {extend: 'pdf', title: 'Reporte PDF'},
            {extend: 'print',
                customize: function (win){
                    $(win.document.body).addClass('white-bg');
                    $(win.document.body).css('font-size', '10px');
                    $(win.document.body).find('table')
                        .addClass('compact')
                        .css('font-size', 'inherit');
                }
            }
        ]
    });
    $('#formScraping').submit(function(){
        if($('#Departamento').val() == ""){
            alert("Debe seleccionar un Departamento.");
            return false;
        }
    });
});
</script>