[propel]

general.project     = domain
paths.phpConfDir    = .
paths.phpDir        = ..\..\%project%

database.connections.default.adapter          = mysql
database.connections.default.dsn              = "mysql:host=localhost;dbname=jobs;charset=UTF8"
database.connections.default.user             = root
database.connections.default.password         =
database.connections.default.settings.charset = utf8

database.connections.default.classname        = Propel\Runtime\Connection\DebugPDO
;database.connections.default.attributes       =

runtime.defaultConnection                     = default
runtime.connections[0]                        = default

generator.defaultConnection                   = default
generator.connections[0]                      = default
