<?php
/**
 * Generated by Chocala Framework.
 * 
 */
class EntityTypeController extends AdminWebController
{

    /**
    * @service EntityTypeService
    * @var EntityTypeService
    */
    protected $entityTypeService;

    public function index()
    {
        $this->redirectTo(['action' => 'dataList']);
    }

    public function dataList()
    {
        $filters = Req::all();
        $filters['_page'] = $filters['_page']?: 1;
        //$filters['_max'] = $filters['_max']?: 10;  //comment for all results
        $entityTypePager = $this->entityTypeService->dataList($filters);
        $this->set('entityTypePager', $entityTypePager);
    }

    public function show()
    {
        $sysEntityType = $this->objectIfExist();
        $this->set('sysEntityType', $sysEntityType);
    }

    public function create()
    {
        if(PageControl::canCreate()){
            $entityType = new SysEntityType();
            $this->set('entityType', $entityType);
        }
        $this->view->changeLayout('ajax');
    }

    public function save()
    {
        if(PageControl::canCreate()){
            $results = $this->entityTypeService->insertOrUpdate(Req::all());
            $this->set('entityType', $results['object']);
            $this->set('success', $results['success']);
            $this->set('errors', $results['errors']);
        }
        $this->renderAsJSON();
    }

    public function edit()
    {
        if(PageControl::canUpdate()){
            $entityType = $this->objectIfExist();
            $this->set('entityType', $entityType);
        }
        $this->view->changeLayout('ajax');
    }

    public function update()
    {
        if(PageControl::canUpdate()){
            $entityType = $this->objectIfExist();
            $results = $this->entityTypeService->insertOrUpdate(Req::all(), $entityType);
            $this->set('entityType', $results['object']);
            $this->set('success', $results['success']);
            $this->set('errors', $results['errors']);
        }
        $this->renderAsJSON();
    }

    public function delete()
    {
        $sysEntityType = $this->objectIfExist();
        try {
            $sysEntityType->delete();
            $this->redirectTo(['action' => 'dataList']);
        } catch (Exception $e) {
            $this->redirectTo(['action' => 'show',
                'id' => $sysEntityType->getPrimaryKey()]);
        }
    }

    public function objectIfExist()
    {
        try {
            return $this->entityTypeService->findPk($this->id);
        } catch (ChocalaException $che) {
            HttpManager::responseAs404();
        }
    }

}