<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title"><i class="fa fa-edit"></i>Editar de Usuario</h4>
</div>
<form action="<?=URI::toPage().'update';?>" method="post" role="form" class="form-horizontal ">
    <!--    <input type="hidden" id="action" name="action" value="update" />-->
    <input type="hidden" name="IdUsuarioEntidad" value="<?=$IdUsuarioEntidad;?>" />
    <input type="hidden" name="IdUsuario" value="<?=$usuario->getId();?>" />
    <input type="hidden" name="IdEntidad" value="<?=$entidad->getId();?>" />

    <div class="modal-body">
        <?php include('form.phtml'); ?>
    </div>
    <div class="modal-footer clearfix">
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Cancelar</button>
        <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Aceptar</button>
    </div>
</form>