<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Módulos del Sistema</h2>
        <ol class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>
                <a>Módulos del Sistema</a>
            </li>
            <li class="active">
                <strong>Listado General</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

    <?= BarView::renderBar('messages'); ?>

    <div class="row">

        <div class="ibox float-e-margins">

            <div class="ibox-title">
                <h5>Lista de Módulos del Sistema</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#">Opción 1</a>
                        </li>
                    </ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>

            <div class="ibox-content">

                <div class="btn-group">
                    <?php if(PageControl::canCreate()){ ?>
                    <a href="<?= URI::toPage().'create'; ?>" class="btn btn-sm btn-primary btn-rounded" data-toggle="modal" data-target="#ajax-modal">
                        <span class="fa fa-plus-square"></span> Agregar Módulo</a>
                    <?php } ?>
                </div>

                <div class="table-responsive">

                    <table class="table table-striped table-bordered table-hover dataTables" >
                        <thead>
                            <tr>
                                <th width="5%">Nº</th>
                                <th>Nombre</th>
                                <th>U.R.I.</th>
                                <th>Acceso</th>
                                <th>Descripción</th>
                                <th width="10%">
                                    URIs
                                </th>
                                <th width="15%">Acciones</th>
                            </tr>
                        </thead>

                        <tbody>
                        <?php
                        $i = 0;
                        $toURIsLink = URI::toModule() . 'uri/module/';
                        $toEditLink = URI::toPage().'edit/';
                        $toDeleteLink = URI::toPage().'delete/';
                        foreach($modulePager as $module){
                            $i++;
                            $pk = $module->getId();
                            ?>
                            <tr class="<?=($i%2==0)? 'odd': 'even';?>">
                                <td class="text-center"><?= $i; ?></td>
                                <td class="text-left"><?= $module->getName(); ?></td>
                                <td class="text-left"><?= $module->getUri(); ?></td>
                                <td class="text-left"><?= $module->getAccess(); ?></td>
                                <td class="text-left"><?= $module->getDescription(); ?></td>
                                <td class="text-center">
                                    <a href="<?=$toURIsLink.$pk;?>" class="btn btn-sm btn-success btn-rounded">
                                        <i class="fa fa-fw fa-key"></i> <?= $module->countSysUris(); ?> URIs
                                    </a>
                                </td>
                                <td class="text-center">
                                    <?php
                                    if(PageControl::canUpdate()){
                                        ?>
                                        <a href="<?=$toEditLink.$pk;?>" class="btn btn-sm btn-warning btn-circle" data-toggle="modal" data-target="#ajax-modal"><i class="fa fa-edit"></i></a>
                                        <?php
                                    }
                                    if(PageControl::canDelete()){
                                        ?>
                                        <a href="<?=$toDeleteLink.$pk;?>" class="btn btn-sm btn-danger btn-circle"><i class="fa fa-times"></i></a>
                                        <?php
                                    }
                                    ?>
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td class="paginateButtons" colspan="7">
                                    <?php if($modulePager->haveToPaginate()): ?>
                                        <p>Page <?= $modulePager->getPage(); ?> of <?= $modulePager->getLastPage(); ?> </p>
                                        <p>Displaying results <?= $modulePager->getFirstIndex(); ?> to <?= $modulePager->getLastIndex(); ?>
                                            on a total of <?= $modulePager->getNbResults(); ?> </p>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        </tfoot>

                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

<!-- page script -->
<script type="text/javascript">
$().ready(function(){
    $('.dataTables').DataTable({
        "language": {
            "emptyTable": "No se encontraron registros"
        },
        dom: '<"html5buttons"B>lTfgitp',
        buttons: [
            {extend: 'copy', title: 'Copiar'},
            {extend: 'csv', title: 'Reporte CSV'},
            {extend: 'excel', title: 'Reporte Excel'},
            {extend: 'pdf', title: 'Reporte PDF'},
            {extend: 'print',
                customize: function (win){
                    $(win.document.body).addClass('white-bg');
                    $(win.document.body).css('font-size', '10px');
                    $(win.document.body).find('table')
                        .addClass('compact')
                        .css('font-size', 'inherit');
                }
            }
        ]
    });
});
</script>