<div class="form-group">
    <label class="control-label col-sm-3" for="Name">Nombre</label>
    <div class="col-sm-9">
        <input type="text" id="Name" name="Name" placeholder="Nombre..." value="<?=$module? $module->getName(): '';?>"
               size="30" maxlength="30" class="form-control" autocomplete="off" />
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="Uri">URI</label>
    <div class="col-sm-9">
        <input type="text" id="Uri" name="Uri" placeholder="URI..." value="<?=$module? $module->getUri(): '';?>"
               size="30" maxlength="30" class="form-control" autocomplete="off" />
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="Access">Acceso</label>
    <div class="col-sm-9">
        <select id="Access" name="Access" class="form-control">
            <option value="">Seleccionar...</option>
            <?php
            foreach(PageConfigs::enumAccess() as $kAccess => $vAccess){
                $sel = $module? ($kAccess==$module->getAccess()? 'selected': ''): '';
                ?>
                <option value="<?=$kAccess;?>" <?=$sel;?>><?=$vAccess;?></option>
            <?php
            }
            ?>
        </select>
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="Description">Descripción</label>
    <div class="col-sm-9">
        <textarea id="Description" name="Description" placeholder="Descripción..."
                  cols="30" rows="2" class="form-control"><?=$module? $module->getDescription(): '';?></textarea>
    </div>
</div>

<div class="form-group">
    <label class="control-label col-sm-3" for="IconClass">Clase CSS</label>
    <div class="col-sm-9">
        <input type="text" id="IconClass" name="IconClass" placeholder="" value="<?=$module? $module->getIconClass(): '';?>"
               size="30" maxlength="100" class="form-control" autocomplete="off" />
    </div>
</div>